const mongoose = require('mongoose');

/**
 * Leave Register Schema
 * Maintains complete ledger of all leave transactions for audit transparency
 */

const leaveRegisterSchema = new mongoose.Schema({
    // Employee Information
    employeeId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Employee',
        required: true,
        index: true
    },
    empNo: {
        type: String,
        required: true,
        index: true
    },
    employeeName: {
        type: String,
        required: true
    },
    designation: {
        type: String,
        required: true
    },
    department: {
        type: String,
        required: true
    },
    divisionId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Division',
        required: true
    },
    departmentId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Department',
        required: true
    },
    dateOfJoining: {
        type: Date,
        required: true
    },
    employmentStatus: {
        type: String,
        enum: ['active', 'inactive', 'terminated', 'resigned'],
        default: 'active'
    },

    // Leave Transaction Details
    leaveType: {
        type: String,
        enum: ['EL', 'CL', 'SL', 'ML', 'OD', 'CCL', 'LWP'], // Earned, Casual, Sick, Maternity, On Duty, Compensatory, Leave Without Pay
        required: true,
        index: true
    },
    transactionType: {
        type: String,
        enum: ['CREDIT', 'DEBIT', 'ADJUSTMENT', 'CARRY_FORWARD', 'EXPIRY'],
        required: true,
        index: true
    },
    
    // Leave Dates and Duration
    startDate: {
        type: Date,
        required: true
    },
    endDate: {
        type: Date,
        required: true
    },
    days: {
        type: Number,
        min: 0
    },
    
    // Leave Application Details (for DEBIT transactions)
    applicationId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Leave'
    },
    applicationDate: {
        type: Date
    },
    approvalDate: {
        type: Date
    },
    approvedBy: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Employee'
    },
    status: {
        type: String,
        enum: ['PENDING', 'APPROVED', 'REJECTED', 'CANCELLED'],
        default: 'APPROVED'
    },
    reason: {
        type: String,
        trim: true,
        maxlength: [500, 'Purpose cannot exceed 500 characters']
    },

    // Balance Information (Ledger-style)
    openingBalance: {
        type: Number,
        min: 0
    },
    transactionAmount: {
        type: Number,
        min: 0
    },
    closingBalance: {
        type: Number,
        min: 0
    },
    
    // Financial Information
    leaveWagesPaid: {
        type: Number,
        default: 0
    },
    wageCalculationDetails: {
        basicSalary: Number,
        dailyRate: Number,
        leaveWageRate: Number,
        totalAmount: Number
    },

    // System Information
    month: {
        type: Number,
        min: 1,
        max: 12,
        required: true,
        index: true
    },
    year: {
        type: Number,
        required: true,
        index: true
    },
    financialYear: {
        type: String,
        required: true,
        index: true
    },
    
    // Payroll Cycle Period Details
    payrollCycleStart: {
        type: Date,
        required: true
    },
    payrollCycleEnd: {
        type: Date,
        required: true
    },
    
    // Financial Year Period Details
    financialYearStart: {
        type: Date,
        required: true
    },
    financialYearEnd: {
        type: Date,
        required: true
    },
    
    // Auto-generated flags
    autoGenerated: {
        type: Boolean,
        default: false
    },
    autoGeneratedType: {
        type: String,
        enum: ['EARNED_LEAVE', 'CARRY_FORWARD', 'ANNUAL_RESET', 'EXPIRY', 'INITIAL_BALANCE'],
        default: null
    },
    
    // Calculation Breakdown (for auto-generated entries)
    calculationBreakdown: {
        attendanceDays: Number,
        ranges: [{
            range: String,
            elEarned: Number,
            description: String
        }],
        calculation: String
    },

    // Audit Trail
    createdAt: {
        type: Date,
        default: Date.now,
        index: true
    },
    updatedAt: {
        type: Date,
        default: Date.now
    },
    createdBy: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Employee'
    },
    lastModifiedBy: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Employee'
    }
}, {
    timestamps: true,
    collection: 'leave_register'
});

// Indexes for performance
leaveRegisterSchema.index({ employeeId: 1, leaveType: 1, month: 1, year: 1 });
leaveRegisterSchema.index({ empNo: 1, leaveType: 1, month: 1, year: 1 });
leaveRegisterSchema.index({ transactionType: 1, month: 1, year: 1 });
leaveRegisterSchema.index({ createdAt: -1 });

// Static methods
leaveRegisterSchema.statics.getEmployeeBalance = function(employeeId, leaveType, asOfDate = new Date()) {
    const targetDate = new Date(asOfDate);
    const month = targetDate.getMonth() + 1;
    const year = targetDate.getFullYear();
    
    return this.findOne({
        employeeId,
        leaveType,
        month,
        year
    }).sort({ createdAt: -1 });
};

leaveRegisterSchema.statics.getEmployeeLedger = function(employeeId, leaveType, startDate, endDate) {
    return this.find({
        employeeId,
        leaveType,
        createdAt: {
            $gte: startDate,
            $lte: endDate
        }
    }).sort({ createdAt: 1 });
};

leaveRegisterSchema.statics.getLeaveRegister = function(filters = {}, month = null, year = null) {
    const query = {};
    
    if (filters.employeeId) query.employeeId = filters.employeeId;
    if (filters.empNo) query.empNo = filters.empNo;
    if (filters.leaveType) query.leaveType = filters.leaveType;
    if (filters.divisionId) query.divisionId = filters.divisionId;
    if (filters.departmentId) query.departmentId = filters.departmentId;
    if (filters.employmentStatus) query.employmentStatus = filters.employmentStatus;
    if (filters.transactionType) query.transactionType = filters.transactionType;
    
    if (month) query.month = month;
    if (year) query.year = year;
    
    if (filters.searchTerm) {
        query.$or = [
            { empNo: { $regex: filters.searchTerm, $options: 'i' } },
            { employeeName: { $regex: filters.searchTerm, $options: 'i' } },
            { designation: { $regex: filters.searchTerm, $options: 'i' } },
            { department: { $regex: filters.searchTerm, $options: 'i' } }
        ];
    }
    
    return this.find(query)
        .populate('employeeId', 'name email')
        .populate('approvedBy', 'name')
        .populate('createdBy', 'name')
        .sort({ createdAt: -1 });
};

// Instance methods
leaveRegisterSchema.methods.calculateNewBalance = function(previousBalance, transactionAmount) {
    if (this.transactionType === 'CREDIT') {
        return previousBalance + transactionAmount;
    } else if (this.transactionType === 'DEBIT') {
        return Math.max(0, previousBalance - transactionAmount);
    } else if (this.transactionType === 'ADJUSTMENT') {
        return transactionAmount; // For adjustments, set directly
    }
    return previousBalance;
};

leaveRegisterSchema.methods.updateClosingBalance = function(previousBalance) {
    this.openingBalance = previousBalance;
    this.closingBalance = this.calculateNewBalance(previousBalance, this.days);
    return this.closingBalance;
};

module.exports = mongoose.model('LeaveRegister', leaveRegisterSchema);
