const mongoose = require('mongoose');
const path = require('path');
const fs = require('fs');

require('dotenv').config();

// Mocking environment for standalone script
const dbUri = process.env.MONGODB_URI || 'mongodb://localhost:27017/hrms-ravi2';

// Import Models (Adjusting paths based on your structure)
const LeaveRegisterYear = require('../model/LeaveRegisterYear');
const Employee = require('../../employees/model/Employee');
const LeavePolicySettings = require('../../settings/model/LeavePolicySettings');

// --- Helper Logic ---
function round2(n) { return Math.round((Number(n) || 0) * 100) / 100; }
function roundHalf(x) {
  const n = Number(x) || 0;
  if (n <= 0) return 0;
  return Math.round(n * 2) / 2;
}

function sumUsedDaysForType(slot, leaveType) {
  const txs = Array.isArray(slot?.transactions) ? slot.transactions : [];
  const wantType = String(leaveType || '').toUpperCase();
  return round2(
    txs
      .filter((t) => {
        const tType = String(t?.transactionType || '').trim().toUpperCase();
        if (tType !== 'DEBIT') return false;
        const lt = String(t?.leaveType || '').trim().toUpperCase();
        if (lt !== wantType) return false;
        const status = String(t?.status || 'APPROVED').toUpperCase();
        if (status !== 'APPROVED' && status !== 'PENDING') return false;
        const ag = String(t?.autoGeneratedType || '');
        if (ag.startsWith('MONTHLY_POOL_TRANSFER_OUT_')) return false;
        return true;
      })
      .reduce((s, t) => s + Math.max(0, Number(t?.days) || 0), 0)
  );
}

function sumTotalPooledUsedDays(slot) {
  const txs = Array.isArray(slot?.transactions) ? slot.transactions : [];
  return round2(
    txs
      .filter((t) => {
        const tType = String(t?.transactionType || '').trim().toUpperCase();
        if (tType !== 'DEBIT') return false;
        const lt = String(t?.leaveType || '').trim().toUpperCase();
        if (lt !== 'CL' && lt !== 'CCL' && lt !== 'EL') return false;
        const status = String(t?.status || 'APPROVED').toUpperCase();
        if (status !== 'APPROVED' && status !== 'PENDING') return false;
        const ag = String(t?.autoGeneratedType || '');
        if (ag.startsWith('MONTHLY_POOL_TRANSFER_OUT_')) return false;
        return true;
      })
      .reduce((s, t) => s + Math.max(0, Number(t?.days) || 0), 0)
  );
}

function allocatePoolConsumption(U, clS, cclS, elS) {
  const clAlloc = Math.min(Math.max(0, U), Math.max(0, clS));
  let r = Math.max(0, U - clAlloc);
  const cclAlloc = Math.min(r, Math.max(0, cclS));
  r -= cclAlloc;
  const elAlloc = Math.min(r, Math.max(0, elS));
  return { clAlloc, cclAlloc, elAlloc, clRem: round2(clS - clAlloc), cclRem: round2(cclS - cclAlloc), elRem: round2(elS - elAlloc) };
}

function sumMonthlyPoolTransferInDaysOnSlot(slot, leaveType) {
    const lt = String(leaveType || '').toUpperCase();
    const txs = Array.isArray(slot?.transactions) ? slot.transactions : [];
    let s = 0;
    for (const t of txs) {
      if (String(t?.leaveType || '').toUpperCase() !== lt) continue;
      const ag = String(t?.autoGeneratedType || '');
      if (ag.startsWith('MONTHLY_POOL_TRANSFER_IN_')) {
        s += Math.max(0, Number(t?.days) || 0);
      }
    }
    return round2(s);
}

function sumMonthlyPoolTransferOutDaysOnSlot(slot, leaveType) {
    const lt = String(leaveType || '').toUpperCase();
    const txs = Array.isArray(slot?.transactions) ? slot.transactions : [];
    let s = 0;
    for (const t of txs) {
      if (String(t?.leaveType || '').toUpperCase() !== lt) continue;
      const ag = String(t?.autoGeneratedType || '');
      if (ag.startsWith('MONTHLY_POOL_TRANSFER_OUT_')) {
        s += Math.max(0, Number(t?.days) || 0);
      }
    }
    return round2(s);
}

async function runAudit() {
  try {
    await mongoose.connect(dbUri);
    console.log('Connected to DB');

    const report = [];
    const years = await LeaveRegisterYear.find().lean();
    
    for (const doc of years) {
      const sortedTxs = (doc.months || [])
        .flatMap(m => (m.transactions || []).map(t => ({ ...t, m })))
        .filter(t => t.leaveType === 'CL')
        .sort((a, b) => new Date(a.startDate) - new Date(b.startDate));

      for (const slot of doc.months || []) {
        if (!slot.payPeriodEnd) continue;

        const pm = slot.payrollCycleMonth;
        const py = slot.payrollCycleYear;
        
        // 1. Ledger Net Change (Closing - Opening) for CL
        const startMs = new Date(slot.payPeriodStart).getTime();
        const endMs = new Date(slot.payPeriodEnd).getTime();
        
        let openingCl = 0;
        let closingCl = 0;
        for (const tx of sortedTxs) {
          const s = new Date(tx.startDate).getTime();
          if (s < startMs) openingCl = Number(tx.closingBalance) || 0;
          if (s <= endMs) closingCl = Number(tx.closingBalance) || 0;
        }
        const ledgerNetChange = round2(closingCl - openingCl);

        // 2. Pool-aware (Scheduled - Allocated)
        const ledgerPooledUsed = sumTotalPooledUsedDays(slot);
        const U = roundHalf(Math.max(ledgerPooledUsed, Number(slot.monthlyApplyConsumed) || 0));
        const clS = roundHalf(slot.clCredits);
        const cclS = roundHalf(slot.compensatoryOffs);
        const elS = roundHalf(slot.elCredits);
        const alloc = allocatePoolConsumption(U, clS, cclS, elS);
        const poolAwareUnusedCl = alloc.clRem;

        // 3. Transaction-based Used
        const transUsedCl = sumUsedDaysForType(slot, 'CL');

        report.push({
          empNo: doc.empNo,
          employeeName: doc.employeeName,
          monthYear: `${pm}/${py}`,
          cl_scheduled: clS,
          cl_transferIn: sumMonthlyPoolTransferInDaysOnSlot(slot, 'CL'),
          cl_transferOut: sumMonthlyPoolTransferOutDaysOnSlot(slot, 'CL'),
          cl_balance: closingCl,
          cl_consumed_ledger_sum: transUsedCl,
          cl_consumed_monthlyApply: Number(slot.monthlyApplyConsumed) || 0,
          cl_unused_ledger_based: ledgerNetChange,
          cl_unused_pool_aware: poolAwareUnusedCl,
          ccl_scheduled: cclS,
          ccl_unused_pool_aware: alloc.cclRem,
          el_scheduled: elS,
          el_unused_pool_aware: alloc.elRem,
          raw_slot_data: slot
        });
      }
    }

    const outputPath = path.join(__dirname, 'leave_audit_report.json');
    fs.writeFileSync(outputPath, JSON.stringify(report, null, 2));
    console.log(`Audit complete. Data for ${report.length} slots saved to ${outputPath}`);
    
  } catch (err) {
    console.error('Audit failed:', err);
  } finally {
    await mongoose.disconnect();
  }
}

runAudit();
