const mongoose = require('mongoose');
require('dotenv').config();

async function run() {
  await mongoose.connect(process.env.MONGODB_URI);
  const db = mongoose.connection.db;

  const docs = await db.collection('leave_register_years').find({}).toArray();
  console.log(`Checking ${docs.length} documents...`);

  let mismatchCount = 0;
  for (const doc of docs) {
    for (let i = 0; i < doc.months.length; i++) {
      const slot = doc.months[i];
      const txs = slot.transactions || [];
      
      const sumDebits = txs
        .filter(t => String(t.transactionType || '').trim().toUpperCase() === 'DEBIT')
        .filter(t => {
          const ag = String(t.autoGeneratedType || '');
          if (ag.startsWith('MONTHLY_POOL_TRANSFER_OUT_')) return false;
          return true;
        })
        .reduce((s, t) => s + (Number(t.days) || 0), 0);

      // Simple check: if monthlyApplyApproved is > 0 and sumDebits is 0, it's a huge red flag
      const approved = Number(slot.monthlyApplyApproved) || 0;
      if (approved > 0 && sumDebits === 0) {
        console.log(`Mismatch found! Emp: ${doc.empNo}, Month: ${slot.payrollCycleMonth}/${slot.payrollCycleYear}`);
        console.log(`  monthlyApplyApproved: ${approved}, sumDebits: ${sumDebits}`);
        mismatchCount++;
        if (mismatchCount > 10) break;
      }
    }
    if (mismatchCount > 10) break;
  }

  console.log(`Total mismatches found in sample: ${mismatchCount}`);
  process.exit(0);
}

run().catch(console.error);
