require('dotenv').config({ path: require('path').join(__dirname, '../.env') });
const mongoose = require('mongoose');

(async () => {
  await mongoose.connect(process.env.MONGODB_URI);
  require('../departments/model/Designation');
  require('../departments/model/Department');
  require('../departments/model/Division');
  const Employee = require('../employees/model/Employee');
  const leaveRegisterService = require('../leaves/services/leaveRegisterService');
  const LeaveRegisterYear = require('../leaves/model/LeaveRegisterYear');
  const Leave = require('../leaves/model/Leave');

  const emp = await Employee.findOne({ $or: [{ emp_no: '1832' }, { emp_no: 1832 }] }).lean();
  const fy = '2026';
  const grouped = await leaveRegisterService.getLeaveRegister({ empNo: '1832', financialYear: fy }, null, null);
  const row = Array.isArray(grouped) ? grouped[0] : grouped;
  const months = row?.registerMonths || [];

  const doc = await LeaveRegisterYear.findOne({ employeeId: emp._id, financialYear: fy }).lean();
  const approved = await Leave.countDocuments({
    employeeId: emp._id,
    leaveType: /^CL$/i,
    status: 'approved',
    isActive: { $ne: false },
  });

  const through6 = months.filter((m) => {
    const y = Number(m.year);
    const mo = Number(m.month);
    return y < 2026 || (y === 2026 && mo <= 6);
  });

  console.log(
    JSON.stringify(
      {
        empNo: '1832',
        approvedClLeavesTotal: approved,
        registerMonthsThrough6: through6.map((m) => ({
          payroll: `${m.month}/${m.year}`,
          label: m.label,
          scheduledCl: m.scheduledCl,
          policyScheduledCl: m.policyScheduledCl,
          cl: {
            credited: m.cl?.credited,
            used: m.cl?.used,
            locked: m.cl?.locked,
            transferIn: m.cl?.transferIn,
            transferOut: m.cl?.transferOut,
          },
          clBalance: m.clBalance,
        })),
        slotTxSummary: (doc?.months || [])
          .filter((s) => Number(s.payrollCycleYear) === 2026 && Number(s.payrollCycleMonth) <= 6)
          .map((s) => ({
            payroll: `${s.payrollCycleMonth}/${s.payrollCycleYear}`,
            clCredits: s.clCredits,
            carryIn: s.poolCarryForwardIn?.cl,
            carryOut: s.poolCarryForwardOut?.cl,
            clDebits: (s.transactions || []).filter(
              (t) => t.leaveType === 'CL' && t.transactionType === 'DEBIT' && !String(t.autoGeneratedType || '').includes('TRANSFER')
            ).length,
            clDebitDays: (s.transactions || [])
              .filter(
                (t) =>
                  t.leaveType === 'CL' &&
                  t.transactionType === 'DEBIT' &&
                  !String(t.autoGeneratedType || '').startsWith('MONTHLY_POOL_TRANSFER')
              )
              .reduce((a, t) => a + (Number(t.days) || 0), 0),
            transferOut: (s.transactions || [])
              .filter((t) => String(t.autoGeneratedType || '') === 'MONTHLY_POOL_TRANSFER_OUT_CL')
              .reduce((a, t) => a + (Number(t.days) || 0), 0),
            transferIn: (s.transactions || [])
              .filter((t) => String(t.autoGeneratedType || '') === 'MONTHLY_POOL_TRANSFER_IN_CL')
              .reduce((a, t) => a + (Number(t.days) || 0), 0),
          })),
      },
      null,
      2
    )
  );

  await mongoose.disconnect();
})().catch(async (e) => {
  console.error(e);
  try {
    await mongoose.disconnect();
  } catch {}
  process.exit(1);
});
