/**
 * Find FY register slots where the same leave applicationId has BOTH:
 * - a leave DEBIT, and
 * - a CREDIT with reason "Leave Application Cancelled/Reversed"
 *
 * Also flags reversal CREDITs that inflate month compensatoryOffs pool math.
 *
 * Usage: node scripts/audit_leave_register_reversal_credit_pairs.js [--fy 2026] [--apply-fix]
 */
const mongoose = require('mongoose');
const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '../.env') });

const LeaveRegisterYear = require('../leaves/model/LeaveRegisterYear');
const Employee = require('../employees/model/Employee');

const REVERSAL_SNIP = 'Leave Application Cancelled/Reversed';

function isReversalCredit(tx) {
  return (
    String(tx?.transactionType || '').toUpperCase() === 'CREDIT' &&
    String(tx?.reason || '').includes(REVERSAL_SNIP)
  );
}

function isLeaveDebit(tx) {
  return (
    String(tx?.transactionType || '').toUpperCase() === 'DEBIT' &&
    !String(tx?.autoGeneratedType || '').startsWith('MONTHLY_POOL_TRANSFER_OUT_')
  );
}

function round2(v) {
  return Math.round((Number(v) || 0) * 100) / 100;
}

async function main() {
  const fyArg = process.argv.find((a) => a.startsWith('--fy='));
  const fyFilter = fyArg ? fyArg.split('=')[1] : process.argv.includes('--fy')
    ? process.argv[process.argv.indexOf('--fy') + 1]
    : null;

  if (!process.env.MONGODB_URI) {
    console.error('MONGODB_URI missing');
    process.exit(1);
  }
  await mongoose.connect(process.env.MONGODB_URI);

  const query = fyFilter ? { financialYear: String(fyFilter).trim() } : {};
  const docs = await LeaveRegisterYear.find(query)
    .select('employeeId empNo employeeName financialYear months compensatoryOffBalance')
    .lean();

  const paired = [];
  const reversalOnly = [];
  const debitOnlyOrphan = [];
  let totalReversalCredits = 0;
  let totalPairedApps = 0;

  for (const doc of docs) {
    for (const slot of doc.months || []) {
      const txs = slot.transactions || [];
      const byApp = new Map();

      for (const tx of txs) {
        const appId = tx.applicationId ? String(tx.applicationId) : null;
        if (!appId) continue;
        if (!byApp.has(appId)) {
          byApp.set(appId, { debits: [], reversalCredits: [], otherCredits: [] });
        }
        const b = byApp.get(appId);
        if (isLeaveDebit(tx)) b.debits.push(tx);
        else if (isReversalCredit(tx)) b.reversalCredits.push(tx);
        else if (String(tx.transactionType).toUpperCase() === 'CREDIT') b.otherCredits.push(tx);
      }

      for (const [appId, bucket] of byApp) {
        if (bucket.reversalCredits.length > 0) {
          totalReversalCredits += bucket.reversalCredits.length;
        }
        if (bucket.debits.length > 0 && bucket.reversalCredits.length > 0) {
          totalPairedApps += 1;
          const debitDays = bucket.debits.reduce((s, t) => s + (Number(t.days) || 0), 0);
          const revDays = bucket.reversalCredits.reduce((s, t) => s + (Number(t.days) || 0), 0);
          paired.push({
            empNo: doc.empNo,
            employeeName: doc.employeeName,
            financialYear: doc.financialYear,
            payrollCycleMonth: slot.payrollCycleMonth,
            payrollCycleYear: slot.payrollCycleYear,
            label: slot.label,
            applicationId: appId,
            leaveType: bucket.debits[0]?.leaveType || bucket.reversalCredits[0]?.leaveType,
            debitCount: bucket.debits.length,
            debitDays: round2(debitDays),
            reversalCount: bucket.reversalCredits.length,
            reversalDays: round2(revDays),
            scheduledCco: slot.compensatoryOffs,
            sampleDebitReason: (bucket.debits[0]?.reason || '').slice(0, 80),
          });
        } else if (bucket.reversalCredits.length > 0 && bucket.debits.length === 0) {
          reversalOnly.push({
            empNo: doc.empNo,
            financialYear: doc.financialYear,
            month: slot.payrollCycleMonth,
            year: slot.payrollCycleYear,
            applicationId: appId,
            leaveType: bucket.reversalCredits[0]?.leaveType,
            reversalDays: round2(
              bucket.reversalCredits.reduce((s, t) => s + (Number(t.days) || 0), 0)
            ),
          });
        }
      }

      // CCL month: count raw debits vs what UI "used" would net (for reporting)
      const cclDebits = txs.filter(
        (t) =>
          String(t.leaveType).toUpperCase() === 'CCL' &&
          isLeaveDebit(t)
      );
      const cclReversal = txs.filter(
        (t) => String(t.leaveType).toUpperCase() === 'CCL' && isReversalCredit(t)
      );
      if (cclDebits.length > 0 && cclReversal.length > 0) {
        const raw = round2(cclDebits.reduce((s, t) => s + (Number(t.days) || 0), 0));
        const rev = round2(cclReversal.reduce((s, t) => s + (Number(t.days) || 0), 0));
        if (raw > rev) {
          debitOnlyOrphan.push({
            empNo: doc.empNo,
            financialYear: doc.financialYear,
            month: slot.payrollCycleMonth,
            year: slot.payrollCycleYear,
            cclDebitLines: cclDebits.length,
            cclDebitDays: raw,
            cclReversalDays: rev,
            displayedUsedWouldBe: round2(Math.max(0, raw - rev)),
            scheduledCco: slot.compensatoryOffs,
          });
        }
      }
    }
  }

  const empNosPaired = new Set(paired.map((p) => String(p.empNo)));
  const empNosMonthInflated = new Set(debitOnlyOrphan.map((p) => String(p.empNo)));

  const summary = {
    scannedAt: new Date().toISOString(),
    financialYearFilter: fyFilter || 'all',
    leaveRegisterYearDocs: docs.length,
    employeesInScan: docs.length,
    /** Same leave: DEBIT + reversal CREDIT still both present (1890 pattern). */
    employeesWithDebitPlusReversalPair: empNosPaired.size,
    applicationPairsDebitPlusReversal: totalPairedApps,
    pairRows: paired.length,
    /** Reversal CREDIT but no matching debit (debit removed or never linked). */
    reversalCreditWithoutDebit: reversalOnly.length,
    employeesReversalOnly: new Set(reversalOnly.map((r) => String(r.empNo))).size,
    /** CCL month: at least one reversal CREDIT and debits; Used column nets to less than debit lines. */
    cclMonthsWithReversalAndDebits: debitOnlyOrphan.length,
    employeesWithCclMonthNetUsedMismatch: empNosMonthInflated.size,
    totalReversalCreditTransactions: totalReversalCredits,
  };

  console.log(JSON.stringify({ summary }, null, 2));

  if (paired.length > 0) {
    console.log('\n--- DEBIT + reversal CREDIT (same applicationId) — first 40 ---');
    console.log(JSON.stringify(paired.slice(0, 40), null, 2));
    if (paired.length > 40) {
      console.log(`\n... and ${paired.length - 40} more pair rows`);
    }
  }

  if (reversalOnly.length > 0) {
    console.log('\n--- Reversal CREDIT only (no debit for that app) — count by leave type ---');
    const byLt = {};
    for (const r of reversalOnly) {
      const lt = String(r.leaveType || '?').toUpperCase();
      byLt[lt] = (byLt[lt] || 0) + 1;
    }
    console.log(JSON.stringify(byLt, null, 2));
    console.log(JSON.stringify(reversalOnly.slice(0, 15), null, 2));
  }

  if (debitOnlyOrphan.length > 0) {
    console.log('\n--- CCL months: debits + reversal (Used shows debits − reversal) — first 25 ---');
    console.log(JSON.stringify(debitOnlyOrphan.slice(0, 25), null, 2));
  }

  // Write full paired list for HR review
  const fs = require('fs');
  const outPath = path.join(__dirname, '_audit_reversal_pairs.json');
  fs.writeFileSync(
    outPath,
    JSON.stringify({ summary, paired, reversalOnly, cclMonthsNetUsed: debitOnlyOrphan }, null, 2)
  );
  console.log(`\nFull report: ${outPath}`);

  await mongoose.disconnect();
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
