const mongoose = require('mongoose');
require('dotenv').config();

const Employee = require('../employees/model/Employee');
const LeaveRegisterYear = require('../leaves/model/LeaveRegisterYear');
const dateCycleService = require('../leaves/services/dateCycleService');
const { extractISTComponents } = require('../shared/utils/dateUtils');

function roundHalf(x) {
  const n = Number(x) || 0;
  if (n <= 0) return 0;
  return Math.round(n * 2) / 2;
}

async function main() {
  const empNo = String(process.argv[2] || '').trim();
  const dateStr = String(process.argv[3] || '').trim(); // YYYY-MM-DD
  if (!empNo || !dateStr) {
    throw new Error('Usage: node debug_employee_ccl_credit_bucket.js <empNo> <YYYY-MM-DD>');
  }

  const uri = process.env.MONGO_URI || 'mongodb://localhost:27017/hrms';
  await mongoose.connect(uri);

  const emp = await Employee.findOne({ emp_no: empNo }).select('_id emp_no employee_name doj').lean();
  if (!emp) throw new Error(`Employee not found for emp_no=${empNo}`);

  const dt = new Date(`${dateStr}T12:00:00+05:30`); // mid-day IST to avoid TZ edge
  const period = await dateCycleService.getPeriodInfo(dt);
  const fy = period.financialYear.name;
  const pm = Number(period.payrollCycle.month);
  const py = Number(period.payrollCycle.year);

  const y = await LeaveRegisterYear.findOne({ employeeId: emp._id, financialYear: fy }).lean();
  if (!y) throw new Error(`LeaveRegisterYear missing for FY=${fy} emp=${empNo}`);

  const slot = (y.months || []).find(
    (m) => Number(m.payrollCycleMonth) === pm && Number(m.payrollCycleYear) === py
  );
  if (!slot) throw new Error(`No slot for payroll ${pm}/${py} in FY ${fy}`);

  const cclCredits = (slot.transactions || []).filter(
    (t) => String(t.leaveType).toUpperCase() === 'CCL' && String(t.transactionType).toUpperCase() === 'CREDIT'
  );

  const creditSum = roundHalf(cclCredits.reduce((s, t) => s + (Number(t.days) || 0), 0));

  console.log(
    JSON.stringify(
      {
        empNo,
        date: dateStr,
        dateIST: extractISTComponents(dt).dateStr,
        payrollCycle: {
          month: pm,
          year: py,
          startIST: extractISTComponents(period.payrollCycle.startDate).dateStr,
          endIST: extractISTComponents(period.payrollCycle.endDate).dateStr,
        },
        financialYear: fy,
        slotPool_compensatoryOffs: Number(slot.compensatoryOffs) || 0,
        slotPoolCarryInCcl: Number(slot.poolCarryForwardIn?.ccl) || 0,
        cclCreditTxCountInSlot: cclCredits.length,
        cclCreditDaysSumInSlot: creditSum,
        sampleCredits: cclCredits.slice(0, 3).map((t) => ({
          days: t.days,
          startDate: t.startDate,
          reason: t.reason,
          autoGeneratedType: t.autoGeneratedType || null,
        })),
      },
      null,
      2
    )
  );

  await mongoose.disconnect();
}

main().catch(async (e) => {
  console.error(e?.message || e);
  try {
    await mongoose.disconnect();
  } catch {}
  process.exit(1);
});

