/**
 * Dev: reset monthly pool carry artifacts for one closing payroll month, then rerun
 * the same steps as monthlyAccrualCron (postMonthlyAccruals + processPayrollCycleCarryForward).
 * Optional FY carry-edge simulation (read-only) across consecutive slots.
 *
 * Strip rules: only removes MONTHLY_POOL_TRANSFER_OUT_* on the closing month and
 * MONTHLY_POOL_TRANSFER_IN_* on the next month (does not remove prior-month transfer-ins on the closing slot).
 * Before strip, reposts missing transfer-in rows when the previous month still has matching OUT_* (repair).
 * Clears `poolCarryForwardOutAt` with null so Mongoose persists (delete alone can leave the flag set).
 *
 * Usage:
 *   node scripts/dev_rerun_payroll_closing_for_employee.js --empNo 2213 --closingMonth 4 --closingYear 2026
 *   node scripts/dev_rerun_payroll_closing_for_employee.js --empNo 2213 --closingMonth 4 --closingYear 2026 --apply
 *   node scripts/dev_rerun_payroll_closing_for_employee.js --all --closingMonth 4 --closingYear 2026
 *   node scripts/dev_rerun_payroll_closing_for_employee.js --all --activeOnly --closingMonth 4 --closingYear 2026 --apply
 *   node scripts/dev_rerun_payroll_closing_for_employee.js --all --apply --verbose   (include per-employee strip rows in JSON)
 *   node scripts/dev_rerun_payroll_closing_for_employee.js --printFullMongoUri …   (optional: log full URI; avoid in shared logs)
 *   node scripts/dev_rerun_payroll_closing_for_employee.js --preferShellMongo …   (use OS/shell MONGODB_URI; do not override from .env)
 *
 * `--all`: every employee who has a LeaveRegisterYear for `--financialYear` with a slot for that closing payroll month.
 * Per employee: repair orphan transfer-in → strip edge → save → recalc → sync. Then once for everyone: postMonthlyAccruals
 * → processPayrollCycleCarryForward. Then per employee: CCL recalc + sync next-period anchor.
 *
 * Requires MONGODB_URI in backend/.env (or process.env). By default this script loads `.env` with
 * `override: true` so **backend/.env wins** over a MONGODB_URI already set in the OS/shell (common
 * reason the “wrong” Atlas host is used). Use `--preferShellMongo` to keep the shell value instead.
 *
 * Requires MONGODB_URI (see backend/.env).
 */

const path = require('path');

/** Log line for scripts: hides user:password in standard Mongo connection strings. */
function redactMongoUriForLog(uri) {
  const s = String(uri || '');
  const m = s.match(/^(mongodb(?:\+srv)?:\/\/)([^/@]+)@/);
  if (!m) return s.length > 200 ? `${s.slice(0, 200)}…` : s;
  const creds = m[2];
  if (!creds.includes(':')) return `${m[1]}***@` + s.slice(m[0].length);
  return `${m[1]}***:***@` + s.slice(m[0].length);
}

const BACKEND_ENV_PATH = path.join(__dirname, '../.env');
const preferShellMongo = process.argv.includes('--preferShellMongo');
const mongodbUriBeforeEnvFile = process.env.MONGODB_URI;
require('dotenv').config({
  path: BACKEND_ENV_PATH,
  /** If false, a MONGODB_URI set in Windows / terminal wins over backend/.env (dotenv default). */
  override: !preferShellMongo,
});

const mongoose = require('mongoose');

require('../departments/model/Designation');
require('../departments/model/Department');
require('../departments/model/Division');

const Employee = require('../employees/model/Employee');
const LeaveRegisterYear = require('../leaves/model/LeaveRegisterYear');

const accrualEngine = require('../leaves/services/accrualEngine');
const dateCycleService = require('../leaves/services/dateCycleService');
const leaveRegisterService = require('../leaves/services/leaveRegisterService');
const leaveRegisterYearLedgerService = require('../leaves/services/leaveRegisterYearLedgerService');
const leaveRegisterYearMonthlyApplyService = require('../leaves/services/leaveRegisterYearMonthlyApplyService');
const monthlyPoolCarryForwardService = require('../leaves/services/monthlyPoolCarryForwardService');
const { sumUsedDaysForType } = require('../leaves/services/leaveRegisterYearService');
const LeavePolicySettings = require('../settings/model/LeavePolicySettings');

function parseArg(name) {
  const key = String(name).replace(/^--/, '');
  const idx = process.argv.findIndex((a) => a === `--${key}`);
  if (idx >= 0 && process.argv[idx + 1] != null) return process.argv[idx + 1];
  return undefined;
}

function hasFlag(name) {
  return process.argv.includes(`--${name}`);
}

function roundHalf(x) {
  const n = Number(x) || 0;
  if (n <= 0) return 0;
  return Math.round(n * 2) / 2;
}

const POOL_OUT = {
  CL: 'MONTHLY_POOL_TRANSFER_OUT_CL',
  CCL: 'MONTHLY_POOL_TRANSFER_OUT_CCL',
  EL: 'MONTHLY_POOL_TRANSFER_OUT_EL',
};
const POOL_IN = {
  CL: 'MONTHLY_POOL_TRANSFER_IN_CL',
  CCL: 'MONTHLY_POOL_TRANSFER_IN_CCL',
  EL: 'MONTHLY_POOL_TRANSFER_IN_EL',
};

function sumPoolTransferDays(slot, autoType) {
  if (!Array.isArray(slot?.transactions)) return 0;
  let s = 0;
  for (const t of slot.transactions) {
    if (String(t?.autoGeneratedType || '') !== autoType) continue;
    const typ = String(t?.transactionType || '').toUpperCase();
    if (autoType.startsWith('MONTHLY_POOL_TRANSFER_OUT_') && typ === 'DEBIT') s += roundHalf(Number(t.days) || 0);
    else if (autoType.startsWith('MONTHLY_POOL_TRANSFER_IN_') && typ === 'CREDIT') s += roundHalf(Number(t.days) || 0);
  }
  return roundHalf(s);
}

function findSlotIdx(months, pm, py) {
  return (months || []).findIndex(
    (m) => Number(m.payrollCycleMonth) === Number(pm) && Number(m.payrollCycleYear) === Number(py)
  );
}

function sortSlots(months) {
  return (months || [])
    .map((m, idx) => ({ idx, m, t: new Date(m?.payPeriodStart || m?.payPeriodEnd || 0).getTime() }))
    .sort((a, b) => a.t - b.t);
}

/** Remove pool transfer txs and carry flags between closing month and next slot; revert next slot pool bumps from poolCarryForwardIn. */
function stripMonthlyPoolCarryForClosing(doc, closingPm, closingPy) {
  const ordered = sortSlots(doc.months);
  const curPos = ordered.findIndex(
    (x) => Number(x.m.payrollCycleMonth) === Number(closingPm) && Number(x.m.payrollCycleYear) === Number(closingPy)
  );
  if (curPos < 0) return { ok: false, reason: 'closing_slot_not_found' };
  const next = ordered[curPos + 1];
  if (!next) return { ok: false, reason: 'no_next_slot' };

  const closeSlot = doc.months[ordered[curPos].idx];
  const nextSlot = doc.months[next.idx];

  const pin = nextSlot.poolCarryForwardIn || {};
  const dCl = roundHalf(Number(pin.cl) || 0);
  const dCcl = roundHalf(Number(pin.ccl) || 0);
  const dEl = roundHalf(Number(pin.el) || 0);

  nextSlot.clCredits = roundHalf(Math.max(0, (Number(nextSlot.clCredits) || 0) - dCl));
  nextSlot.compensatoryOffs = roundHalf(Math.max(0, (Number(nextSlot.compensatoryOffs) || 0) - dCcl));
  nextSlot.elCredits = roundHalf(Math.max(0, (Number(nextSlot.elCredits) || 0) - dEl));
  delete nextSlot.poolCarryForwardIn;
  delete nextSlot.poolCarryForwardFromLabel;

  // Only strip this payroll edge: keep MONTHLY_POOL_TRANSFER_IN_* on the closing month
  // (they belong to the prior edge, e.g. March→April) and keep OUT_* on the next month if any.
  if (Array.isArray(closeSlot.transactions)) {
    closeSlot.transactions = closeSlot.transactions.filter(
      (t) => !String(t?.autoGeneratedType || '').startsWith('MONTHLY_POOL_TRANSFER_OUT_')
    );
  }
  if (Array.isArray(nextSlot.transactions)) {
    nextSlot.transactions = nextSlot.transactions.filter(
      (t) => !String(t?.autoGeneratedType || '').startsWith('MONTHLY_POOL_TRANSFER_IN_')
    );
  }

  // Use null (not delete) so Mongoose persists the cleared closing flag; otherwise carry-forward stays skipped.
  closeSlot.poolCarryForwardOutAt = null;
  closeSlot.poolCarryForwardOut = { cl: 0, ccl: 0, el: 0 };
  closeSlot.poolCarryForwardAllocation = undefined;

  return {
    ok: true,
    revertedNext: { cl: dCl, ccl: dCcl, el: dEl },
    closingLabel: `${closingPm}/${closingPy}`,
    nextLabel: `${nextSlot.payrollCycleMonth}/${nextSlot.payrollCycleYear}`,
  };
}

async function buildEmpPayload(employeeId) {
  const employee = await Employee.findById(employeeId)
    .select('_id emp_no employee_name department_id division_id designation_id doj is_active')
    .populate('department_id', 'name')
    .populate('division_id', 'name')
    .populate('designation_id', 'name')
    .lean();
  if (!employee) return null;
  return {
    employeeId: employee._id,
    empNo: employee.emp_no,
    employeeName: employee.employee_name || 'N/A',
    designation: employee.designation_id?.name || 'N/A',
    department: employee.department_id?.name || 'N/A',
    divisionId: employee.division_id?._id || employee.division_id,
    departmentId: employee.department_id?._id || employee.department_id,
    dateOfJoining: employee.doj,
    employmentStatus: employee.is_active ? 'active' : 'inactive',
  };
}

/**
 * Repost missing MONTHLY_POOL_TRANSFER_IN_* on the closing slot when the previous month still has matching OUT_* (e.g. after an older strip removed IN rows from the closing month).
 */
async function repairOrphanPoolTransferInFromPreviousMonth(employeeId, fyName, closingPm, closingPy) {
  const doc = await LeaveRegisterYear.findOne({ employeeId, financialYear: String(fyName).trim() });
  if (!doc?.months?.length) return { ok: false, reason: 'no_doc' };
  const ordered = sortSlots(doc.months);
  const curPos = ordered.findIndex(
    (x) => Number(x.m.payrollCycleMonth) === Number(closingPm) && Number(x.m.payrollCycleYear) === Number(closingPy)
  );
  if (curPos < 1) return { ok: true, repaired: [] };
  const prevSlot = ordered[curPos - 1].m;
  const closeSlot = ordered[curPos].m;
  const prevLabel = `${prevSlot.payrollCycleMonth}/${prevSlot.payrollCycleYear}`;
  const closeLabel = `${closeSlot.payrollCycleMonth}/${closeSlot.payrollCycleYear}`;
  const anchor = closeSlot.payPeriodStart || closeSlot.payPeriodEnd;
  if (!anchor) return { ok: false, reason: 'no_anchor' };

  const empPayload = await buildEmpPayload(employeeId);
  if (!empPayload) return { ok: false, reason: 'no_employee' };

  const repaired = [];
  for (const lt of ['CL', 'CCL', 'EL']) {
    const outAuto = POOL_OUT[lt];
    const inAuto = POOL_IN[lt];
    const outSum = sumPoolTransferDays(prevSlot, outAuto);
    const inSum = sumPoolTransferDays(closeSlot, inAuto);
    const gap = roundHalf(outSum - inSum);
    if (gap <= 0) continue;

    await leaveRegisterService.addTransaction({
      ...empPayload,
      leaveType: lt,
      transactionType: 'CREDIT',
      startDate: anchor,
      endDate: anchor,
      days: gap,
      reason: `Repair: pool transfer in ${lt} from payroll ${prevLabel} → ${closeLabel} (reposted missing ledger row).`,
      status: 'APPROVED',
      autoGenerated: true,
      autoGeneratedType: inAuto,
      payrollCycleMonth: Number(closingPm),
      payrollCycleYear: Number(closingPy),
    });
    repaired.push({ leaveType: lt, days: gap });
  }
  return { ok: true, repaired };
}

async function carryEdgeSimulation(employeeId, fyName) {
  const policy = await LeavePolicySettings.getSettings().catch(() => ({}));
  const doc = await LeaveRegisterYear.findOne({ employeeId, financialYear: String(fyName).trim() }).lean();
  if (!doc?.months?.length) return { ok: false, reason: 'no_year_doc' };

  const elInPool = (() => {
    const capCfg = policy?.monthlyLeaveApplicationCap || {};
    const includeEL = !!capCfg?.includeEL;
    const elPaidInPayroll = policy?.earnedLeave?.useAsPaidInPayroll !== false;
    return !!policy?.earnedLeave?.enabled && includeEL && !elPaidInPayroll;
  })();

  const clRoll = policy?.carryForward?.casualLeave?.carryMonthlyClCreditToNextPayrollMonth !== false;
  const cclRoll = policy?.carryForward?.compensatoryOff?.carryMonthlyPoolToNextPayrollMonth !== false;
  const elRoll =
    elInPool && policy?.carryForward?.earnedLeave?.carryMonthlyPoolToNextPayrollMonth !== false;

  const ordered = sortSlots(doc.months);
  const edges = [];
  for (let p = 0; p < ordered.length - 1; p++) {
    const cur = ordered[p].m;
    const nxt = ordered[p + 1].m;
    const pm = Number(cur.payrollCycleMonth);
    const py = Number(cur.payrollCycleYear);
    const clS = roundHalf(Number(cur.clCredits) || 0);
    const cclS = roundHalf(Number(cur.compensatoryOffs) || 0);
    const elS = elInPool ? roundHalf(Number(cur.elCredits) || 0) : 0;
    const usedCl = roundHalf(sumUsedDaysForType(cur, 'CL'));
    const clLocked = roundHalf(Number(cur.lockedCredits) || 0);
    const usedCcl = roundHalf(sumUsedDaysForType(cur, 'CCL'));
    const usedEl = roundHalf(sumUsedDaysForType(cur, 'EL'));
    const clCarry = clRoll ? roundHalf(Math.max(0, clS - usedCl - clLocked)) : 0;
    const cclCarry = cclRoll ? roundHalf(Math.max(0, cclS - usedCcl)) : 0;
    const elCarry = elRoll ? roundHalf(Math.max(0, elS - usedEl)) : 0;
    const already = !!cur.poolCarryForwardOutAt;
    edges.push({
      from: `${pm}/${py}`,
      to: `${nxt.payrollCycleMonth}/${nxt.payrollCycleYear}`,
      alreadyClosedInDb: already,
      scheduledPools: { cl: clS, ccl: cclS, el: elS },
      ledgerUsed: { cl: usedCl, ccl: usedCcl, el: usedEl, clLocked },
      wouldCarry: { cl: clCarry, ccl: cclCarry, el: elCarry },
    });
  }
  return { ok: true, financialYear: fyName, edges };
}

async function registerCclSlice(employeeId, fy, calendarYear) {
  const cy = Number(calendarYear) || new Date().getFullYear();
  const grouped = await leaveRegisterService.getLeaveRegister({ employeeId, financialYear: fy }, null, null);
  const row = Array.isArray(grouped) ? grouped[0] : grouped;
  const months = row?.registerMonths || [];
  const pick = (m, y) => months.find((x) => Number(x.month) === m && Number(x.year) === y);
  const apr = pick(4, cy);
  const may = pick(5, cy);
  return {
    yearCclBalance: row?.yearSnapshot?.compensatoryOffBalance ?? row?.leaveRegisterYear?.compensatoryOffBalance,
    april: apr
      ? {
          scheduledCco: apr.scheduledCco,
          policyScheduledCco: apr.policyScheduledCco,
          ccl: apr.ccl,
        }
      : null,
    may: may
      ? {
          scheduledCco: may.scheduledCco,
          policyScheduledCco: may.policyScheduledCco,
          ccl: may.ccl,
        }
      : null,
  };
}

async function distinctEmployeeIdsForClosingSlot(fy, closingMonth, closingYear) {
  const pm = Number(closingMonth);
  const py = Number(closingYear);
  return LeaveRegisterYear.distinct('employeeId', {
    financialYear: String(fy).trim(),
    months: { $elemMatch: { payrollCycleMonth: pm, payrollCycleYear: py } },
  });
}

/**
 * Repair + strip closing→next edge, save, ledger recalc, sync apply fields for the closing period only.
 */
async function applyPerEmployeePoolStripAndSync(employeeId, fy, closingMonth, closingYear) {
  const repair = await repairOrphanPoolTransferInFromPreviousMonth(employeeId, fy, closingMonth, closingYear);
  const docFresh = await LeaveRegisterYear.findOne({ employeeId, financialYear: String(fy).trim() });
  if (!docFresh) {
    return { ok: false, repair, error: 'no_year_doc_after_repair' };
  }
  const strip = stripMonthlyPoolCarryForClosing(docFresh, closingMonth, closingYear);
  if (!strip.ok) {
    return { ok: false, repair, strip, error: strip.reason || 'strip_failed' };
  }
  docFresh.markModified('months');
  await docFresh.save();
  await leaveRegisterYearLedgerService.recalculateRegisterBalances(employeeId, 'CL', null);
  await leaveRegisterYearLedgerService.recalculateRegisterBalances(employeeId, 'CCL', null);
  await leaveRegisterYearLedgerService.recalculateRegisterBalances(employeeId, 'EL', null);
  const pc = await dateCycleService.getPayrollCycleForMonth(closingYear, closingMonth);
  await leaveRegisterYearMonthlyApplyService.syncStoredMonthApplyFieldsForEmployeeDate(employeeId, pc.endDate);
  return { ok: true, repair, strip };
}

async function finalizeAfterGlobalPoolCarry(employeeId, closingMonth, closingYear) {
  await leaveRegisterYearLedgerService.recalculateRegisterBalances(employeeId, 'CCL', null);
  const pc = await dateCycleService.getPayrollCycleForMonth(closingYear, closingMonth);
  const nextM = closingMonth + 1;
  const nextY = nextM > 12 ? closingYear + 1 : closingYear;
  const nextMonth = nextM > 12 ? 1 : nextM;
  const pcNext = await dateCycleService.getPayrollCycleForMonth(nextY, nextMonth);
  const anchor = pcNext?.startDate || pc.endDate;
  await leaveRegisterYearMonthlyApplyService.syncStoredMonthApplyFieldsForEmployeeDate(employeeId, anchor);
}

async function main() {
  const allMode = hasFlag('all');
  const empNo = parseArg('empNo') || '2213';
  const closingMonth = Number(parseArg('closingMonth') || '4');
  const closingYear = Number(parseArg('closingYear') || '2026');
  const fy = String(parseArg('financialYear') || '2026').trim();
  const apply = hasFlag('apply');
  const activeOnly = hasFlag('activeOnly');
  const verbose = hasFlag('verbose');

  const uri = process.env.MONGODB_URI;
  if (!uri) {
    console.error('MONGODB_URI missing');
    process.exit(1);
  }
  console.log('[dev_rerun_payroll_closing] Database: process.env.MONGODB_URI');
  console.log('[dev_rerun_payroll_closing] .env path:', BACKEND_ENV_PATH);
  console.log(
    '[dev_rerun_payroll_closing] dotenv override:',
    preferShellMongo ? 'false (--preferShellMongo: shell/OS wins)' : 'true (backend/.env wins)'
  );
  if (
    mongodbUriBeforeEnvFile &&
    mongodbUriBeforeEnvFile !== uri &&
    !preferShellMongo
  ) {
    console.log(
      '[dev_rerun_payroll_closing] Prior MONGODB_URI was replaced by backend/.env (redacted before → after):'
    );
    console.log('  ', redactMongoUriForLog(mongodbUriBeforeEnvFile));
    console.log('  ', redactMongoUriForLog(uri));
  }
  console.log('[dev_rerun_payroll_closing] MONGODB_URI in use (redacted):', redactMongoUriForLog(uri));
  if (hasFlag('printFullMongoUri')) {
    console.log('[dev_rerun_payroll_closing] MONGODB_URI (full):', uri);
  }
  await mongoose.connect(uri);

  if (allMode) {
    let employeeIds = await distinctEmployeeIdsForClosingSlot(fy, closingMonth, closingYear);
    if (activeOnly && employeeIds.length) {
      const activeIds = await Employee.find({ _id: { $in: employeeIds }, is_active: true }).distinct('_id');
      const activeSet = new Set(activeIds.map((id) => String(id)));
      employeeIds = employeeIds.filter((id) => activeSet.has(String(id)));
    }

    const emps = await Employee.find({ _id: { $in: employeeIds } })
      .select('_id emp_no employee_name is_active')
      .lean();
    const empById = new Map(emps.map((e) => [String(e._id), e]));

    const out = {
      ok: true,
      mode: 'all',
      closing: { month: closingMonth, year: closingYear },
      financialYear: fy,
      activeOnly,
      apply,
      targetCount: employeeIds.length,
    };

    if (!apply) {
      out.employees = employeeIds.map((id) => {
        const e = empById.get(String(id));
        return { emp_no: e?.emp_no, name: e?.employee_name, is_active: e?.is_active };
      });
      console.log(JSON.stringify(out, null, 2));
      await mongoose.disconnect();
      return;
    }

    const perEmployee = [];
    let stripOk = 0;
    let stripFail = 0;
    for (const employeeId of employeeIds) {
      const e = empById.get(String(employeeId));
      const row = { emp_no: e?.emp_no, employeeId: String(employeeId) };
      try {
        const r = await applyPerEmployeePoolStripAndSync(employeeId, fy, closingMonth, closingYear);
        if (r.ok) stripOk++;
        else stripFail++;
        row.ok = r.ok;
        if (verbose) {
          row.result = r;
        } else {
          if (!r.ok) row.error = r.error;
          if (r.repair?.repaired?.length) row.repaired = r.repair.repaired;
        }
        perEmployee.push(row);
      } catch (err) {
        stripFail++;
        perEmployee.push({
          ...row,
          ok: false,
          error: err?.message || String(err),
        });
      }
    }

    const accrual = await accrualEngine.postMonthlyAccruals(closingMonth, closingYear);
    const pool = await monthlyPoolCarryForwardService.processPayrollCycleCarryForward(closingMonth, closingYear);

    const finalizeErrors = [];
    for (const employeeId of employeeIds) {
      try {
        await finalizeAfterGlobalPoolCarry(employeeId, closingMonth, closingYear);
      } catch (err) {
        finalizeErrors.push({
          employeeId: String(employeeId),
          emp_no: empById.get(String(employeeId))?.emp_no,
          error: err?.message || String(err),
        });
      }
    }

    out.summary = {
      stripOk,
      stripFail,
      postMonthlyAccruals: accrual,
      processPayrollCycleCarryForward: pool,
      finalizeErrorCount: finalizeErrors.length,
    };
    if (verbose) {
      out.perEmployee = perEmployee;
    } else {
      out.perEmployeeFailures = perEmployee.filter((r) => r.ok === false || r.error);
      out.perEmployeeSampleOk = perEmployee.filter((r) => r.ok !== false && !r.error).slice(0, 5);
    }
    if (finalizeErrors.length) {
      out.finalizeErrors = finalizeErrors.slice(0, 50);
    }

    console.log(JSON.stringify(out, null, 2));
    await mongoose.disconnect();
    return;
  }

  const emp = await Employee.findOne({
    $or: [{ emp_no: String(empNo) }, { emp_no: Number(empNo) }],
  })
    .select('_id emp_no employee_name')
    .lean();
  if (!emp) {
    console.log(JSON.stringify({ ok: false, error: 'Employee not found', empNo }, null, 2));
    await mongoose.disconnect();
    process.exit(0);
  }

  const out = {
    ok: true,
    employee: { emp_no: emp.emp_no, name: emp.employee_name },
    closing: { month: closingMonth, year: closingYear },
    apply,
    steps: [],
  };

  const beforeRegister = await registerCclSlice(emp._id, fy, closingYear);
  const beforeSim = await carryEdgeSimulation(emp._id, fy);
  out.beforeRegisterCcl = beforeRegister;
  out.fyCarryEdgeSimulation = beforeSim;

  const doc = await LeaveRegisterYear.findOne({ employeeId: emp._id, financialYear: fy });
  const cIdx = doc ? findSlotIdx(doc.months, closingMonth, closingYear) : -1;
  const aprilSlot = cIdx >= 0 ? doc.months[cIdx] : null;
  out.aprilSlotFlags = aprilSlot
    ? {
        poolCarryForwardOutAt: !!aprilSlot.poolCarryForwardOutAt,
        poolCarryForwardOut: aprilSlot.poolCarryForwardOut || null,
      }
    : null;

  if (apply && doc) {
    const r = await applyPerEmployeePoolStripAndSync(emp._id, fy, closingMonth, closingYear);
    out.steps.push({ perEmployee: r });
    if (!r.ok) {
      out.steps.push({ error: r.error || 'per_employee_failed' });
    } else {
      const accrual = await accrualEngine.postMonthlyAccruals(closingMonth, closingYear);
      out.steps.push({ postMonthlyAccruals: accrual });

      const pool = await monthlyPoolCarryForwardService.processPayrollCycleCarryForward(
        closingMonth,
        closingYear
      );
      out.steps.push({ processPayrollCycleCarryForward: pool });

      await finalizeAfterGlobalPoolCarry(emp._id, closingMonth, closingYear);
    }
  } else if (apply && !doc) {
    out.steps.push({ error: 'No LeaveRegisterYear for FY; cannot apply' });
  }

  out.afterRegisterCcl = await registerCclSlice(emp._id, fy, closingYear);
  out.fyCarryEdgeSimulationAfter = await carryEdgeSimulation(emp._id, fy);

  console.log(JSON.stringify(out, null, 2));
  await mongoose.disconnect();
}

main().catch(async (e) => {
  console.error(e?.message || e);
  try {
    await mongoose.disconnect();
  } catch {}
  process.exit(1);
});
