const path = require('path');
const mongoose = require('mongoose');
require('dotenv').config({ path: path.join(__dirname, '../.env') });
require('../departments/model/Designation');
require('../departments/model/Department');
require('../departments/model/Division');
const Employee = require('../employees/model/Employee');
const Leave = require('../leaves/model/Leave');
const LeaveRegisterYear = require('../leaves/model/LeaveRegisterYear');
const leaveRegisterService = require('../leaves/services/leaveRegisterService');

async function explainMarch(empNo) {
  const emp = await Employee.findOne({
    $or: [{ emp_no: String(empNo) }, { emp_no: Number(empNo) }],
  }).lean();
  const doc = await LeaveRegisterYear.findOne({
    employeeId: emp._id,
    financialYear: '2026',
  }).lean();
  const slot = (doc.months || []).find(
    (m) => m.payrollCycleMonth === 3 && m.payrollCycleYear === 2026
  );

  const grouped = await leaveRegisterService.getLeaveRegister(
    { employeeId: emp._id, financialYear: '2026' },
    null,
    null
  );
  const row = Array.isArray(grouped) ? grouped[0] : grouped;
  const uiMonth = (row?.registerMonths || []).find((m) => m.month === 3 && m.year === 2026);

  const leaves = await Leave.find({
    employeeId: emp._id,
    isActive: { $ne: false },
    fromDate: { $lte: slot.payPeriodEnd },
    toDate: { $gte: slot.payPeriodStart },
  })
    .select('_id leaveType status fromDate toDate numberOfDays reason splitStatus')
    .lean();

  const clDebits = (slot.transactions || []).filter(
    (t) =>
      String(t.leaveType) === 'CL' &&
      String(t.transactionType).toUpperCase() === 'DEBIT' &&
      !String(t.autoGeneratedType || '').includes('TRANSFER')
  );

  const poolIn = Number(slot.poolCarryForwardIn?.cl) || 0;
  const poolOut = Number(slot.poolCarryForwardOut?.cl) || 0;
  const clCredits = Number(slot.clCredits) || 0;
  const policyScheduled = uiMonth?.policyScheduledCl ?? null;

  console.log(
    JSON.stringify(
      {
        empNo: emp.emp_no,
        name: emp.employee_name,
        marchPayrollPeriod: {
          start: slot.payPeriodStart,
          end: slot.payPeriodEnd,
        },
        uiDisplay: {
          policyScheduledCl: uiMonth?.policyScheduledCl,
          scheduledClTotal: uiMonth?.scheduledCl,
          clUsedShown: uiMonth?.cl?.used,
          clTransferIn: uiMonth?.cl?.transferIn,
          clTransferOut: uiMonth?.cl?.transferOut,
        },
        ledgerSlot: {
          clCredits,
          poolCarryForwardIn: poolIn,
          poolCarryForwardOut: poolOut,
          impliedPolicyOnly: clCredits - poolIn,
        },
        math: {
          poolTotal: `${policyScheduled ?? clCredits - poolIn} scheduled + ${poolIn} carry-in = ${clCredits} total pool`,
          minusUsed: uiMonth?.cl?.used ?? '?',
          expectedTransferOutIfZeroUsed: clCredits,
          actualTransferOut: poolOut,
          difference: clCredits - poolOut,
        },
        approvedLeavesInMarchPeriod: leaves.map((l) => ({
          id: String(l._id),
          type: l.leaveType,
          status: l.status,
          days: l.numberOfDays,
          from: l.fromDate,
          to: l.toDate,
          reason: (l.reason || '').slice(0, 50),
        })),
        clDebitsInMarchLedger: clDebits.map((t) => ({
          days: t.days,
          reason: (t.reason || '').slice(0, 70),
          applicationId: t.applicationId ? String(t.applicationId) : null,
          status: t.status,
        })),
        poolCarryForwardAllocation: slot.poolCarryForwardAllocation || null,
      },
      null,
      2
    )
  );
}

async function main() {
  await mongoose.connect(process.env.MONGODB_URI);
  await explainMarch(process.argv[2] || '06');
  await mongoose.disconnect();
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
