/**
 * Export an Excel workbook: every employee × each payroll month in a FY,
 * with grouped headers (month) and sub-headers Credits | Used | Balance for CCL.
 *
 * Data source: LeaveRegisterYear.months[] (registerDisplaySnapshot when present,
 * otherwise derived from slot transactions).
 *
 * Usage (from backend/, with MONGODB_URI in .env):
 *   node scripts/export_ccl_monthly_credits_used_balance.js --fy 2025-2026
 *   node scripts/export_ccl_monthly_credits_used_balance.js --fy 2025-2026 --month 4
 *   node scripts/export_ccl_monthly_credits_used_balance.js --fy 2025-2026 --month 4 --year 2026
 *
 * Optional:
 *   --month N              — only calendar month N (1–12), e.g. 4 = April
 *   --year YYYY            — with --month, restrict to that payroll year (payrollCycleYear)
 *   MONTH=4 YEAR=2026      — same via env
 *   OUT=./exports/ccl.xlsx
 *   ACTIVE_ONLY=1          — only employees with is_active !== false
 *   INCLUDE_CCL_CARRY_IN=1 — count MONTHLY_POOL_TRANSFER_IN_CCL toward Credits (default: exclude)
 */

require('dotenv').config({ path: require('path').resolve(__dirname, '../.env') });
const fs = require('fs');
const path = require('path');
const mongoose = require('mongoose');
const XLSX = require('xlsx');

// Register refs used by Employee.populate('department_id', 'division_id')
require('../departments/model/Department');
require('../departments/model/Division');

const LeaveRegisterYear = require('../leaves/model/LeaveRegisterYear');
const Employee = require('../employees/model/Employee');

const MONTH_NAMES = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

function round2(v) {
  const n = Number(v) || 0;
  return Math.round(n * 100) / 100;
}

function parseMonthYearFromEnv() {
  const mRaw = process.env.MONTH;
  const yRaw = process.env.YEAR;
  let month = mRaw !== undefined && mRaw !== '' ? Number(mRaw) : null;
  let year = yRaw !== undefined && yRaw !== '' ? Number(yRaw) : null;
  if (month != null && (!Number.isFinite(month) || month < 1 || month > 12)) month = null;
  if (year != null && (!Number.isFinite(year) || year < 1900 || year > 2100)) year = null;
  return { month, year };
}

/** @returns {{ fy: string, filterMonth: number | null, filterYear: number | null }} */
function parseArgs() {
  const argv = process.argv.slice(2);
  let fy = process.env.FINANCIAL_YEAR || process.env.FY || '';
  let filterMonth = null;
  let filterYear = null;
  const fromEnv = parseMonthYearFromEnv();
  if (fromEnv.month != null) filterMonth = fromEnv.month;
  if (fromEnv.year != null) filterYear = fromEnv.year;

  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === '--fy' && argv[i + 1]) {
      fy = argv[i + 1];
      i++;
    } else if (argv[i] === '--month' && argv[i + 1]) {
      const n = Number(argv[i + 1]);
      if (Number.isFinite(n) && n >= 1 && n <= 12) filterMonth = n;
      i++;
    } else if (argv[i] === '--year' && argv[i + 1]) {
      const n = Number(argv[i + 1]);
      if (Number.isFinite(n) && n >= 1900 && n <= 2100) filterYear = n;
      i++;
    }
  }
  return { fy: String(fy || '').trim(), filterMonth, filterYear };
}

function slotSortKey(s) {
  const t = s?.payPeriodStart ? new Date(s.payPeriodStart).getTime() : 0;
  const m = Number(s?.payrollCycleMonth) || 0;
  const y = Number(s?.payrollCycleYear) || 0;
  return t || y * 100 + m;
}

function monthLabel(m, y) {
  if (!Number.isFinite(m) || m < 1 || m > 12 || !Number.isFinite(y)) return '—';
  return `${MONTH_NAMES[m - 1]} ${y}`;
}

function monthKey(m, y) {
  return `${y}-${String(m).padStart(2, '0')}`;
}

function sumUsedCcl(slot) {
  const txs = Array.isArray(slot?.transactions) ? slot.transactions : [];
  return round2(
    txs
      .filter(
        (t) =>
          String(t?.leaveType || '').toUpperCase() === 'CCL' && String(t?.transactionType || '').toUpperCase() === 'DEBIT'
      )
      .filter((t) => !String(t?.autoGeneratedType || '').startsWith('MONTHLY_POOL_TRANSFER_OUT_'))
      .reduce((s, t) => s + Math.max(0, Number(t?.days) || 0), 0)
  );
}

function includeCarryInCredits() {
  return process.env.INCLUDE_CCL_CARRY_IN === '1' || process.env.INCLUDE_CCL_CARRY_IN === 'true';
}

function sumCreditCcl(slot) {
  const txs = Array.isArray(slot?.transactions) ? slot.transactions : [];
  const carryIn = includeCarryInCredits();
  return round2(
    txs
      .filter(
        (t) =>
          String(t?.leaveType || '').toUpperCase() === 'CCL' &&
          String(t?.transactionType || '').toUpperCase() === 'CREDIT'
      )
      .filter((t) => carryIn || String(t?.autoGeneratedType || '') !== 'MONTHLY_POOL_TRANSFER_IN_CCL')
      .reduce((s, t) => s + Math.max(0, Number(t?.days) || 0), 0)
  );
}

function lastCclClosingBalance(slot) {
  const txs = Array.isArray(slot?.transactions) ? slot.transactions : [];
  let last = null;
  for (const t of txs) {
    if (String(t?.leaveType || '').toUpperCase() !== 'CCL') continue;
    if (Number.isFinite(Number(t?.closingBalance))) last = Number(t.closingBalance);
  }
  return last;
}

/**
 * Credits = CCL CREDIT days posted in the slot (optional carry-in).
 * Used / Balance prefer registerDisplaySnapshot (same basis as leave register UI when synced).
 */
function extractCclTriple(slot) {
  const snap = slot?.registerDisplaySnapshot?.ccl;
  const usedFallback = sumUsedCcl(slot);
  const creditFallback = sumCreditCcl(slot);
  const balanceFallback = lastCclClosingBalance(slot);

  let credits = creditFallback;
  if (snap && snap.scheduledTotal != null && Number.isFinite(Number(snap.scheduledTotal))) {
    credits = round2(Number(snap.scheduledTotal));
    if (credits === 0 && creditFallback > 0) credits = creditFallback;
  }

  let used = usedFallback;
  if (snap && snap.used != null && Number.isFinite(Number(snap.used))) used = round2(Number(snap.used));

  let balance = balanceFallback != null ? round2(balanceFallback) : '';
  if (snap && snap.ledgerBalance != null && Number.isFinite(Number(snap.ledgerBalance))) {
    balance = round2(Number(snap.ledgerBalance));
  }

  return { credits, used, balance };
}

async function main() {
  const { fy: financialYear, filterMonth, filterYear } = parseArgs();
  if (!financialYear) {
    console.error(
      'Usage: node scripts/export_ccl_monthly_credits_used_balance.js --fy 2025-2026 [--month 4] [--year 2026]'
    );
    process.exit(1);
  }
  if (!process.env.MONGODB_URI) {
    console.error('MONGODB_URI is not set (check backend/.env).');
    process.exit(1);
  }

  const activeOnly =
    process.env.ACTIVE_ONLY === '1' || process.env.ACTIVE_ONLY === 'true' || process.env.ACTIVE_ONLY === 'yes';
  const monthSuffix =
    filterMonth != null
      ? `_m${String(filterMonth).padStart(2, '0')}${filterYear != null ? `_y${filterYear}` : ''}`
      : '';
  const outPath =
    process.env.OUT ||
    path.join(
      __dirname,
      '../exports',
      `ccl_monthly_${financialYear.replace(/[^\w-]+/g, '_')}${monthSuffix}_${Date.now()}.xlsx`
    );

  await mongoose.connect(process.env.MONGODB_URI);

  const empQuery = activeOnly ? { is_active: { $ne: false } } : {};
  const employees = await Employee.find(empQuery)
    .select('emp_no employee_name division_id department_id is_active')
    .populate('division_id', 'name')
    .populate('department_id', 'name')
    .sort({ emp_no: 1 })
    .lean();

  const yearDocs = await LeaveRegisterYear.find({ financialYear })
    .select('employeeId empNo employeeName months')
    .lean();

  const yearByEmp = new Map();
  for (const y of yearDocs) {
    yearByEmp.set(String(y.employeeId), y);
  }

  const monthKeysOrdered = [];
  const seen = new Set();
  for (const y of yearDocs) {
    const months = Array.isArray(y.months) ? [...y.months].sort((a, b) => slotSortKey(a) - slotSortKey(b)) : [];
    for (const s of months) {
      const pm = Number(s.payrollCycleMonth);
      const py = Number(s.payrollCycleYear);
      if (!Number.isFinite(pm) || !Number.isFinite(py)) continue;
      const k = monthKey(pm, py);
      if (!seen.has(k)) {
        seen.add(k);
        monthKeysOrdered.push({ key: k, month: pm, year: py, label: monthLabel(pm, py) });
      }
    }
  }
  monthKeysOrdered.sort((a, b) => a.year * 100 + a.month - (b.year * 100 + b.month));

  let monthsForExport = monthKeysOrdered;
  if (filterMonth != null) {
    monthsForExport = monthKeysOrdered.filter((mk) => {
      if (mk.month !== filterMonth) return false;
      if (filterYear != null && mk.year !== filterYear) return false;
      return true;
    });
  }
  if (filterMonth != null && monthsForExport.length === 0) {
    const hint =
      filterYear != null
        ? `No payroll slot found for month=${filterMonth} year=${filterYear} in FY ${financialYear}.`
        : `No payroll slot found for month=${filterMonth} in FY ${financialYear}. Try adding --year <payrollCycleYear>.`;
    console.error(hint);
    process.exit(1);
  }

  const fixedCols = 4;
  const perMonth = 3;
  const totalCols = fixedCols + monthsForExport.length * perMonth;

  const headerRow0 = new Array(totalCols).fill('');
  headerRow0[0] = 'Emp No';
  headerRow0[1] = 'Employee name';
  headerRow0[2] = 'Division';
  headerRow0[3] = 'Department';
  const headerRow1 = new Array(totalCols).fill('');
  headerRow1[0] = '';
  headerRow1[1] = '';
  headerRow1[2] = '';
  headerRow1[3] = '';

  const merges = [];
  let c = fixedCols;
  for (const mk of monthsForExport) {
    headerRow0[c] = mk.label;
    headerRow1[c] = 'Credits';
    headerRow1[c + 1] = 'Used';
    headerRow1[c + 2] = 'Balance';
    merges.push({ s: { r: 0, c }, e: { r: 0, c: c + 2 } });
    c += perMonth;
  }

  const rows = [headerRow0, headerRow1];

  for (const emp of employees) {
    const row = new Array(totalCols).fill('');
    row[0] = emp.emp_no ?? '';
    row[1] = emp.employee_name ?? '';
    row[2] = (emp.division_id && emp.division_id.name) || '';
    row[3] = (emp.department_id && emp.department_id.name) || '';
    const ydoc = yearByEmp.get(String(emp._id));
    const slotByKey = new Map();
    if (ydoc && Array.isArray(ydoc.months)) {
      for (const s of ydoc.months) {
        const pm = Number(s.payrollCycleMonth);
        const py = Number(s.payrollCycleYear);
        if (!Number.isFinite(pm) || !Number.isFinite(py)) continue;
        slotByKey.set(monthKey(pm, py), s);
      }
    }
    let col = fixedCols;
    for (const mk of monthsForExport) {
      const slot = slotByKey.get(mk.key);
      if (!slot) {
        row[col] = '';
        row[col + 1] = '';
        row[col + 2] = '';
      } else {
        const { credits, used, balance } = extractCclTriple(slot);
        row[col] = credits;
        row[col + 1] = used;
        row[col + 2] = balance;
      }
      col += perMonth;
    }
    rows.push(row);
  }

  const ws = XLSX.utils.aoa_to_sheet(rows);
  ws['!merges'] = merges;
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, 'CCL by month');

  const dir = path.dirname(outPath);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  XLSX.writeFile(wb, outPath);

  const filterDesc =
    filterMonth != null
      ? `month=${filterMonth}${filterYear != null ? ` year=${filterYear}` : ''}`
      : 'all months';
  console.log(
    `Wrote ${outPath} (employees=${employees.length}, FY=${financialYear}, ${filterDesc}, columns=${monthsForExport.length})`
  );
  await mongoose.disconnect();
}

main().catch((e) => {
  console.error(e);
  mongoose.disconnect().finally(() => process.exit(1));
});
