/**
 * Excel report for the ~12% of employees where register GRID (view) ≠ TRANSACTION popup sum.
 *
 * Usage:
 *   node scripts/export_display_vs_transaction_mismatch_excel.js
 *   node scripts/export_display_vs_transaction_mismatch_excel.js --financialYear 2026 --untilMonth 5
 *
 * Output: backend/scripts/Leave_Register_Display_vs_Transaction_Mismatch_FY2026.xlsx
 */

const path = require('path');
const fs = require('fs');
const mongoose = require('mongoose');
const XLSX = require('xlsx');
require('dotenv').config({ path: path.join(__dirname, '../.env') });

require('../departments/model/Designation');
require('../departments/model/Department');
require('../departments/model/Division');

const LeaveRegisterYear = require('../leaves/model/LeaveRegisterYear');
const LeavePolicySettings = require('../settings/model/LeavePolicySettings');
const leaveRegisterService = require('../leaves/services/leaveRegisterService');
const {
  allocateLockedByPriorityForSlot,
  isPayrollPeriodEndedOnOrBeforeAsOf,
} = require('../leaves/services/leaveRegisterYearService');

const TRANSFER_OUT_PREFIX = 'MONTHLY_POOL_TRANSFER_OUT_';
const TRANSFER_IN_PREFIX = 'MONTHLY_POOL_TRANSFER_IN_';
const LEAVE_TYPES = ['CL', 'CCL', 'EL'];

function parseArg(name) {
  const key = String(name).replace(/^--/, '');
  const idx = process.argv.findIndex((a) => a === `--${key}`);
  if (idx >= 0 && process.argv[idx + 1] != null && !String(process.argv[idx + 1]).startsWith('--')) {
    return process.argv[idx + 1];
  }
  return undefined;
}

function roundHalf(v) {
  const n = Number(v) || 0;
  if (n === 0) return 0;
  return Math.round(n * 2) / 2;
}

function roundHalfSigned(v) {
  const n = Number(v) || 0;
  if (n === 0) return 0;
  const sign = n < 0 ? -1 : 1;
  return (sign * Math.round(Math.abs(n) * 2)) / 2;
}

function num(v) {
  if (v == null || v === '' || !Number.isFinite(Number(v))) return '';
  const n = Number(v);
  return Math.abs(n - Math.round(n)) < 0.001 ? Math.round(n) : Math.round(n * 100) / 100;
}

function sortSlots(months) {
  return (months || [])
    .map((slot) => ({
      slot,
      time: new Date(slot?.payPeriodStart || slot?.payPeriodEnd || 0).getTime(),
    }))
    .sort((a, b) => a.time - b.time)
    .map((x) => x.slot);
}

function isTransferTx(tx) {
  const autoType = String(tx?.autoGeneratedType || '');
  return autoType.startsWith(TRANSFER_OUT_PREFIX) || autoType.startsWith(TRANSFER_IN_PREFIX);
}

function isReversalCredit(tx) {
  return (
    String(tx?.transactionType || '').toUpperCase() === 'CREDIT' &&
    String(tx?.reason || '').includes('Leave Application Cancelled/Reversed')
  );
}

function txnStatsForType(slot, leaveType) {
  const lt = String(leaveType).toUpperCase();
  let debitCount = 0;
  let debitSum = 0;
  let reversalSum = 0;
  const debitLines = [];
  for (const tx of slot?.transactions || []) {
    if (String(tx?.leaveType || '').toUpperCase() !== lt) continue;
    if (isTransferTx(tx)) continue;
    const txType = String(tx?.transactionType || '').toUpperCase();
    const days = Math.max(0, Number(tx?.days) || 0);
    if (txType === 'DEBIT' && days > 0) {
      debitCount += 1;
      debitSum += days;
      debitLines.push({
        days,
        reason: String(tx?.reason || '').slice(0, 120),
        applicationId: tx?.applicationId ? String(tx.applicationId) : '',
        status: tx?.status || '',
        transactionType: txType,
        autoGeneratedType: tx?.autoGeneratedType || '',
      });
    }
    if (isReversalCredit(tx)) reversalSum += days;
  }
  const netLedgerUsed = roundHalf(Math.max(0, debitSum - reversalSum));
  return { debitCount, debitSum: roundHalf(debitSum), reversalSum: roundHalf(reversalSum), netLedgerUsed, debitLines };
}

function reconcileUsed(slot, leaveType) {
  const alloc = slot?.poolCarryForwardAllocation;
  if (!alloc?.actualOrLedgerUsed) return null;
  const key = leaveType;
  const v = alloc.actualOrLedgerUsed[key];
  return v != null && Number.isFinite(Number(v)) ? roundHalf(Number(v)) : null;
}

function ignoredStaleSummary(slot, leaveType) {
  const alloc = slot?.poolCarryForwardAllocation;
  const rows = Array.isArray(alloc?.ignoredStaleApplicationDebits) ? alloc.ignoredStaleApplicationDebits : [];
  const filtered = rows.filter((r) => String(r?.leaveType || '').toUpperCase() === leaveType);
  if (!filtered.length) return { count: 0, days: 0, detail: '' };
  const days = roundHalf(filtered.reduce((s, r) => s + (Number(r?.days) || 0), 0));
  const detail = filtered
    .slice(0, 3)
    .map((r) => `${r.status || '?'}:${r.days}d`)
    .join('; ');
  return { count: filtered.length, days, detail };
}

function policyCr(rm, kind) {
  if (!rm) return null;
  if (kind === 'CL') {
    if (rm.policyScheduledCl != null) return roundHalf(Number(rm.policyScheduledCl));
    const ti = Number(rm.cl?.transferIn) || 0;
    if (rm.scheduledCl != null) return roundHalf(Math.max(0, Number(rm.scheduledCl) - ti));
  }
  if (kind === 'CCL') {
    if (rm.policyScheduledCco != null) return roundHalf(Number(rm.policyScheduledCco));
    const ti = Number(rm.ccl?.transferIn) || 0;
    if (rm.scheduledCco != null) return roundHalf(Math.max(0, Number(rm.scheduledCco) - ti));
  }
  if (kind === 'EL') {
    if (rm.policyScheduledEl != null) return roundHalf(Number(rm.policyScheduledEl));
    const ti = Number(rm.el?.transferIn) || 0;
    if (rm.scheduledEl != null) return roundHalf(Math.max(0, Number(rm.scheduledEl) - ti));
  }
  return null;
}

function bucketFor(rm, kind) {
  if (kind === 'CL') return rm?.cl;
  if (kind === 'CCL') return rm?.ccl;
  return rm?.el;
}

function classifyPattern(viewUsed, txnNet) {
  const v = Number(viewUsed) || 0;
  const t = Number(txnNet) || 0;
  if (Math.abs(v - t) < 0.001) return { code: 'MATCH', label: 'No mismatch' };
  if (v > t) return { code: 'A', label: 'Grid Used HIGHER than transaction debits (approved > debits in list)' };
  if (v < t) return { code: 'B', label: 'Transaction debits HIGHER than grid (stale/rejected/duplicate debits in ledger)' };
  return { code: 'C', label: 'Mixed difference' };
}

function buildExplanation(pattern, diff, stale) {
  const parts = [];
  if (pattern.code === 'A') {
    parts.push(
      'REGISTER VIEW: Used counts approved leave for payroll. TRANSACTION LIST: fewer or no matching DEBIT rows in this month.'
    );
  } else if (pattern.code === 'B') {
    parts.push(
      'TRANSACTION LIST: extra DEBIT rows still stored (often rejected/cancelled/duplicate). REGISTER VIEW: reconcile ignores those for Used and Transfer.'
    );
    if (stale.count > 0) {
      parts.push(`Reconcile ignored ${stale.count} stale debit(s) (${stale.days} day(s)): ${stale.detail}.`);
    }
  }
  parts.push(`Difference (View Used − Txn net debits) = ${num(diff)}.`);
  parts.push('Trust REGISTER columns for transfer; clean stale txn lines if popup should match.');
  return parts.join(' ');
}

async function main() {
  const financialYear = String(parseArg('financialYear') || '2026').trim();
  const untilMonth = parseArg('untilMonth') != null ? Number(parseArg('untilMonth')) : 5;
  const auditPath = path.join(__dirname, '_scan_all_transfer_audit.json');
  let targetEmpNos = null;
  if (fs.existsSync(auditPath)) {
    try {
      const audit = JSON.parse(fs.readFileSync(auditPath, 'utf8'));
      targetEmpNos = audit.uniqueEmployeesWithIssues || null;
    } catch {
      targetEmpNos = null;
    }
  }

  await mongoose.connect(process.env.MONGODB_URI);

  const summaryRows = [];
  const txnDetailRows = [];
  const empIndexRows = [];

  let yearDocs = await LeaveRegisterYear.find({ financialYear })
    .select('employeeId empNo employeeName months')
    .lean();

  if (targetEmpNos?.length) {
    const want = new Set(targetEmpNos.map((e) => String(e).trim()));
    yearDocs = yearDocs.filter((d) => want.has(String(d.empNo).trim()));
  }

  const empById = new Map();
  for (const d of yearDocs) {
    empById.set(String(d.employeeId), {
      _id: d.employeeId,
      emp_no: d.empNo,
      employee_name: d.employeeName,
    });
  }

  for (const doc of yearDocs) {
    const emp = empById.get(String(doc.employeeId)) || {
      emp_no: doc.empNo,
      employee_name: doc.employeeName,
    };
    const empNo = emp.emp_no ?? doc.empNo;
    const empName = emp.employee_name ?? doc.employeeName;

    const grouped = await leaveRegisterService.getLeaveRegister(
      { employeeId: doc.employeeId, financialYear },
      null,
      null
    );
    const entry = Array.isArray(grouped) ? grouped[0] : grouped;
    const registerMonths = entry?.registerMonths || [];
    const slots = sortSlots(doc.months);
    const slotByKey = new Map(
      slots.map((s) => [`${Number(s.payrollCycleMonth)}/${Number(s.payrollCycleYear)}`, s])
    );

    let empIssueMonths = 0;

    for (const rm of registerMonths) {
      const m = Number(rm.month);
      const y = Number(rm.year);
      if (m > untilMonth) continue;
      const mk = `${m}/${y}`;
      const slot = slotByKey.get(mk);
      if (!slot?.payPeriodEnd || !isPayrollPeriodEndedOnOrBeforeAsOf(slot.payPeriodEnd, new Date())) {
        continue;
      }

      for (const lt of LEAVE_TYPES) {
        const kind = lt === 'CL' ? 'CL' : lt === 'CCL' ? 'CCL' : 'EL';
        const b = bucketFor(rm, kind);
        if (!b) continue;

        const txn = txnStatsForType(slot, lt);
        const viewUsed = roundHalf(Number(b.used) || 0);
        const viewLocked = roundHalf(Number(b.locked) || 0);
        const viewUsedPlusLock = roundHalf(viewUsed + viewLocked);
        const internalReconcileUsed = reconcileUsed(slot, lt);
        const displayUsed =
          internalReconcileUsed != null ? internalReconcileUsed : viewUsed;
        const diff = roundHalfSigned(displayUsed - txn.netLedgerUsed);

        if (Math.abs(diff) < 0.001) continue;

        const stale = ignoredStaleSummary(slot, lt);
        const pattern = classifyPattern(displayUsed, txn.netLedgerUsed);
        const cr = policyCr(rm, kind);
        const carriedIn = roundHalf(Number(b.transferIn) || 0);
        const transferOut = roundHalf(Number(b.transferOut) || 0);
        const poolCredits =
          kind === 'CL'
            ? roundHalf(Number(slot?.clCredits) || 0)
            : kind === 'CCL'
              ? roundHalf(Number(slot?.compensatoryOffs) || 0)
              : roundHalf(Number(slot?.elCredits) || 0);
        const poolIn = roundHalf(Number(slot?.poolCarryForwardIn?.[kind === 'CL' ? 'cl' : kind === 'CCL' ? 'ccl' : 'el']) || 0);
        const poolOut = roundHalf(Number(slot?.poolCarryForwardOut?.[kind === 'CL' ? 'cl' : kind === 'CCL' ? 'ccl' : 'el']) || 0);
        const bal =
          cr != null
            ? roundHalf((cr || 0) + carriedIn - viewUsedPlusLock - transferOut)
            : '';

        empIssueMonths += 1;

        summaryRows.push({
          'Emp No': empNo,
          'Employee Name': empName,
          'Payroll Month': rm.label || mk,
          'Month Index': m,
          'Year': y,
          'Leave Type': lt,
          'Issue Pattern Code': pattern.code,
          'Issue Pattern (short)': pattern.label,
          'View: Policy Cr': num(cr),
          'View: Carried In': num(carriedIn),
          'View: Used': num(viewUsed),
          'View: Pending Lock': num(viewLocked),
          'View: Used + Lock': num(viewUsedPlusLock),
          'View: Transfer Out': num(transferOut),
          'View: Balance (Cr+in−used−lock−out)': num(bal),
          'Txn: Debit Line Count': txn.debitCount,
          'Txn: Sum All Debits': num(txn.debitSum),
          'Txn: Reversal Credits': num(txn.reversalSum),
          'Txn: Net Used (debits − reversals)': num(txn.netLedgerUsed),
          'Internal: Total Pool Credits': num(poolCredits),
          'Internal: poolCarryForwardIn': num(poolIn),
          'Internal: poolCarryForwardOut': num(poolOut),
          'Internal: Reconcile Used (allocation)': num(internalReconcileUsed),
          'Internal: Stale Debits Ignored Count': stale.count,
          'Internal: Stale Debits Ignored Days': num(stale.days),
          'Internal: Stale Detail': stale.detail,
          'Difference (View Used − Txn Net)': num(diff),
          'What To Trust': 'REGISTER VIEW (Used, Transfer Out, Carried In)',
          'Plain English Explanation': buildExplanation(pattern, diff, stale),
        });

        for (let li = 0; li < txn.debitLines.length; li++) {
          const line = txn.debitLines[li];
          txnDetailRows.push({
            'Emp No': empNo,
            'Employee Name': empName,
            'Payroll Month': rm.label || mk,
            'Leave Type': lt,
            'Line #': li + 1,
            'Txn Days': num(line.days),
            'Txn Type': line.transactionType,
            'Txn Status': line.status,
            'Application Id': line.applicationId,
            'Txn Reason': line.reason,
            'Auto Generated Type': line.autoGeneratedType,
            'Included in Grid Used?':
              'No — grid uses approved/reconcile; may differ from raw debit sum',
          });
        }
      }
    }

    if (empIssueMonths > 0) {
      empIndexRows.push({
        'Emp No': empNo,
        'Employee Name': empName,
        'Mismatch Rows (month×type)': empIssueMonths,
      });
    }
  }

  summaryRows.sort((a, b) =>
    String(a['Emp No']).localeCompare(String(b['Emp No']), undefined, { numeric: true })
  );

  const readme = [
    { Topic: 'Purpose', Detail: 'Employees (~12%) where leave REGISTER grid ≠ TRANSACTION popup debit sum (FY 2026, ended months).' },
    { Topic: 'REGISTER VIEW', Detail: 'What HR sees: Cr, Carried In, Used, Lock, Transfer Out, Bal. Source: leaveRegisterService API (same as UI).' },
    { Topic: 'TRANSACTION POPUP', Detail: 'Sum of all DEBIT lines in that month slot (minus reversal credits). Opening month shows every ledger line.' },
    { Topic: 'INTERNAL MECHANIC', Detail: 'poolCarryForwardIn/Out, pool credits, reconcile actualOrLedgerUsed, ignored stale debits.' },
    { Topic: 'Pattern A', Detail: 'View Used > Txn Net — approved usage counted; debits missing or in different shape.' },
    { Topic: 'Pattern B', Detail: 'Txn Net > View Used — extra debits in ledger (rejected/duplicate); grid ignores for transfer.' },
    { Topic: 'Trust for payroll', Detail: 'Always REGISTER VIEW. Clean txn lines only if you want popup to match.' },
    { Topic: 'Generated', Detail: new Date().toISOString() },
    { Topic: 'Employees in file', Detail: String(empIndexRows.length) },
    { Topic: 'Summary rows', Detail: String(summaryRows.length) },
    { Topic: 'Transaction detail rows', Detail: String(txnDetailRows.length) },
  ];

  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(readme), 'README');
  XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(empIndexRows), 'Employee Index');
  XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(summaryRows), 'Summary (View vs Txn)');
  if (txnDetailRows.length > 0) {
    XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(txnDetailRows), 'Transaction Lines');
  }

  const outName = `Leave_Register_Display_vs_Transaction_Mismatch_FY${financialYear}.xlsx`;
  const outPath = path.join(__dirname, outName);
  XLSX.writeFile(wb, outPath);

  console.log(
    JSON.stringify(
      {
        ok: true,
        outputFile: outPath,
        employees: empIndexRows.length,
        summaryRows: summaryRows.length,
        transactionDetailRows: txnDetailRows.length,
        financialYear,
        untilMonth,
      },
      null,
      2
    )
  );

  await mongoose.disconnect();
}

main().catch(async (err) => {
  console.error(err?.stack || err);
  try {
    await mongoose.disconnect();
  } catch {}
  process.exit(1);
});
