const path = require('path');
const mongoose = require('mongoose');
require('dotenv').config({ path: path.join(__dirname, '../.env') });
require('../departments/model/Designation');
require('../departments/model/Department');
require('../departments/model/Division');
const Employee = require('../employees/model/Employee');
const Leave = require('../leaves/model/Leave');
const LeaveSplit = require('../leaves/model/LeaveSplit');
const LeaveRegisterYear = require('../leaves/model/LeaveRegisterYear');

function fmt(d) {
  if (!d) return null;
  return new Date(d).toISOString().slice(0, 10);
}

async function main() {
  const empNo = process.argv[2] || '06';
  await mongoose.connect(process.env.MONGODB_URI);

  const emp = await Employee.findOne({
    $or: [{ emp_no: String(empNo) }, { emp_no: Number(empNo) }],
  }).lean();
  if (!emp) {
    console.log(JSON.stringify({ error: 'employee_not_found', empNo }, null, 2));
    await mongoose.disconnect();
    return;
  }

  const doc = await LeaveRegisterYear.findOne({
    employeeId: emp._id,
    financialYear: '2026',
  }).lean();
  const slot = (doc?.months || []).find(
    (m) => Number(m.payrollCycleMonth) === 3 && Number(m.payrollCycleYear) === 2026
  );

  const periodStart = slot?.payPeriodStart;
  const periodEnd = slot?.payPeriodEnd;

  const leaves = await Leave.find({
    employeeId: emp._id,
    isActive: { $ne: false },
    fromDate: { $lte: periodEnd },
    toDate: { $gte: periodStart },
  })
    .select(
      '_id leaveType status splitStatus fromDate toDate numberOfDays isHalfDay reason appliedAt approvedAt createdAt updatedAt'
    )
    .sort({ fromDate: 1 })
    .lean();

  const leaveIds = leaves.map((l) => l._id);
  const splits = leaveIds.length
    ? await LeaveSplit.find({ leaveId: { $in: leaveIds }, status: 'approved' })
        .select('leaveId leaveType date numberOfDays isHalfDay status')
        .lean()
    : [];

  const clDebits = (slot?.transactions || []).filter(
    (t) =>
      String(t.leaveType) === 'CL' &&
      String(t.transactionType).toUpperCase() === 'DEBIT' &&
      !String(t.autoGeneratedType || '').includes('TRANSFER')
  );

  const allocation = slot?.poolCarryForwardAllocation || null;

  const approvedClInPeriod = leaves.filter(
    (l) => String(l.leaveType).toUpperCase() === 'CL' && String(l.status).toLowerCase() === 'approved'
  );

  console.log(
    JSON.stringify(
      {
        employee: { empNo: emp.emp_no, name: emp.employee_name },
        marchPayrollMonth: '3/2026',
        payrollPeriod: { start: fmt(periodStart), end: fmt(periodEnd) },
        marchPool: {
          scheduledCl: 1,
          carryIn: Number(slot?.poolCarryForwardIn?.cl) || 0,
          totalPool: Number(slot?.clCredits) || 0,
          transferOut: Number(slot?.poolCarryForwardOut?.cl) || 0,
          usedForTransferCalculation: allocation?.actualOrLedgerUsed?.CL ?? null,
        },
        answer: {
          consumedDays: allocation?.actualOrLedgerUsed?.CL ?? null,
          formula: 'Transfer out = 1 scheduled + 2 carry-in - 1 used = 2',
        },
        approvedClLeavesInMarchPeriod: approvedClInPeriod.map((l) => ({
          leaveId: String(l._id),
          status: l.status,
          days: l.numberOfDays,
          fromDate: fmt(l.fromDate),
          toDate: fmt(l.toDate),
          reason: l.reason || '',
          appliedAt: fmt(l.appliedAt),
          approvedAt: fmt(l.approvedAt),
          splitStatus: l.splitStatus || null,
        })),
        allLeavesOverlappingMarch: leaves.map((l) => ({
          leaveId: String(l._id),
          type: l.leaveType,
          status: l.status,
          days: l.numberOfDays,
          fromDate: fmt(l.fromDate),
          toDate: fmt(l.toDate),
          reason: l.reason || '',
          countsForTransfer: String(l.leaveType).toUpperCase() === 'CL' && String(l.status).toLowerCase() === 'approved',
        })),
        approvedSplitsInMarch: splits.map((s) => ({
          leaveId: String(s.leaveId),
          type: s.leaveType,
          date: fmt(s.date),
          days: s.numberOfDays,
          isHalfDay: !!s.isHalfDay,
        })),
        clDebitsPostedInMarchLedger: clDebits.map((t) => ({
          days: t.days,
          date: fmt(t.startDate || t.at),
          applicationId: t.applicationId ? String(t.applicationId) : null,
          reason: t.reason || '',
          status: t.status,
          linkedLeave: t.applicationId
            ? leaves.find((l) => String(l._id) === String(t.applicationId))
            : null,
        })),
        ignoredStaleDebits: allocation?.ignoredStaleApplicationDebits || [],
      },
      null,
      2
    )
  );

  await mongoose.disconnect();
}

main().catch(async (e) => {
  console.error(e);
  try {
    await mongoose.disconnect();
  } catch {}
  process.exit(1);
});
