/**
 * Inspect one employee's leave-register transactions for a specific payroll month/year.
 * Usage: node scripts/inspect_employee_month_transactions.js 925 5 2026 2026
 * args: <empNo> <payrollMonth> <payrollYear> [financialYear]
 */
const mongoose = require('mongoose');
const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '../.env') });

require('../departments/model/Designation');
require('../departments/model/Department');
require('../departments/model/Division');

const Employee = require('../employees/model/Employee');
const LeaveRegisterYear = require('../leaves/model/LeaveRegisterYear');
const leaveRegisterService = require('../leaves/services/leaveRegisterService');

const empNoArg = process.argv[2] || '925';
const monthArg = Number(process.argv[3] || 5);
const yearArg = Number(process.argv[4] || 2026);
const fyArg = process.argv[5] || '2026';

function txOut(t) {
  return {
    at: t.at || null,
    leaveType: t.leaveType || null,
    transactionType: t.transactionType || null,
    days: Number(t.days) || 0,
    openingBalance: t.openingBalance ?? null,
    closingBalance: t.closingBalance ?? null,
    startDate: t.startDate || null,
    endDate: t.endDate || null,
    reason: t.reason || '',
    status: t.status || null,
    autoGeneratedType: t.autoGeneratedType || null,
  };
}

async function main() {
  if (!process.env.MONGODB_URI) throw new Error('MONGODB_URI missing');
  await mongoose.connect(process.env.MONGODB_URI);

  const emp = await Employee.findOne({
    $or: [{ emp_no: String(empNoArg) }, { emp_no: Number(empNoArg) }],
  })
    .select('_id emp_no employee_name')
    .lean();

  if (!emp) {
    console.log(JSON.stringify({ ok: false, error: 'Employee not found', empNo: empNoArg }, null, 2));
    return;
  }

  const ydoc = await LeaveRegisterYear.findOne({
    employeeId: emp._id,
    financialYear: String(fyArg).trim(),
  }).lean();

  const slot = (ydoc?.months || []).find(
    (m) => Number(m.payrollCycleMonth) === monthArg && Number(m.payrollCycleYear) === yearArg
  );

  const grouped = await leaveRegisterService.getLeaveRegister(
    { employeeId: emp._id, financialYear: String(fyArg).trim() },
    null,
    null
  );
  const row = Array.isArray(grouped) ? grouped[0] : grouped;
  const registerMonth = (row?.registerMonths || []).find(
    (m) => Number(m.month) === monthArg && Number(m.year) === yearArg
  );

  console.log(
    JSON.stringify(
      {
        ok: true,
        employee: {
          id: String(emp._id),
          emp_no: emp.emp_no,
          name: emp.employee_name,
        },
        financialYear: String(fyArg).trim(),
        slot: slot
          ? {
              label: slot.label,
              payrollCycleMonth: slot.payrollCycleMonth,
              payrollCycleYear: slot.payrollCycleYear,
              payPeriodStart: slot.payPeriodStart || null,
              payPeriodEnd: slot.payPeriodEnd || null,
              clCredits: slot.clCredits ?? null,
              compensatoryOffs: slot.compensatoryOffs ?? null,
              elCredits: slot.elCredits ?? null,
              lockedCredits: slot.lockedCredits ?? null,
              poolCarryForwardIn: slot.poolCarryForwardIn || null,
              poolCarryForwardOut: slot.poolCarryForwardOut || null,
              transactionCount: Array.isArray(slot.transactions) ? slot.transactions.length : 0,
              transactions: (slot.transactions || []).map(txOut),
            }
          : null,
        registerMonthView: registerMonth || null,
      },
      null,
      2
    )
  );
}

main()
  .catch((e) => {
    console.error(e);
    process.exitCode = 1;
  })
  .finally(async () => {
    try {
      await mongoose.disconnect();
    } catch (_) {}
  });

