/**
 * Inspect leave register + CCL for one employee (by emp_no).
 * Usage: node scripts/inspect_employee_leave_register_ccl.js 2213
 */
const mongoose = require('mongoose');
const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '../.env') });

require('../departments/model/Designation');
require('../departments/model/Department');
require('../departments/model/Division');

const Employee = require('../employees/model/Employee');
const LeaveRegisterYear = require('../leaves/model/LeaveRegisterYear');
const LeavePolicySettings = require('../settings/model/LeavePolicySettings');
const dateCycleService = require('../leaves/services/dateCycleService');
const leaveRegisterService = require('../leaves/services/leaveRegisterService');

const empNoArg = process.argv[2] || process.env.EMP_NO || '2213';

async function main() {
  const uri = process.env.MONGODB_URI;
  if (!uri) {
    console.error('MONGODB_URI missing');
    process.exit(1);
  }
  await mongoose.connect(uri);

  const emp = await Employee.findOne({
    $or: [{ emp_no: String(empNoArg) }, { emp_no: Number(empNoArg) }],
  })
    .select('_id emp_no employee_name compensatoryOffs casualLeaves paidLeaves is_active doj')
    .lean();

  if (!emp) {
    console.log(JSON.stringify({ ok: false, error: 'Employee not found', empNo: empNoArg }, null, 2));
    await mongoose.disconnect();
    process.exit(0);
  }

  const yearRows = await LeaveRegisterYear.find({ employeeId: emp._id })
    .select('financialYear financialYearStart months')
    .sort({ financialYearStart: -1 })
    .lean();

  const policy = await LeavePolicySettings.getSettings().catch(() => null);
  const today = new Date();
  const periodInfo = await dateCycleService.getPeriodInfo(today);
  const defaultFy = periodInfo?.financialYear?.name || yearRows[0]?.financialYear;

  const out = {
    ok: true,
    employee: {
      _id: String(emp._id),
      emp_no: emp.emp_no,
      employee_name: emp.employee_name,
      is_active: emp.is_active,
      doj: emp.doj,
      /** Profile fields (may differ from register ledger until sync). */
      compensatoryOffs: emp.compensatoryOffs,
      casualLeaves: emp.casualLeaves,
      paidLeaves: emp.paidLeaves,
    },
    leaveRegisterYearsInDb: yearRows.map((y) => ({
      financialYear: y.financialYear,
      financialYearStart: y.financialYearStart,
      monthSlots: (y.months || []).map((m) => ({
        payrollCycleMonth: m.payrollCycleMonth,
        payrollCycleYear: m.payrollCycleYear,
        label: m.label,
        scheduled: m.scheduled
          ? {
              compensatoryOffs: m.scheduled.compensatoryOffs,
              poolCarryForwardIn: m.scheduled.poolCarryForwardIn,
              poolCarryForwardOut: m.scheduled.poolCarryForwardOut,
            }
          : null,
        cclTxns: (m.transactions || [])
          .filter((t) => t.leaveType === 'CCL')
          .map((t) => ({
            transactionType: t.transactionType,
            days: t.days,
            startDate: t.startDate,
            endDate: t.endDate,
            reason: t.reason,
            autoGenerated: t.autoGenerated,
            autoGeneratedType: t.autoGeneratedType,
          })),
      })),
    })),
  };

  if (defaultFy) {
    const grouped = await leaveRegisterService.getLeaveRegister(
      { employeeId: emp._id, financialYear: defaultFy },
      null,
      null
    );
    const row = Array.isArray(grouped) ? grouped[0] : grouped;
    const months = row?.registerMonths || row?.months || [];
    out.apiFinancialYearUsed = defaultFy;
    out.registerSummaryFromService = row
      ? {
          financialYear: row.financialYear || row.yearSnapshot?.financialYear,
          cclBalanceFromRow: row.cclBalance ?? row.balances?.ccl ?? row.compensatoryOffBalance,
          registerMonthsCcl: months.map((m) => ({
            month: m.month ?? m.payrollCycleMonth,
            year: m.year ?? m.payrollCycleYear,
            label: m.label,
            scheduledCco: m.scheduledCco,
            policyScheduledCco: m.policyScheduledCco,
            ccl: m.ccl,
            ledgerCompensatoryOff: m.ledger?.compensatoryOff,
          })),
        }
      : { error: 'getLeaveRegister returned empty' };
  }

  console.log(JSON.stringify(out, null, 2));
  await mongoose.disconnect();
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
