const path = require('path');
const mongoose = require('mongoose');
require('dotenv').config({ path: path.join(__dirname, '../.env') });
require('../departments/model/Designation');
require('../departments/model/Department');
require('../departments/model/Division');
const Employee = require('../employees/model/Employee');
const LeaveRegisterYear = require('../leaves/model/LeaveRegisterYear');

async function inspect(empNo) {
  const emp = await Employee.findOne({
    $or: [{ emp_no: String(empNo) }, { emp_no: Number(empNo) }],
  }).lean();
  const doc = await LeaveRegisterYear.findOne({
    employeeId: emp._id,
    financialYear: '2026',
  }).lean();
  const slots = (doc.months || [])
    .slice()
    .sort((a, b) => new Date(a.payPeriodStart) - new Date(b.payPeriodStart));
  for (const s of slots) {
    const mk = `${s.payrollCycleMonth}/${s.payrollCycleYear}`;
    if (!['3/2026', '4/2026', '5/2026'].includes(mk)) continue;
    const txs = (s.transactions || []).filter((t) =>
      String(t.autoGeneratedType || '').includes('TRANSFER')
    );
    console.log('---', empNo, mk, '---');
    console.log({
      clCredits: s.clCredits,
      ccl: s.compensatoryOffs,
      locked: s.lockedCredits,
      poolIn: s.poolCarryForwardIn,
      poolOut: s.poolCarryForwardOut,
      payEnd: s.payPeriodEnd,
    });
    console.log(
      'transfer txs',
      txs.map((t) => ({
        type: t.autoGeneratedType,
        lt: t.leaveType,
        days: t.days,
      }))
    );
    const debits = (s.transactions || []).filter(
      (t) =>
        String(t.transactionType || '').toUpperCase() === 'DEBIT' &&
        !String(t.autoGeneratedType || '').includes('TRANSFER')
    );
    console.log(
      'non-transfer debits',
      debits.map((t) => ({
        lt: t.leaveType,
        days: t.days,
        reason: (t.reason || '').slice(0, 60),
        status: t.status,
      }))
    );
  }
}

async function main() {
  await mongoose.connect(process.env.MONGODB_URI);
  for (const empNo of process.argv.slice(2).length
    ? process.argv.slice(2)
    : ['06']) {
    await inspect(empNo);
  }
  await mongoose.disconnect();
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
