/**
 * EL credits from LeaveRegisterYear (authoritative ledger) + ELHistory for DEV.
 * Usage: node scripts/listDevElLedgerCredits.js [year=2026] [payrollCycleMonth=3]
 */
require('dotenv').config({ path: require('path').join(__dirname, '../.env') });
const mongoose = require('mongoose');
const Department = require('../departments/model/Department');
const Employee = require('../employees/model/Employee');
const LeaveRegisterYear = require('../leaves/model/LeaveRegisterYear');
const ELHistory = require('../leaves/model/ELHistory');

const YEAR = parseInt(process.argv[2] || '2026', 10);
const CYCLE_MONTH = process.argv[3] ? parseInt(process.argv[3], 10) : null;

function isElAccrualCredit(t) {
  return (
    t &&
    String(t.leaveType).toUpperCase() === 'EL' &&
    String(t.transactionType).toUpperCase() === 'CREDIT' &&
    (String(t.autoGeneratedType || '') === 'EARNED_LEAVE' ||
      (t.reason && String(t.reason).includes('Earned Leave')))
  );
}

async function main() {
  await mongoose.connect(process.env.MONGODB_URI);
  const dept =
    (await Department.findOne({ code: /^DEV$/i }).lean()) ||
    (await Department.findOne({ name: /development/i }).lean());
  if (!dept) {
    console.log(JSON.stringify({ error: 'Department not found' }));
    process.exit(0);
  }
  const emps = await Employee.find({ department_id: dept._id, is_active: true })
    .select('_id emp_no name paidLeaves')
    .sort({ emp_no: 1 })
    .lean();

  const out = [];
  for (const e of emps) {
    const yrs = await LeaveRegisterYear.find({ employeeId: e._id }).lean();
    const ledgerCredits = [];
    for (const y of yrs) {
      for (const m of y.months || []) {
        if (CYCLE_MONTH != null && m.payrollCycleMonth != null && m.payrollCycleMonth !== CYCLE_MONTH) continue;
        if (CYCLE_MONTH != null && m.payrollCycleYear != null && m.payrollCycleYear !== YEAR) continue;
        for (const t of m.transactions || []) {
          if (!isElAccrualCredit(t)) continue;
          ledgerCredits.push({
            financialYear: y.financialYear,
            payrollCycleMonth: m.payrollCycleMonth,
            payrollCycleYear: m.payrollCycleYear,
            days: t.days,
            reason: t.reason,
            at: t.at,
          });
        }
      }
    }
    const histQ = { employeeId: e._id, type: 'CREDIT', year: YEAR };
    if (CYCLE_MONTH != null) histQ.month = CYCLE_MONTH;
    const hist = await ELHistory.find(histQ).sort({ month: 1, createdAt: 1 }).lean();

    out.push({
      emp_no: e.emp_no,
      name: e.name,
      paid_leaves_balance_now: e.paidLeaves,
      el_credited_from_ledger_matching_filter: ledgerCredits.reduce((s, x) => s + (Number(x.days) || 0), 0),
      ledger_rows: ledgerCredits,
      el_history_days_sum: hist.reduce((s, h) => s + (Number(h.days) || 0), 0),
      el_history_rows: hist.map((h) => ({ month: h.month, year: h.year, days: h.days, source: h.source })),
    });
  }

  console.log(
    JSON.stringify(
      {
        department: dept.name,
        filter: CYCLE_MONTH != null ? { payrollCycleYear: YEAR, payrollCycleMonth: CYCLE_MONTH } : { year: YEAR },
        employees: out,
      },
      null,
      2
    )
  );
  await mongoose.disconnect();
}

main().catch((err) => {
  console.error(err);
  mongoose.disconnect().finally(() => process.exit(1));
});
