/**
 * Probe leave register monthly pool transfer chain for specific emp nos.
 * Flags months where posted transfer-out != expected carry, or transfer-in != prior transfer-out.
 *
 * Usage:
 *   node scripts/probe_transfer_mismatch_employees.js --empNos 06,128,71 --financialYear 2026
 */

const path = require('path');
const mongoose = require('mongoose');
require('dotenv').config({ path: path.join(__dirname, '../.env') });

require('../departments/model/Designation');
require('../departments/model/Department');
require('../departments/model/Division');

const Employee = require('../employees/model/Employee');
const LeaveRegisterYear = require('../leaves/model/LeaveRegisterYear');
const LeavePolicySettings = require('../settings/model/LeavePolicySettings');
const {
  allocateLockedByPriorityForSlot,
  isPayrollPeriodEndedOnOrBeforeAsOf,
} = require('../leaves/services/leaveRegisterYearService');

const LEAVE_TYPES = ['CL', 'CCL', 'EL'];
const TRANSFER_OUT_PREFIX = 'MONTHLY_POOL_TRANSFER_OUT_';
const TRANSFER_IN_PREFIX = 'MONTHLY_POOL_TRANSFER_IN_';

function parseArg(name) {
  const key = String(name).replace(/^--/, '');
  const idx = process.argv.findIndex((a) => a === `--${key}`);
  if (idx >= 0 && process.argv[idx + 1] != null && !String(process.argv[idx + 1]).startsWith('--')) {
    return process.argv[idx + 1];
  }
  return undefined;
}

function roundHalf(v) {
  const n = Number(v) || 0;
  if (n <= 0) return 0;
  return Math.round(n * 2) / 2;
}

function sortSlotRefs(months) {
  return (months || [])
    .map((slot, idx) => ({
      idx,
      slot,
      time: new Date(slot?.payPeriodStart || slot?.payPeriodEnd || 0).getTime(),
    }))
    .sort((a, b) => a.time - b.time);
}

function monthKey(slot) {
  return `${Number(slot?.payrollCycleMonth)}/${Number(slot?.payrollCycleYear)}`;
}

function transferAutoType(direction, leaveType) {
  return `${direction === 'out' ? TRANSFER_OUT_PREFIX : TRANSFER_IN_PREFIX}${leaveType}`;
}

function isTransferTx(tx) {
  const autoType = String(tx?.autoGeneratedType || '');
  return autoType.startsWith(TRANSFER_OUT_PREFIX) || autoType.startsWith(TRANSFER_IN_PREFIX);
}

function isReversalCredit(tx) {
  return (
    String(tx?.transactionType || '').toUpperCase() === 'CREDIT' &&
    String(tx?.reason || '').includes('Leave Application Cancelled/Reversed')
  );
}

function sumTransfer(slot, direction, leaveType) {
  const expected = transferAutoType(direction, leaveType);
  return roundHalf(
    (slot?.transactions || [])
      .filter((tx) => String(tx?.autoGeneratedType || '') === expected)
      .reduce((sum, tx) => sum + Math.max(0, Number(tx?.days) || 0), 0)
  );
}

function netUsedDaysForType(slot, leaveType) {
  const lt = String(leaveType || '').toUpperCase();
  let debits = 0;
  let reversalCredits = 0;
  for (const tx of slot?.transactions || []) {
    if (String(tx?.leaveType || '').toUpperCase() !== lt) continue;
    if (isTransferTx(tx)) continue;
    const txType = String(tx?.transactionType || '').toUpperCase();
    const days = Math.max(0, Number(tx?.days) || 0);
    if (txType === 'DEBIT') debits += days;
    if (isReversalCredit(tx)) reversalCredits += days;
  }
  return roundHalf(Math.max(0, debits - reversalCredits));
}

function resolveRollFlags(policy) {
  const capCfg = policy?.monthlyLeaveApplicationCap || {};
  const includeEL = !!capCfg.includeEL;
  const elPaidInPayroll = policy?.earnedLeave?.useAsPaidInPayroll !== false;
  const elInPool = !!policy?.earnedLeave?.enabled && includeEL && !elPaidInPayroll;
  return {
    CL: policy?.carryForward?.casualLeave?.carryMonthlyClCreditToNextPayrollMonth !== false,
    CCL: policy?.carryForward?.compensatoryOff?.carryMonthlyPoolToNextPayrollMonth !== false,
    EL: elInPool && policy?.carryForward?.earnedLeave?.carryMonthlyPoolToNextPayrollMonth !== false,
    elInPool,
  };
}

function computeCarry(slot, rollFlags) {
  const credits = {
    CL: roundHalf(Number(slot?.clCredits) || 0),
    CCL: roundHalf(Number(slot?.compensatoryOffs) || 0),
    EL: rollFlags.elInPool ? roundHalf(Number(slot?.elCredits) || 0) : 0,
  };
  const usedCl = netUsedDaysForType(slot, 'CL');
  const usedCcl = netUsedDaysForType(slot, 'CCL');
  const usedEl = netUsedDaysForType(slot, 'EL');
  const periodEnded =
    slot?.payPeriodEnd && isPayrollPeriodEndedOnOrBeforeAsOf(slot.payPeriodEnd, new Date());
  const slotForLock =
    periodEnded && Number(slot?.monthlyApplyLocked) > 0
      ? { ...slot, monthlyApplyLocked: 0 }
      : slot;
  const locked = allocateLockedByPriorityForSlot(
    slotForLock,
    { cl: credits.CL, ccl: credits.CCL, el: credits.EL },
    { cl: usedCl, ccl: usedCcl, el: usedEl },
    rollFlags.elInPool
  );
  return {
    credits,
    used: { CL: usedCl, CCL: usedCcl, EL: usedEl },
    locked,
    carry: {
      CL: rollFlags.CL ? roundHalf(Math.max(0, credits.CL - usedCl - locked.cl)) : 0,
      CCL: rollFlags.CCL ? roundHalf(Math.max(0, credits.CCL - usedCcl - locked.ccl)) : 0,
      EL: rollFlags.EL ? roundHalf(Math.max(0, credits.EL - usedEl - locked.el)) : 0,
    },
    poolOut: {
      CL: roundHalf(Number(slot?.poolCarryForwardOut?.cl) || 0),
      CCL: roundHalf(Number(slot?.poolCarryForwardOut?.ccl) || 0),
      EL: roundHalf(Number(slot?.poolCarryForwardOut?.el) || 0),
    },
    poolIn: {
      CL: roundHalf(Number(slot?.poolCarryForwardIn?.cl) || 0),
      CCL: roundHalf(Number(slot?.poolCarryForwardIn?.ccl) || 0),
      EL: roundHalf(Number(slot?.poolCarryForwardIn?.el) || 0),
    },
  };
}

function probeDoc(doc, rollFlags) {
  const ordered = sortSlotRefs(doc.months);
  const issues = [];
  const monthSummaries = [];

  for (let i = 0; i < ordered.length; i++) {
    const slot = ordered[i].slot;
    const mk = monthKey(slot);
    const c = computeCarry(slot, rollFlags);
    const postedOut = {
      CL: sumTransfer(slot, 'out', 'CL'),
      CCL: sumTransfer(slot, 'out', 'CCL'),
      EL: sumTransfer(slot, 'out', 'EL'),
    };
    const postedIn = {
      CL: sumTransfer(slot, 'in', 'CL'),
      CCL: sumTransfer(slot, 'in', 'CCL'),
      EL: sumTransfer(slot, 'in', 'EL'),
    };

    const monthIssue = { payroll: mk, problems: [] };

    for (const lt of LEAVE_TYPES) {
      const expectedOut = c.carry[lt];
      const periodEnded =
        slot?.payPeriodEnd && isPayrollPeriodEndedOnOrBeforeAsOf(slot.payPeriodEnd, new Date());
      if (i < ordered.length - 1 && periodEnded && postedOut[lt] !== expectedOut) {
        monthIssue.problems.push({
          type: 'transfer_out_mismatch',
          leaveType: lt,
          posted: postedOut[lt],
          expected: expectedOut,
          credits: c.credits[lt],
          used: c.used[lt],
          locked: c.locked[lt === 'CL' ? 'cl' : lt === 'CCL' ? 'ccl' : 'el'],
          poolOut: c.poolOut[lt],
        });
      }
      if (postedIn[lt] !== c.poolIn[lt]) {
        monthIssue.problems.push({
          type: 'transfer_in_vs_pool_in_mismatch',
          leaveType: lt,
          postedIn: postedIn[lt],
          poolCarryForwardIn: c.poolIn[lt],
        });
      }
      if (c.poolOut[lt] !== postedOut[lt]) {
        monthIssue.problems.push({
          type: 'pool_out_vs_ledger_out_mismatch',
          leaveType: lt,
          poolOut: c.poolOut[lt],
          ledgerOut: postedOut[lt],
        });
      }
    }

    if (i > 0) {
      const prev = ordered[i - 1].slot;
      const prevMk = monthKey(prev);
      const prevPeriodEnded =
        prev?.payPeriodEnd && isPayrollPeriodEndedOnOrBeforeAsOf(prev.payPeriodEnd, new Date());
      const prevC = computeCarry(prev, rollFlags);
      for (const lt of LEAVE_TYPES) {
        const prevOut = sumTransfer(prev, 'out', lt);
        const curIn = postedIn[lt];
        if (prevPeriodEnded && prevOut !== curIn) {
          monthIssue.problems.push({
            type: 'chain_break',
            leaveType: lt,
            fromMonth: prevMk,
            transferOutFromPrior: prevOut,
            transferInThisMonth: curIn,
            expectedFromPrior: prevC.carry[lt],
          });
        }
        if (prevPeriodEnded && c.poolIn[lt] !== prevC.carry[lt]) {
          monthIssue.problems.push({
            type: 'pool_in_vs_prior_carry_mismatch',
            leaveType: lt,
            fromMonth: prevMk,
            poolIn: c.poolIn[lt],
            priorExpectedCarry: prevC.carry[lt],
          });
        }
      }
    }

    monthSummaries.push({
      payroll: mk,
      credits: c.credits,
      used: c.used,
      carry: c.carry,
      postedOut,
      postedIn,
      poolIn: c.poolIn,
      poolOut: c.poolOut,
      lockedCl: roundHalf(Number(slot?.lockedCredits) || 0),
      problemCount: monthIssue.problems.length,
    });

    if (monthIssue.problems.length > 0) {
      issues.push(monthIssue);
    }
  }

  return {
    empNo: doc.empNo,
    employeeName: doc.employeeName,
    financialYear: doc.financialYear,
    slotCount: ordered.length,
    issueCount: issues.reduce((s, x) => s + x.problems.length, 0),
    monthsWithIssues: issues.length,
    issues,
    monthSummaries,
  };
}

async function main() {
  const empNosArg =
    parseArg('empNos') ||
    '06,128,71,5008,1823,2067,1644,1724,166,2163';
  const financialYear = String(parseArg('financialYear') || '2026').trim();
  const empNos = empNosArg.split(',').map((s) => s.trim()).filter(Boolean);

  if (!process.env.MONGODB_URI) {
    console.error('MONGODB_URI missing');
    process.exit(1);
  }

  await mongoose.connect(process.env.MONGODB_URI);
  const policy = await LeavePolicySettings.getSettings().catch(() => ({}));
  const rollFlags = resolveRollFlags(policy);

  const results = [];
  for (const empNo of empNos) {
    const emp = await Employee.findOne({
      $or: [{ emp_no: String(empNo) }, { emp_no: Number(empNo) }],
    })
      .select('_id emp_no employee_name is_active')
      .lean();

    if (!emp) {
      results.push({ empNo, ok: false, error: 'employee_not_found' });
      continue;
    }

    const doc = await LeaveRegisterYear.findOne({
      employeeId: emp._id,
      financialYear,
    }).lean();

    if (!doc) {
      results.push({
        empNo: emp.emp_no,
        ok: false,
        error: 'leave_register_year_not_found',
        employeeName: emp.employee_name,
        financialYear,
      });
      continue;
    }

    const probe = probeDoc(doc, rollFlags);
    results.push({
      ok: true,
      employeeId: String(emp._id),
      employeeName: emp.employee_name,
      is_active: emp.is_active,
      ...probe,
      needsReconcile: probe.issueCount > 0,
    });
  }

  const summary = {
    financialYear,
    rollFlags,
    scanned: results.length,
    found: results.filter((r) => r.ok).length,
    needsReconcile: results.filter((r) => r.needsReconcile).length,
    clean: results.filter((r) => r.ok && !r.needsReconcile).length,
    notFound: results.filter((r) => !r.ok).length,
  };

  console.log(JSON.stringify({ summary, results }, null, 2));
  await mongoose.disconnect();
}

main().catch(async (err) => {
  console.error(err?.stack || err);
  try {
    await mongoose.disconnect();
  } catch {}
  process.exit(1);
});
