/**
 * Fix LeaveRegisterYear month slots where `compensatoryOffs` was inflated because
 * monthly pool carry (`monthlyPoolCarryForwardService`) already added carried CCL to
 * the next slot, and `leaveRegisterYearLedgerService.addTransaction` also bumped the
 * slot for MONTHLY_POOL_TRANSFER_IN_CCL (pre-fix double count).
 *
 * Safe guard: only adjusts when `poolCarryForwardIn.ccl` is present and >= sum of
 * MONTHLY_POOL_TRANSFER_IN_CCL credit days in that slot (so we do not strip a month
 * that only has transfer-in credits and no carry metadata).
 *
 * Usage (default = dry run; add --apply to persist):
 *   node scripts/reconcile_leave_register_ccl_double_transfer_in.js
 *   node scripts/reconcile_leave_register_ccl_double_transfer_in.js --empNo 2003 --apply
 *   node scripts/reconcile_leave_register_ccl_double_transfer_in.js --financialYear 2026 --apply
 *
 * After writes: CCL balances are recalculated from transactions; monthly apply fields
 * are re-synced for each touched slot.
 */

const path = require('path');
const mongoose = require('mongoose');
require('dotenv').config({ path: path.join(__dirname, '../.env') });

require('../departments/model/Designation');
require('../departments/model/Department');
require('../departments/model/Division');

const Employee = require('../employees/model/Employee');
const LeaveRegisterYear = require('../leaves/model/LeaveRegisterYear');
const leaveRegisterYearLedgerService = require('../leaves/services/leaveRegisterYearLedgerService');
const leaveRegisterYearMonthlyApplyService = require('../leaves/services/leaveRegisterYearMonthlyApplyService');

function roundHalf(x) {
  const n = Number(x) || 0;
  if (n <= 0) return 0;
  return Math.round(n * 2) / 2;
}

function parseArg(name) {
  const key = String(name).replace(/^--/, '');
  const idx = process.argv.findIndex((a) => a === `--${key}`);
  if (idx >= 0 && process.argv[idx + 1] != null && !String(process.argv[idx + 1]).startsWith('--')) {
    return process.argv[idx + 1];
  }
  return undefined;
}

function hasFlag(name) {
  return process.argv.includes(`--${name}`);
}

function sumTransferInCclCreditDays(slot) {
  let s = 0;
  for (const t of slot.transactions || []) {
    if (String(t.leaveType || '').toUpperCase() !== 'CCL') continue;
    if (String(t.transactionType || '').toUpperCase() !== 'CREDIT') continue;
    if (String(t.autoGeneratedType || '') !== 'MONTHLY_POOL_TRANSFER_IN_CCL') continue;
    s += roundHalf(Number(t.days) || 0);
  }
  return roundHalf(s);
}

function sumNonTransferInCclCreditDays(slot) {
  let s = 0;
  for (const t of slot.transactions || []) {
    if (String(t.leaveType || '').toUpperCase() !== 'CCL') continue;
    if (String(t.transactionType || '').toUpperCase() !== 'CREDIT') continue;
    if (String(t.autoGeneratedType || '') === 'MONTHLY_POOL_TRANSFER_IN_CCL') continue;
    s += roundHalf(Number(t.days) || 0);
  }
  return roundHalf(s);
}

/**
 * Minimum pool implied by carry-in + non–transfer-in credits (transfer-in is ledger echo of carry).
 */
function floorMinCclPool(slot) {
  const pin = roundHalf(Number(slot.poolCarryForwardIn?.ccl) || 0);
  const nt = sumNonTransferInCclCreditDays(slot);
  return roundHalf(pin + nt);
}

function proposeReconcileSlot(slot) {
  const ti = sumTransferInCclCreditDays(slot);
  if (ti <= 0) {
    return { changed: false, reason: 'no_transfer_in_ccl' };
  }
  const pinCcl = roundHalf(Number(slot.poolCarryForwardIn?.ccl) || 0);
  if (pinCcl < ti) {
    return { changed: false, reason: 'carry_metadata_lt_transfer_in_skip' };
  }
  const floorMin = floorMinCclPool(slot);
  const cur = roundHalf(Number(slot.compensatoryOffs) || 0);
  const threshold = roundHalf(floorMin + ti);
  if (cur < threshold) {
    return { changed: false, reason: 'pool_not_inflated_vs_floor_plus_ti' };
  }
  const next = roundHalf(cur - ti);
  if (next < floorMin) {
    return { changed: false, reason: 'would_go_below_floor', cur, floorMin, ti };
  }
  if (next === cur) {
    return { changed: false, reason: 'no_op' };
  }
  return { changed: true, before: cur, after: next, floorMin, ti, pinCcl };
}

async function main() {
  const dryRun = !hasFlag('apply');
  const empNoFilter = parseArg('empNo');
  const fyFilter = parseArg('financialYear');

  const uri = process.env.MONGODB_URI;
  if (!uri) {
    console.error('MONGODB_URI missing');
    process.exit(1);
  }

  await mongoose.connect(uri);

  const query = {};
  if (fyFilter) query.financialYear = String(fyFilter).trim();
  if (empNoFilter) {
    const emp = await Employee.findOne({
      $or: [{ emp_no: String(empNoFilter) }, { emp_no: Number(empNoFilter) }],
    })
      .select('_id')
      .lean();
    if (!emp) {
      console.log(JSON.stringify({ ok: false, error: 'Employee not found', empNo: empNoFilter }, null, 2));
      await mongoose.disconnect();
      process.exit(0);
    }
    query.employeeId = emp._id;
  }

  const cursor = LeaveRegisterYear.find(query).cursor();
  const summary = {
    dryRun,
    docsScanned: 0,
    docsModified: 0,
    slotsFixed: 0,
    details: [],
    errors: [],
  };

  for await (const doc of cursor) {
    summary.docsScanned++;
    let docChanged = false;
    const slotResults = [];

    if (!Array.isArray(doc.months)) continue;

    for (let i = 0; i < doc.months.length; i++) {
      const slot = doc.months[i];
      const r = proposeReconcileSlot(slot);
      if (r.changed) {
        slotResults.push({
          payrollCycleMonth: slot.payrollCycleMonth,
          payrollCycleYear: slot.payrollCycleYear,
          label: slot.label,
          payPeriodStart: slot.payPeriodStart || null,
          payPeriodEnd: slot.payPeriodEnd || null,
          before: r.before,
          after: r.after,
          floorMin: r.floorMin,
          ti: r.ti,
          pinCcl: r.pinCcl,
        });
        docChanged = true;
        summary.slotsFixed++;
        if (!dryRun) {
          slot.compensatoryOffs = r.after;
        }
      }
    }

    if (docChanged) {
      summary.details.push({
        employeeId: String(doc.employeeId),
        empNo: doc.empNo,
        financialYear: doc.financialYear,
        slots: slotResults,
      });
      if (!dryRun) {
        try {
          doc.markModified('months');
          await doc.save();
          await leaveRegisterYearLedgerService.recalculateRegisterBalances(doc.employeeId, 'CCL', null);
          for (const s of slotResults) {
            const anchor = s.payPeriodStart || s.payPeriodEnd;
            if (anchor) {
              await leaveRegisterYearMonthlyApplyService.syncStoredMonthApplyFieldsForEmployeeDate(
                doc.employeeId,
                new Date(anchor)
              );
            }
          }
          summary.docsModified++;
        } catch (e) {
          summary.errors.push({
            empNo: doc.empNo,
            financialYear: doc.financialYear,
            error: e.message || String(e),
          });
        }
      }
    }
  }

  console.log(
    JSON.stringify(
      {
        ok: true,
        message: dryRun
          ? 'Dry run only. Re-run with --apply to write fixes.'
          : 'Applied fixes where possible.',
        ...summary,
      },
      null,
      2
    )
  );

  await mongoose.disconnect();
}

main().catch(async (e) => {
  console.error(e?.message || e);
  try {
    await mongoose.disconnect();
  } catch {}
  process.exit(1);
});
