/**
 * Reconcile LeaveRegisterYear monthly pool transfer rows for CL/CCL/EL.
 *
 * What it does:
 *   1) Strips MONTHLY_POOL_TRANSFER_IN_* and MONTHLY_POOL_TRANSFER_OUT_* rows
 *      for all payroll edges from the FY opening through the target month opening.
 *   2) Reverts slot pool bumps recorded in poolCarryForwardIn.
 *   3) Recomputes actual unused pool from current slot credits minus actual used
 *      debits (net of old reversal credits) and locked CL.
 *   4) Reposts matching transfer-out/transfer-in rows and refreshes balances.
 *
 * Usage:
 *   node scripts/reconcile_leave_register_monthly_transfers.js --empNo 61 --untilMonth 5 --untilYear 2026
 *   node scripts/reconcile_leave_register_monthly_transfers.js --empNo 61 --untilMonth 5 --untilYear 2026 --apply
 *
 * Defaults:
 *   --financialYear <name> defaults to the FY containing today's date
 *   dry-run unless --apply is provided
 */

const path = require('path');
const mongoose = require('mongoose');
require('dotenv').config({ path: path.join(__dirname, '../.env') });

require('../departments/model/Designation');
require('../departments/model/Department');
require('../departments/model/Division');

const Employee = require('../employees/model/Employee');
const LeaveRegisterYear = require('../leaves/model/LeaveRegisterYear');
const LeavePolicySettings = require('../settings/model/LeavePolicySettings');
const dateCycleService = require('../leaves/services/dateCycleService');
const leaveRegisterService = require('../leaves/services/leaveRegisterService');
const leaveRegisterYearLedgerService = require('../leaves/services/leaveRegisterYearLedgerService');
const leaveRegisterYearMonthlyApplyService = require('../leaves/services/leaveRegisterYearMonthlyApplyService');

const LEAVE_TYPES = ['CL', 'CCL', 'EL'];
const TRANSFER_OUT_PREFIX = 'MONTHLY_POOL_TRANSFER_OUT_';
const TRANSFER_IN_PREFIX = 'MONTHLY_POOL_TRANSFER_IN_';

function parseArg(name) {
  const key = String(name).replace(/^--/, '');
  const idx = process.argv.findIndex((a) => a === `--${key}`);
  if (idx >= 0 && process.argv[idx + 1] != null && !String(process.argv[idx + 1]).startsWith('--')) {
    return process.argv[idx + 1];
  }
  return undefined;
}

function hasFlag(name) {
  return process.argv.includes(`--${name}`);
}

function round2(v) {
  const n = Number(v) || 0;
  return Math.round(n * 100) / 100;
}

function roundHalf(v) {
  const n = Number(v) || 0;
  if (n <= 0) return 0;
  return Math.round(n * 2) / 2;
}

function redactMongoUri(uri) {
  const s = String(uri || '');
  return s.replace(/^(mongodb(?:\+srv)?:\/\/)([^/@]+)@/, '$1***@');
}

function sortSlotRefs(months) {
  return (months || [])
    .map((slot, idx) => ({
      idx,
      slot,
      time: new Date(slot?.payPeriodStart || slot?.payPeriodEnd || 0).getTime(),
    }))
    .sort((a, b) => a.time - b.time);
}

function transferAutoType(direction, leaveType) {
  return `${direction === 'out' ? TRANSFER_OUT_PREFIX : TRANSFER_IN_PREFIX}${leaveType}`;
}

function isTransferTx(tx) {
  const autoType = String(tx?.autoGeneratedType || '');
  return autoType.startsWith(TRANSFER_OUT_PREFIX) || autoType.startsWith(TRANSFER_IN_PREFIX);
}

function isTransferTxForDirection(tx, direction) {
  const autoType = String(tx?.autoGeneratedType || '');
  if (direction === 'out') return autoType.startsWith(TRANSFER_OUT_PREFIX);
  if (direction === 'in') return autoType.startsWith(TRANSFER_IN_PREFIX);
  return isTransferTx(tx);
}

function isReversalCredit(tx) {
  return (
    String(tx?.transactionType || '').toUpperCase() === 'CREDIT' &&
    String(tx?.reason || '').includes('Leave Application Cancelled/Reversed')
  );
}

function sumTransfer(slot, direction, leaveType) {
  const expected = transferAutoType(direction, leaveType);
  return roundHalf(
    (slot?.transactions || [])
      .filter((tx) => String(tx?.autoGeneratedType || '') === expected)
      .reduce((sum, tx) => sum + Math.max(0, Number(tx?.days) || 0), 0)
  );
}

function netUsedDaysForType(slot, leaveType) {
  const lt = String(leaveType || '').toUpperCase();
  let debits = 0;
  let reversalCredits = 0;
  for (const tx of slot?.transactions || []) {
    if (String(tx?.leaveType || '').toUpperCase() !== lt) continue;
    if (isTransferTx(tx)) continue;
    const txType = String(tx?.transactionType || '').toUpperCase();
    const days = Math.max(0, Number(tx?.days) || 0);
    if (txType === 'DEBIT') debits += days;
    if (isReversalCredit(tx)) reversalCredits += days;
  }
  return roundHalf(Math.max(0, debits - reversalCredits));
}

function resolveRollFlags(policy) {
  const capCfg = policy?.monthlyLeaveApplicationCap || {};
  const includeEL = !!capCfg.includeEL;
  const elPaidInPayroll = policy?.earnedLeave?.useAsPaidInPayroll !== false;
  const elInPool = !!policy?.earnedLeave?.enabled && includeEL && !elPaidInPayroll;
  return {
    CL: policy?.carryForward?.casualLeave?.carryMonthlyClCreditToNextPayrollMonth !== false,
    CCL: policy?.carryForward?.compensatoryOff?.carryMonthlyPoolToNextPayrollMonth !== false,
    EL: elInPool && policy?.carryForward?.earnedLeave?.carryMonthlyPoolToNextPayrollMonth !== false,
    elInPool,
  };
}

function slotCredits(slot, rollFlags) {
  return {
    CL: roundHalf(Number(slot?.clCredits) || 0),
    CCL: roundHalf(Number(slot?.compensatoryOffs) || 0),
    EL: rollFlags.elInPool ? roundHalf(Number(slot?.elCredits) || 0) : 0,
  };
}

function computeCarry(slot, rollFlags) {
  const credits = slotCredits(slot, rollFlags);
  const used = {
    CL: netUsedDaysForType(slot, 'CL'),
    CCL: netUsedDaysForType(slot, 'CCL'),
    EL: netUsedDaysForType(slot, 'EL'),
  };
  const clLocked = roundHalf(Number(slot?.lockedCredits) || 0);
  return {
    credits,
    used: { ...used, clLocked },
    carry: {
      CL: rollFlags.CL ? roundHalf(Math.max(0, credits.CL - used.CL)) : 0,
      CCL: rollFlags.CCL ? roundHalf(Math.max(0, credits.CCL - used.CCL)) : 0,
      EL: rollFlags.EL ? roundHalf(Math.max(0, credits.EL - used.EL)) : 0,
    },
  };
}

function monthKey(slot) {
  return `${Number(slot?.payrollCycleMonth)}/${Number(slot?.payrollCycleYear)}`;
}

function snapshotMonths(doc, untilIdx, rollFlags) {
  const ordered = sortSlotRefs(doc.months);
  const maxIdx = Math.min(untilIdx, ordered.length - 1);
  return ordered.slice(0, maxIdx + 1).map(({ slot }) => {
    const c = computeCarry(slot, rollFlags);
    return {
      label: slot.label || monthKey(slot),
      payroll: monthKey(slot),
      credits: {
        cl: round2(Number(slot.clCredits) || 0),
        ccl: round2(Number(slot.compensatoryOffs) || 0),
        el: round2(Number(slot.elCredits) || 0),
        lockedCl: round2(Number(slot.lockedCredits) || 0),
      },
      actualUsed: {
        cl: c.used.CL,
        ccl: c.used.CCL,
        el: c.used.EL,
      },
      transferLedger: {
        in: {
          cl: sumTransfer(slot, 'in', 'CL'),
          ccl: sumTransfer(slot, 'in', 'CCL'),
          el: sumTransfer(slot, 'in', 'EL'),
        },
        out: {
          cl: sumTransfer(slot, 'out', 'CL'),
          ccl: sumTransfer(slot, 'out', 'CCL'),
          el: sumTransfer(slot, 'out', 'EL'),
        },
      },
      poolCarryForwardIn: {
        cl: round2(Number(slot.poolCarryForwardIn?.cl) || 0),
        ccl: round2(Number(slot.poolCarryForwardIn?.ccl) || 0),
        el: round2(Number(slot.poolCarryForwardIn?.el) || 0),
      },
      poolCarryForwardOut: {
        cl: round2(Number(slot.poolCarryForwardOut?.cl) || 0),
        ccl: round2(Number(slot.poolCarryForwardOut?.ccl) || 0),
        el: round2(Number(slot.poolCarryForwardOut?.el) || 0),
      },
      wouldCarryFromThisSlot: {
        cl: c.carry.CL,
        ccl: c.carry.CCL,
        el: c.carry.EL,
      },
      balancesFromLastTx: lastClosingBalances(slot),
    };
  });
}

function lastClosingBalances(slot) {
  const out = { cl: null, ccl: null, el: null };
  for (const tx of slot?.transactions || []) {
    const lt = String(tx?.leaveType || '').toUpperCase();
    const v = Number(tx?.closingBalance);
    if (!Number.isFinite(v)) continue;
    if (lt === 'CL') out.cl = v;
    if (lt === 'CCL') out.ccl = v;
    if (lt === 'EL') out.el = v;
  }
  return out;
}

function findTargetIndex(ordered, untilMonth, untilYear) {
  return ordered.findIndex(
    ({ slot }) =>
      Number(slot.payrollCycleMonth) === Number(untilMonth) &&
      Number(slot.payrollCycleYear) === Number(untilYear)
  );
}

function stripTransfersThroughTarget(doc, targetIdx) {
  const ordered = sortSlotRefs(doc.months);
  const removed = [];
  const revertedCarryIn = [];

  for (let p = 0; p <= targetIdx; p++) {
    const slot = ordered[p]?.slot;
    if (!slot) continue;

    const pin = slot.poolCarryForwardIn || {};
    const dCl = roundHalf(Number(pin.cl) || 0);
    const dCcl = roundHalf(Number(pin.ccl) || 0);
    const dEl = roundHalf(Number(pin.el) || 0);
    if (dCl || dCcl || dEl) {
      slot.clCredits = roundHalf(Math.max(0, (Number(slot.clCredits) || 0) - dCl));
      slot.compensatoryOffs = roundHalf(Math.max(0, (Number(slot.compensatoryOffs) || 0) - dCcl));
      slot.elCredits = roundHalf(Math.max(0, (Number(slot.elCredits) || 0) - dEl));
      revertedCarryIn.push({ slot: monthKey(slot), cl: dCl, ccl: dCcl, el: dEl });
    }

    const before = Array.isArray(slot.transactions) ? slot.transactions.length : 0;
    slot.transactions = (slot.transactions || []).filter((tx) => !isTransferTx(tx));
    const after = slot.transactions.length;
    const removedCount = before - after;
    if (removedCount > 0) removed.push({ slot: monthKey(slot), removedCount });

    slot.poolCarryForwardIn = { cl: 0, ccl: 0, el: 0 };
    slot.poolCarryForwardOut = { cl: 0, ccl: 0, el: 0 };
    slot.poolCarryForwardFromLabel = '';
    slot.poolCarryForwardOutAt = null;
    slot.poolCarryForwardAllocation = undefined;
  }

  return { removed, revertedCarryIn };
}

function pushTransferTx(slot, leaveType, txType, days, autoGeneratedType, date, reason) {
  const d = roundHalf(days);
  if (d <= 0) return;
  if (!Array.isArray(slot.transactions)) slot.transactions = [];
  slot.transactions.push({
    at: new Date(),
    leaveType,
    transactionType: txType,
    days: d,
    openingBalance: 0,
    closingBalance: 0,
    startDate: date,
    endDate: date,
    reason,
    status: 'APPROVED',
    autoGenerated: true,
    autoGeneratedType,
  });
}

function rebuildTransfersThroughTarget(doc, targetIdx, rollFlags) {
  const ordered = sortSlotRefs(doc.months);
  const edges = [];

  for (let p = 0; p < targetIdx; p++) {
    const cur = ordered[p]?.slot;
    const next = ordered[p + 1]?.slot;
    if (!cur || !next) continue;

    const c = computeCarry(cur, rollFlags);
    const carry = c.carry;
    const hasCarry = LEAVE_TYPES.some((lt) => carry[lt] > 0);
    const lockedCreditsReleasedToTransferOut = roundHalf(Number(cur.lockedCredits) || 0);
    if (!hasCarry) {
      if (lockedCreditsReleasedToTransferOut > 0) {
        cur.poolCarryForwardAllocation = {
          source: 'reconcile_leave_register_monthly_transfers',
          credits: c.credits,
          actualUsed: c.used,
          lockedCreditsReleasedToTransferOut,
          carryPosted: { cl: 0, ccl: 0, el: 0 },
          rollFlags,
        };
        cur.lockedCredits = 0;
      }
      edges.push({
        from: monthKey(cur),
        to: monthKey(next),
        credits: c.credits,
        actualUsed: c.used,
        carry,
        posted: false,
      });
      continue;
    }

    cur.poolCarryForwardOut = {
      cl: carry.CL,
      ccl: carry.CCL,
      el: carry.EL,
    };
    cur.poolCarryForwardOutAt = new Date();
    cur.poolCarryForwardAllocation = {
      source: 'reconcile_leave_register_monthly_transfers',
      credits: c.credits,
      actualUsed: c.used,
      lockedCreditsReleasedToTransferOut,
      carryPosted: {
        cl: carry.CL,
        ccl: carry.CCL,
        el: carry.EL,
      },
      rollFlags,
    };
    cur.lockedCredits = 0;

    next.clCredits = roundHalf((Number(next.clCredits) || 0) + carry.CL);
    next.compensatoryOffs = roundHalf((Number(next.compensatoryOffs) || 0) + carry.CCL);
    next.elCredits = roundHalf((Number(next.elCredits) || 0) + carry.EL);
    next.poolCarryForwardIn = {
      cl: carry.CL,
      ccl: carry.CCL,
      el: carry.EL,
    };
    next.poolCarryForwardFromLabel = cur.label || monthKey(cur);

    const outAt = cur.payPeriodEnd ? new Date(cur.payPeriodEnd) : new Date(cur.payPeriodStart || new Date());
    const inAt = next.payPeriodStart ? new Date(next.payPeriodStart) : new Date(next.payPeriodEnd || outAt);
    const fromLabel = monthKey(cur);
    const toLabel = monthKey(next);

    for (const lt of LEAVE_TYPES) {
      if (carry[lt] <= 0) continue;
      pushTransferTx(
        cur,
        lt,
        'DEBIT',
        carry[lt],
        transferAutoType('out', lt),
        outAt,
        `Reconciled transfer out unused monthly pool ${lt} from payroll ${fromLabel} to ${toLabel}.`
      );
      pushTransferTx(
        next,
        lt,
        'CREDIT',
        carry[lt],
        transferAutoType('in', lt),
        inAt,
        `Reconciled transfer in unused monthly pool ${lt} from payroll ${fromLabel} to ${toLabel}.`
      );
    }

    edges.push({
      from: fromLabel,
      to: toLabel,
      credits: c.credits,
      actualUsed: c.used,
      carry,
      posted: true,
    });
  }

  return edges;
}

async function getRegisterServiceSummary(employeeId, financialYear) {
  const grouped = await leaveRegisterService.getLeaveRegister({ employeeId, financialYear }, null, null);
  const row = Array.isArray(grouped) ? grouped[0] : grouped;
  return (row?.registerMonths || []).map((m) => ({
    payroll: `${m.month}/${m.year}`,
    label: m.label,
    cl: {
      credited: m.cl?.credited,
      used: m.cl?.used,
      transferIn: m.cl?.transferIn,
      transferOut: m.cl?.transferOut,
    },
    ccl: {
      credited: m.ccl?.credited,
      used: m.ccl?.used,
      transferIn: m.ccl?.transferIn,
      transferOut: m.ccl?.transferOut,
    },
    el: {
      credited: m.el?.credited,
      used: m.el?.used,
      transferIn: m.el?.transferIn,
      transferOut: m.el?.transferOut,
    },
    scheduled: {
      cl: m.scheduledCl,
      ccl: m.scheduledCco,
      el: m.scheduledEl,
    },
  }));
}

async function syncTouchedSlots(employeeId, doc, targetIdx) {
  const ordered = sortSlotRefs(doc.months);
  const anchors = [];
  for (let p = 0; p <= targetIdx; p++) {
    const slot = ordered[p]?.slot;
    const anchor = slot?.payPeriodStart || slot?.payPeriodEnd;
    if (anchor) anchors.push(anchor);
  }
  for (const anchor of anchors) {
    await leaveRegisterYearMonthlyApplyService.syncStoredMonthApplyFieldsForEmployeeDate(employeeId, anchor);
  }
}

async function reconcileOneDoc({ doc, emp, targetIdx, rollFlags, apply }) {
  const before = snapshotMonths(doc, targetIdx, rollFlags);
  const workingDoc = await LeaveRegisterYear.findById(doc._id);
  const strip = stripTransfersThroughTarget(workingDoc, targetIdx);
  const rebuiltEdges = rebuildTransfersThroughTarget(workingDoc, targetIdx, rollFlags);
  const afterPreview = snapshotMonths(workingDoc, targetIdx, rollFlags);
  const changed =
    strip.removed.length > 0 ||
    strip.revertedCarryIn.length > 0 ||
    rebuiltEdges.some((edge) => edge.posted);

  let after = afterPreview;
  if (apply) {
    workingDoc.markModified('months');
    await workingDoc.save();
    for (const lt of LEAVE_TYPES) {
      await leaveRegisterYearLedgerService.recalculateRegisterBalances(doc.employeeId, lt, null);
    }
    await syncTouchedSlots(doc.employeeId, workingDoc, targetIdx);
    const fresh = await LeaveRegisterYear.findById(workingDoc._id);
    after = snapshotMonths(fresh, targetIdx, rollFlags);
  }

  const pickPayroll = (rows, payroll) => rows.find((row) => row.payroll === payroll) || null;
  const aprilBefore = pickPayroll(before, '4/2026');
  const aprilAfter = pickPayroll(after, '4/2026');
  const mayBefore = pickPayroll(before, '5/2026');
  const mayAfter = pickPayroll(after, '5/2026');

  return {
    ok: true,
    employeeId: String(doc.employeeId),
    empNo: doc.empNo || emp?.emp_no,
    employeeName: doc.employeeName || emp?.employee_name || '',
    changed,
    removedTransferRows: strip.removed.reduce((sum, row) => sum + row.removedCount, 0),
    rebuiltEdges: rebuiltEdges.filter((edge) => edge.posted).length,
    april: {
      lockedCl: `${aprilBefore?.credits?.lockedCl ?? 0} -> ${aprilAfter?.credits?.lockedCl ?? 0}`,
      clTransferIn: `${aprilBefore?.transferLedger?.in?.cl ?? 0} -> ${aprilAfter?.transferLedger?.in?.cl ?? 0}`,
      clTransferOut: `${aprilBefore?.transferLedger?.out?.cl ?? 0} -> ${aprilAfter?.transferLedger?.out?.cl ?? 0}`,
      actualUsed: {
        cl: aprilAfter?.actualUsed?.cl ?? 0,
        ccl: aprilAfter?.actualUsed?.ccl ?? 0,
        el: aprilAfter?.actualUsed?.el ?? 0,
      },
    },
    mayOpening: {
      clCredits: `${mayBefore?.credits?.cl ?? 0} -> ${mayAfter?.credits?.cl ?? 0}`,
      clTransferIn: `${mayBefore?.transferLedger?.in?.cl ?? 0} -> ${mayAfter?.transferLedger?.in?.cl ?? 0}`,
      cclTransferIn: `${mayBefore?.transferLedger?.in?.ccl ?? 0} -> ${mayAfter?.transferLedger?.in?.ccl ?? 0}`,
      elTransferIn: `${mayBefore?.transferLedger?.in?.el ?? 0} -> ${mayAfter?.transferLedger?.in?.el ?? 0}`,
    },
  };
}

async function main() {
  const all = hasFlag('all');
  const verbose = hasFlag('verbose');
  const empNo = parseArg('empNo');
  const untilMonth = Number(parseArg('untilMonth') || parseArg('month') || '5');
  const untilYear = Number(parseArg('untilYear') || parseArg('year') || '2026');
  const financialYearArg = parseArg('financialYear');
  const apply = hasFlag('apply');

  if (!empNo && !all) {
    console.error('Missing --empNo or --all');
    process.exit(1);
  }
  if (!Number.isFinite(untilMonth) || untilMonth < 1 || untilMonth > 12 || !Number.isFinite(untilYear)) {
    console.error('Invalid --untilMonth / --untilYear');
    process.exit(1);
  }
  if (!process.env.MONGODB_URI) {
    console.error('MONGODB_URI missing');
    process.exit(1);
  }

  await mongoose.connect(process.env.MONGODB_URI);

  const fyName = financialYearArg
    ? String(financialYearArg).trim()
    : (await dateCycleService.getFinancialYearForDate(new Date(untilYear, untilMonth - 1, 1))).name;
  const policy = await LeavePolicySettings.getSettings().catch(() => ({}));
  const rollFlags = resolveRollFlags(policy);

  if (all) {
    const query = {
      financialYear: fyName,
      months: {
        $elemMatch: {
          payrollCycleMonth: untilMonth,
          payrollCycleYear: untilYear,
        },
      },
    };
    const docs = await LeaveRegisterYear.find(query).sort({ empNo: 1 });
    const employeeIds = docs.map((doc) => doc.employeeId);
    const employees = await Employee.find({ _id: { $in: employeeIds } })
      .select('_id emp_no employee_name casualLeaves paidLeaves compensatoryOffs is_active')
      .lean();
    const empById = new Map(employees.map((row) => [String(row._id), row]));

    const summary = {
      ok: true,
      dryRun: !apply,
      message: apply
        ? 'Applied monthly transfer reconciliation for all matching employees.'
        : 'Dry run only. Re-run with --apply to persist this reconciliation for all matching employees.',
      database: redactMongoUri(process.env.MONGODB_URI),
      financialYear: fyName,
      targetOpening: { month: untilMonth, year: untilYear },
      rollFlags,
      scanned: docs.length,
      applied: 0,
      failed: 0,
      totalRemovedTransferRows: 0,
      totalRebuiltEdges: 0,
      aprilLockedClearedEmployees: 0,
      aprilTransferOutChangedEmployees: 0,
      mayTransferInChangedEmployees: 0,
      unchangedImportantRows: 0,
      rows: [],
      errors: [],
    };

    for (const doc of docs) {
      try {
        const ordered = sortSlotRefs(doc.months);
        const targetIdx = findTargetIndex(ordered, untilMonth, untilYear);
        if (targetIdx < 0) {
          summary.failed++;
          summary.errors.push({ empNo: doc.empNo, error: 'target_slot_not_found' });
          continue;
        }
        const row = await reconcileOneDoc({
          doc,
          emp: empById.get(String(doc.employeeId)),
          targetIdx,
          rollFlags,
          apply,
        });
        summary.applied++;
        summary.totalRemovedTransferRows += row.removedTransferRows;
        summary.totalRebuiltEdges += row.rebuiltEdges;
        if (!String(row.april.lockedCl || '').startsWith('0 -> 0')) {
          summary.aprilLockedClearedEmployees++;
        }
        if (row.april.clTransferOut && row.april.clTransferOut.split(' -> ')[0] !== row.april.clTransferOut.split(' -> ')[1]) {
          summary.aprilTransferOutChangedEmployees++;
        }
        if (row.mayOpening.clTransferIn && row.mayOpening.clTransferIn.split(' -> ')[0] !== row.mayOpening.clTransferIn.split(' -> ')[1]) {
          summary.mayTransferInChangedEmployees++;
        }
        const importantChanged =
          !String(row.april.lockedCl || '').startsWith('0 -> 0') ||
          (row.april.clTransferOut && row.april.clTransferOut.split(' -> ')[0] !== row.april.clTransferOut.split(' -> ')[1]) ||
          (row.mayOpening.clTransferIn && row.mayOpening.clTransferIn.split(' -> ')[0] !== row.mayOpening.clTransferIn.split(' -> ')[1]);
        if (verbose || importantChanged) {
          summary.rows.push(row);
        } else {
          summary.unchangedImportantRows++;
        }
      } catch (error) {
        summary.failed++;
        summary.errors.push({
          empNo: doc.empNo,
          employeeId: String(doc.employeeId),
          error: error?.message || String(error),
        });
      }
    }

    console.log(JSON.stringify(summary, null, 2));
    await mongoose.disconnect();
    return;
  }

  const emp = await Employee.findOne({
    $or: [{ emp_no: String(empNo) }, { emp_no: Number(empNo) }],
  })
    .select('_id emp_no employee_name casualLeaves paidLeaves compensatoryOffs is_active')
    .lean();

  if (!emp) {
    console.log(JSON.stringify({ ok: false, error: 'Employee not found', empNo }, null, 2));
    await mongoose.disconnect();
    return;
  }

  const beforeDoc = await LeaveRegisterYear.findOne({ employeeId: emp._id, financialYear: fyName });
  if (!beforeDoc) {
    console.log(
      JSON.stringify(
        {
          ok: false,
          error: 'LeaveRegisterYear not found',
          employee: { emp_no: emp.emp_no, employee_name: emp.employee_name },
          financialYear: fyName,
        },
        null,
        2
      )
    );
    await mongoose.disconnect();
    return;
  }

  const ordered = sortSlotRefs(beforeDoc.months);
  const targetIdx = findTargetIndex(ordered, untilMonth, untilYear);
  if (targetIdx < 0) {
    console.log(
      JSON.stringify(
        {
          ok: false,
          error: 'Target month slot not found',
          target: { untilMonth, untilYear, financialYear: fyName },
          slots: ordered.map(({ slot }) => monthKey(slot)),
        },
        null,
        2
      )
    );
    await mongoose.disconnect();
    return;
  }

  const before = snapshotMonths(beforeDoc, targetIdx, rollFlags);
  const beforeService = await getRegisterServiceSummary(emp._id, fyName);

  const workingDoc = await LeaveRegisterYear.findById(beforeDoc._id);
  const strip = stripTransfersThroughTarget(workingDoc, targetIdx);
  const rebuiltEdges = rebuildTransfersThroughTarget(workingDoc, targetIdx, rollFlags);

  let after = snapshotMonths(workingDoc, targetIdx, rollFlags);
  let afterService = null;
  const changed =
    strip.removed.length > 0 ||
    strip.revertedCarryIn.length > 0 ||
    rebuiltEdges.some((e) => e.posted);

  if (apply) {
    workingDoc.markModified('months');
    await workingDoc.save();
    for (const lt of LEAVE_TYPES) {
      await leaveRegisterYearLedgerService.recalculateRegisterBalances(emp._id, lt, null);
    }
    await syncTouchedSlots(emp._id, workingDoc, targetIdx);
    const fresh = await LeaveRegisterYear.findById(workingDoc._id);
    after = snapshotMonths(fresh, targetIdx, rollFlags);
    afterService = await getRegisterServiceSummary(emp._id, fyName);
  }

  const result = {
    ok: true,
    dryRun: !apply,
    message: apply
      ? 'Applied monthly transfer reconciliation.'
      : 'Dry run only. Re-run with --apply to persist this reconciliation.',
    database: redactMongoUri(process.env.MONGODB_URI),
    employee: {
      _id: String(emp._id),
      emp_no: emp.emp_no,
      employee_name: emp.employee_name,
      is_active: emp.is_active,
      employeeBalancesBeforeRun: {
        casualLeaves: emp.casualLeaves,
        compensatoryOffs: emp.compensatoryOffs,
        paidLeaves: emp.paidLeaves,
      },
    },
    financialYear: fyName,
    targetOpening: { month: untilMonth, year: untilYear },
    rollFlags,
    changed,
    strip,
    rebuiltEdges,
    before,
    after,
    registerServiceBefore: beforeService.filter((m) => {
      const [pm, py] = String(m.payroll || '').split('/').map(Number);
      const idx = ordered.findIndex(
        ({ slot }) => Number(slot.payrollCycleMonth) === pm && Number(slot.payrollCycleYear) === py
      );
      return idx >= 0 && idx <= targetIdx;
    }),
    registerServiceAfter: afterService
      ? afterService.filter((m) => {
          const [pm, py] = String(m.payroll || '').split('/').map(Number);
          const idx = ordered.findIndex(
            ({ slot }) => Number(slot.payrollCycleMonth) === pm && Number(slot.payrollCycleYear) === py
          );
          return idx >= 0 && idx <= targetIdx;
        })
      : null,
  };

  console.log(JSON.stringify(result, null, 2));
  await mongoose.disconnect();
}

main().catch(async (error) => {
  console.error(error?.stack || error?.message || error);
  try {
    await mongoose.disconnect();
  } catch {}
  process.exit(1);
});
