/**
 * CL leave register reconciliation (scheduled credits + approved-app debits + transfers).
 *
 * Scope: FY opening payroll slot → current system pay period (or --untilMonth/--untilYear).
 *
 * Phases per employee:
 *   1) Reset CL on touched slots — keep MONTHLY_CL_SCHEDULE credits only; strip other CL tx/aggregates.
 *   2) Post CL DEBIT rows from approved Leave applications overlapping the reconciled window.
 *   3) Rebuild monthly pool transfers (CL/CCL/EL carry chain) through the target pay period.
 *   4) Recalculate CL balances + sync monthly-apply cached fields.
 *
 * Does NOT modify Leave applications.
 *
 * Usage:
 *   node scripts/reconcile_cl_register_from_approved_leaves.js --empNo 2202
 *   node scripts/reconcile_cl_register_from_approved_leaves.js --all --apply
 *
 * Options:
 *   --apply              Persist changes (default: dry run)
 *   --all                All employees with a register year row for the FY
 *   --empNo <no>         Single employee
 *   --financialYear      FY name (default: FY for today)
 *   --untilMonth/--untilYear  Target pay period (default: current system pay period)
 *   --skip-reset         Skip phase 1 (register already cleaned to scheduled-only)
 *   --limit N
 *   --fy 2026          Alias for --financialYear
 *
 * Outputs (when run completes):
 *   scripts/_reconcile_all_cl_results.json
 *   scripts/_reconcile_all_cl_employees.json
 *   scripts/_reconcile_all_cl_employees.csv
 */
const path = require('path');
const fs = require('fs');
const mongoose = require('mongoose');
require('dotenv').config({ path: path.join(__dirname, '../.env') });

require('../departments/model/Designation');
require('../departments/model/Department');
require('../departments/model/Division');

const Employee = require('../employees/model/Employee');
const Leave = require('../leaves/model/Leave');
const LeaveRegisterYear = require('../leaves/model/LeaveRegisterYear');
const dateCycleService = require('../leaves/services/dateCycleService');
const leaveRegisterYearLedgerService = require('../leaves/services/leaveRegisterYearLedgerService');
const leaveRegisterYearMonthlyApplyService = require('../leaves/services/leaveRegisterYearMonthlyApplyService');
const { reconcileEmployeeFromDate } = require('../leaves/services/monthlyTransferReconciliationService');

function parseArg(name) {
  const key = String(name).replace(/^--/, '');
  const idx = process.argv.findIndex((a) => a === `--${key}`);
  if (idx >= 0 && process.argv[idx + 1] != null && !String(process.argv[idx + 1]).startsWith('--')) {
    return process.argv[idx + 1];
  }
  return undefined;
}

function hasFlag(name) {
  return process.argv.includes(`--${name}`);
}

function round2(v) {
  const n = Number(v) || 0;
  return Math.round(n * 100) / 100;
}

function isScheduledClTx(tx) {
  return (
    String(tx?.leaveType || '').toUpperCase() === 'CL' &&
    String(tx?.transactionType || '').toUpperCase() === 'CREDIT' &&
    String(tx?.autoGeneratedType || '') === 'MONTHLY_CL_SCHEDULE'
  );
}

function sumScheduledCl(slot) {
  let total = 0;
  for (const tx of slot?.transactions || []) {
    if (!isScheduledClTx(tx)) continue;
    total += Math.max(0, Number(tx.days) || 0);
  }
  return round2(total);
}

function sortSlotRefs(months) {
  return (months || [])
    .map((slot, idx) => ({
      idx,
      slot,
      time: new Date(slot?.payPeriodStart || slot?.payPeriodEnd || 0).getTime(),
    }))
    .sort((a, b) => a.time - b.time);
}

function findTargetIndex(ordered, untilMonth, untilYear) {
  return ordered.findIndex(
    ({ slot }) =>
      Number(slot?.payrollCycleMonth) === Number(untilMonth) &&
      Number(slot?.payrollCycleYear) === Number(untilYear)
  );
}

function clearSlotClAggregates(slot) {
  slot.poolCarryForwardIn = { ...(slot.poolCarryForwardIn || {}), cl: 0 };
  slot.poolCarryForwardOut = { ...(slot.poolCarryForwardOut || {}), cl: 0 };
  slot.poolCarryForwardOutAt = null;
  slot.poolCarryForwardFromLabel = '';
  if (slot.poolCarryForwardAllocation && typeof slot.poolCarryForwardAllocation === 'object') {
    slot.poolCarryForwardAllocation = null;
  }
  slot.lockedCredits = 0;
  slot.monthlyApplyCeiling = 0;
  slot.monthlyApplyConsumed = 0;
  slot.monthlyApplyLocked = 0;
  slot.monthlyApplyApproved = 0;
  slot.monthlyApplySyncedAt = new Date();
}

function resetClThroughTarget(doc, targetIdx) {
  const ordered = sortSlotRefs(doc.months);
  let clTxRemoved = 0;
  let slotsTouched = 0;

  for (let p = 0; p <= targetIdx; p++) {
    const slot = ordered[p]?.slot;
    if (!slot) continue;
    let slotChanged = false;

    if (Array.isArray(slot.transactions) && slot.transactions.length > 0) {
      const before = slot.transactions.length;
      slot.transactions = slot.transactions.filter((tx) => {
        const lt = String(tx?.leaveType || '').toUpperCase();
        if (lt !== 'CL') return true;
        return isScheduledClTx(tx);
      });
      const removed = before - slot.transactions.length;
      if (removed > 0) {
        clTxRemoved += removed;
        slotChanged = true;
      }
    }

    clearSlotClAggregates(slot);
    const scheduled = sumScheduledCl(slot);
    if (round2(Number(slot.clCredits) || 0) !== scheduled) {
      slot.clCredits = scheduled;
      slotChanged = true;
    }
    if (slotChanged) slotsTouched++;
  }

  const scheduledTotal = round2(
    ordered.slice(0, targetIdx + 1).reduce((acc, { slot }) => acc + (Number(slot?.clCredits) || 0), 0)
  );
  doc.yearlyPolicyClScheduledTotal = scheduledTotal;
  doc.yearlyClCreditDaysPosted = scheduledTotal;

  return { clTxRemoved, slotsTouched };
}

function hasClDebitForApplication(doc, applicationId) {
  const appId = String(applicationId);
  for (const slot of doc.months || []) {
    for (const tx of slot.transactions || []) {
      if (String(tx?.applicationId || '') !== appId) continue;
      if (String(tx?.leaveType || '').toUpperCase() !== 'CL') continue;
      if (String(tx?.transactionType || '').toUpperCase() === 'DEBIT') return true;
    }
  }
  return false;
}

async function loadApprovedClLeaves(employeeId, windowStart, windowEnd) {
  return Leave.find({
    employeeId,
    leaveType: /^CL$/i,
    status: 'approved',
    isActive: { $ne: false },
    fromDate: { $lte: windowEnd },
    toDate: { $gte: windowStart },
  })
    .sort({ fromDate: 1, appliedAt: 1, createdAt: 1 })
    .lean();
}

async function postClDebitFromLeave(leave, employee) {
  const transactionData = {
    employeeId: leave.employeeId,
    empNo: employee.emp_no,
    employeeName: employee.employee_name || 'N/A',
    designation: employee.designation_id?.name || employee.designation || 'N/A',
    department: employee.department_id?.name || employee.department || 'N/A',
    divisionId: employee.division_id,
    departmentId: employee.department_id,
    dateOfJoining: employee.doj,
    employmentStatus: employee.is_active ? 'active' : 'inactive',
    leaveType: 'CL',
    transactionType: 'DEBIT',
    startDate: leave.fromDate,
    endDate: leave.toDate,
    days: leave.numberOfDays,
    applicationId: leave._id,
    applicationDate: leave.appliedAt || leave.createdAt,
    approvalDate: leave.updatedAt,
    status: 'APPROVED',
    reason: leave.purpose || 'CL leave',
  };
  return leaveRegisterYearLedgerService.addTransaction(transactionData);
}

async function reconcileOneEmployee({
  doc,
  employee,
  targetIdx,
  ordered,
  apply,
  skipReset,
  untilMonth,
  untilYear,
  financialYear,
}) {
  const targetSlot = ordered[targetIdx]?.slot;
  const firstSlot = ordered[0]?.slot;
  if (!targetSlot || !firstSlot) {
    return { ok: false, skipped: true, reason: 'missing_slots' };
  }

  const windowStart = new Date(firstSlot.payPeriodStart || firstSlot.payPeriodEnd);
  const windowEnd = new Date(targetSlot.payPeriodEnd || targetSlot.payPeriodStart);

  const workingDoc = apply ? await LeaveRegisterYear.findById(doc._id) : doc;
  if (!workingDoc) return { ok: false, skipped: true, reason: 'doc_not_found' };

  let resetStats = { clTxRemoved: 0, slotsTouched: 0 };
  if (!skipReset) {
    resetStats = resetClThroughTarget(workingDoc, targetIdx);
  }

  const approvedLeaves = await loadApprovedClLeaves(employee._id, windowStart, windowEnd);
  const debitsToPost = [];
  const debitsSkipped = [];

  for (const leave of approvedLeaves) {
    if (hasClDebitForApplication(workingDoc, leave._id)) {
      debitsSkipped.push(String(leave._id));
      continue;
    }
    debitsToPost.push(leave);
  }

  let debitsPosted = 0;
  if (apply) {
    if (!skipReset || resetStats.clTxRemoved > 0 || resetStats.slotsTouched > 0) {
      workingDoc.markModified('months');
      workingDoc.markModified('yearlyPolicyClScheduledTotal');
      workingDoc.markModified('yearlyClCreditDaysPosted');
      await workingDoc.save();
    }

    for (const leave of debitsToPost) {
      await postClDebitFromLeave(leave, employee);
      debitsPosted++;
    }

    await reconcileEmployeeFromDate({
      employeeId: employee._id,
      fromDate: windowStart,
      untilMonth,
      untilYear,
      financialYear,
      apply: true,
    });

    await leaveRegisterYearLedgerService.recalculateRegisterBalances(employee._id, 'CL', windowStart);

    for (let p = 0; p <= targetIdx; p++) {
      const anchor = ordered[p]?.slot?.payPeriodStart || ordered[p]?.slot?.payPeriodEnd;
      if (anchor) {
        await leaveRegisterYearMonthlyApplyService.syncStoredMonthApplyFieldsForEmployeeDate(
          employee._id,
          anchor
        );
      }
    }
  }

  return {
    ok: true,
    empNo: doc.empNo || employee.emp_no,
    employeeName: doc.employeeName || employee.employee_name,
    targetPayroll: `${untilMonth}/${untilYear}`,
    window: {
      from: windowStart.toISOString(),
      to: windowEnd.toISOString(),
    },
    reset: resetStats,
    approvedLeavesFound: approvedLeaves.length,
    debitsToPost: debitsToPost.length,
    debitsPosted,
    debitsSkippedExisting: debitsSkipped.length,
  };
}

async function main() {
  const apply = hasFlag('apply');
  const all = hasFlag('all');
  const skipReset = hasFlag('skip-reset');
  const empNo = parseArg('empNo');
  const limit = Number(parseArg('limit') || 0);

  if (!all && !empNo) {
    console.error('Provide --empNo <no> or --all');
    process.exit(1);
  }
  if (!process.env.MONGODB_URI) {
    console.error('MONGODB_URI missing');
    process.exit(1);
  }

  await mongoose.connect(process.env.MONGODB_URI);

  console.log(
    `[reconcile_all_cl] mode=${apply ? 'APPLY' : 'DRY-RUN'} phases: 1)reset/cleanup CL slots 2)post approved CL debits 3)rebuild transfers 4)recalc`
  );

  const todayPeriod = await dateCycleService.getPeriodInfo(new Date());
  const untilMonth = Number(parseArg('untilMonth') || parseArg('month') || todayPeriod.payrollCycle.month);
  const untilYear = Number(parseArg('untilYear') || parseArg('year') || todayPeriod.payrollCycle.year);
  const fyArg = parseArg('fy');
  const financialYear =
    parseArg('financialYear') ||
    fyArg ||
    (await dateCycleService.getFinancialYearForDate(new Date())).name;

  const summary = {
    ok: true,
    dryRun: !apply,
    script: 'reconcile_cl_register_from_approved_leaves',
    financialYear,
    currentSystemPayPeriod: {
      month: todayPeriod.payrollCycle.month,
      year: todayPeriod.payrollCycle.year,
      start: todayPeriod.payrollCycle.startDate,
      end: todayPeriod.payrollCycle.endDate,
    },
    reconcileThrough: { month: untilMonth, year: untilYear },
    skipReset,
    scanned: 0,
    processed: 0,
    skipped: 0,
    failed: 0,
    totalDebitsToPost: 0,
    totalDebitsPosted: 0,
    rows: [],
    errors: [],
  };

  let docs = [];
  if (empNo) {
    const emp = await Employee.findOne({
      $or: [{ emp_no: String(empNo) }, { emp_no: Number(empNo) }],
    }).lean();
    if (!emp) {
      console.log(JSON.stringify({ ok: false, error: 'Employee not found', empNo }, null, 2));
      await mongoose.disconnect();
      return;
    }
    const doc = await LeaveRegisterYear.findOne({ employeeId: emp._id, financialYear });
    if (!doc) {
      console.log(JSON.stringify({ ok: false, error: 'LeaveRegisterYear not found', empNo, financialYear }, null, 2));
      await mongoose.disconnect();
      return;
    }
    docs = [doc];
  } else {
    docs = await LeaveRegisterYear.find({ financialYear }).sort({ empNo: 1 });
  }

  if (limit > 0) docs = docs.slice(0, limit);
  summary.scanned = docs.length;

  const employeeIds = docs.map((d) => d.employeeId);
  const employees = await Employee.find({ _id: { $in: employeeIds } })
    .populate('designation_id', 'name')
    .populate('department_id', 'name')
    .lean();
  const empById = new Map(employees.map((e) => [String(e._id), e]));

  let n = 0;
  for (const doc of docs) {
    n += 1;
    const employee = empById.get(String(doc.employeeId));
    if (!employee) {
      summary.skipped++;
      summary.errors.push({ empNo: doc.empNo, error: 'employee_not_found' });
      continue;
    }

    const ordered = sortSlotRefs(doc.months);
    const targetIdx = findTargetIndex(ordered, untilMonth, untilYear);
    if (targetIdx < 0) {
      summary.skipped++;
      summary.errors.push({
        empNo: doc.empNo,
        error: 'target_pay_period_not_in_register',
        target: `${untilMonth}/${untilYear}`,
      });
      continue;
    }

    try {
      if (n % 50 === 0 || n === docs.length) {
        console.log(
          `[progress] ${n}/${docs.length} processed=${summary.processed} failed=${summary.failed} dryRun=${!apply}`
        );
      }
      const row = await reconcileOneEmployee({
        doc,
        employee,
        targetIdx,
        ordered,
        apply,
        skipReset,
        untilMonth,
        untilYear,
        financialYear,
      });
      summary.processed++;
      summary.totalDebitsToPost += row.debitsToPost || 0;
      summary.totalDebitsPosted += row.debitsPosted || 0;
      summary.rows.push(row);
    } catch (error) {
      summary.failed++;
      summary.errors.push({
        empNo: doc.empNo,
        error: error?.message || String(error),
      });
    }
  }

  summary.message = apply
    ? 'Applied CL register reconciliation (reset + approved debits + transfers).'
    : 'Dry run. Re-run with --apply to persist.';

  const scriptDir = path.join(__dirname);
  const resultsPath = path.join(scriptDir, '_reconcile_all_cl_results.json');
  const employeesJsonPath = path.join(scriptDir, '_reconcile_all_cl_employees.json');
  const employeesCsvPath = path.join(scriptDir, '_reconcile_all_cl_employees.csv');

  fs.writeFileSync(resultsPath, JSON.stringify(summary, null, 2));
  fs.writeFileSync(employeesJsonPath, JSON.stringify(summary.rows, null, 2));
  fs.writeFileSync(
    employeesCsvPath,
    [
      [
        'empNo',
        'employeeName',
        'targetPayroll',
        'clTxRemoved',
        'slotsTouched',
        'approvedLeavesFound',
        'debitsToPost',
        'debitsPosted',
        'debitsSkippedExisting',
        'status',
      ].join(','),
      ...summary.rows.map((r) =>
        [
          r.empNo,
          `"${String(r.employeeName || '').replace(/"/g, '""')}"`,
          r.targetPayroll,
          r.reset?.clTxRemoved ?? '',
          r.reset?.slotsTouched ?? '',
          r.approvedLeavesFound ?? '',
          r.debitsToPost ?? '',
          r.debitsPosted ?? '',
          r.debitsSkippedExisting ?? '',
          r.ok ? 'ok' : 'skipped',
        ].join(',')
      ),
      ...summary.errors.map((e) =>
        [
          e.empNo,
          '',
          e.target || '',
          '',
          '',
          '',
          '',
          '',
          '',
          `error:${e.error}`,
        ].join(',')
      ),
    ].join('\n')
  );

  console.log(JSON.stringify({ ...summary, rows: `[${summary.rows.length} rows]` }, null, 2));
  console.log('Summary JSON:', resultsPath);
  console.log('Per-employee JSON:', employeesJsonPath);
  console.log('Per-employee CSV:', employeesCsvPath);

  await mongoose.disconnect();
  process.exit(summary.failed > 0 ? 1 : 0);
}

main().catch(async (error) => {
  console.error(error?.stack || error?.message || error);
  try {
    await mongoose.disconnect();
  } catch {}
  process.exit(1);
});
