/**
 * Reconcile LeaveRegisterYear monthly pool transfers up to a target month opening.
 *
 * Scope:
 *   - Real ledger: leave_register_years.months[].transactions.
 *   - Transfer rows: MONTHLY_POOL_TRANSFER_OUT_* and MONTHLY_POOL_TRANSFER_IN_*.
 *   - Transferable monthly pool types: CL, CCL, EL.
 *
 * What it does:
 *   1) Captures before snapshot for each payroll slot up to the target opening.
 *   2) Removes existing transfer-in / transfer-out rows through the target slot.
 *   3) Reverts poolCarryForwardIn bumps from the receiving slots.
 *   4) Recomputes actual used by month from approved Leave / LeaveSplit rows and
 *      ledger debits, ignoring stale application debits whose Leave is now not approved.
 *   5) Rebuilds transfer-out and transfer-in rows sequentially until the target opening.
 *   6) Rechains CL/CCL/EL balances and refreshes monthly apply cache when --apply is used.
 *
 * Usage:
 *   node scripts/reconcile_leave_register_all_transfers_to_opening.js --empNo 61 --untilMonth 5 --untilYear 2026
 *   node scripts/reconcile_leave_register_all_transfers_to_opening.js --empNo 61 --untilMonth 5 --untilYear 2026 --apply
 */

const path = require('path');
const mongoose = require('mongoose');
require('dotenv').config({ path: path.join(__dirname, '../.env') });

require('../departments/model/Designation');
require('../departments/model/Department');
require('../departments/model/Division');

const Employee = require('../employees/model/Employee');
const Leave = require('../leaves/model/Leave');
const LeaveSplit = require('../leaves/model/LeaveSplit');
const LeaveRegisterYear = require('../leaves/model/LeaveRegisterYear');
const LeavePolicySettings = require('../settings/model/LeavePolicySettings');
const dateCycleService = require('../leaves/services/dateCycleService');
const leaveRegisterService = require('../leaves/services/leaveRegisterService');
const leaveRegisterYearLedgerService = require('../leaves/services/leaveRegisterYearLedgerService');
const leaveRegisterYearMonthlyApplyService = require('../leaves/services/leaveRegisterYearMonthlyApplyService');

const LEAVE_TYPES = ['CL', 'CCL', 'EL'];
const TRANSFER_OUT_PREFIX = 'MONTHLY_POOL_TRANSFER_OUT_';
const TRANSFER_IN_PREFIX = 'MONTHLY_POOL_TRANSFER_IN_';

function parseArg(name) {
  const key = String(name).replace(/^--/, '');
  const idx = process.argv.findIndex((a) => a === `--${key}`);
  if (idx >= 0 && process.argv[idx + 1] != null && !String(process.argv[idx + 1]).startsWith('--')) {
    return process.argv[idx + 1];
  }
  return undefined;
}

function hasFlag(name) {
  return process.argv.includes(`--${name}`);
}

function round2(value) {
  const n = Number(value) || 0;
  return Math.round(n * 100) / 100;
}

function roundHalf(value) {
  const n = Number(value) || 0;
  if (n <= 0) return 0;
  return Math.round(n * 2) / 2;
}

function redactMongoUri(uri) {
  return String(uri || '').replace(/^(mongodb(?:\+srv)?:\/\/)([^/@]+)@/, '$1***@');
}

function sortSlotRefs(months) {
  return (months || [])
    .map((slot, idx) => ({
      idx,
      slot,
      time: new Date(slot?.payPeriodStart || slot?.payPeriodEnd || 0).getTime(),
    }))
    .sort((a, b) => a.time - b.time);
}

function monthKey(slot) {
  return `${Number(slot?.payrollCycleMonth)}/${Number(slot?.payrollCycleYear)}`;
}

function findTargetIndex(ordered, untilMonth, untilYear) {
  return ordered.findIndex(
    ({ slot }) =>
      Number(slot?.payrollCycleMonth) === Number(untilMonth) &&
      Number(slot?.payrollCycleYear) === Number(untilYear)
  );
}

function transferAutoType(direction, leaveType) {
  return `${direction === 'out' ? TRANSFER_OUT_PREFIX : TRANSFER_IN_PREFIX}${leaveType}`;
}

function isTransferTx(tx) {
  const autoType = String(tx?.autoGeneratedType || '');
  return autoType.startsWith(TRANSFER_OUT_PREFIX) || autoType.startsWith(TRANSFER_IN_PREFIX);
}

function isReversalCredit(tx) {
  return (
    String(tx?.transactionType || '').toUpperCase() === 'CREDIT' &&
    String(tx?.reason || '').includes('Leave Application Cancelled/Reversed')
  );
}

function sumTransfer(slot, direction, leaveType) {
  const expected = transferAutoType(direction, leaveType);
  return roundHalf(
    (slot?.transactions || [])
      .filter((tx) => String(tx?.autoGeneratedType || '') === expected)
      .reduce((sum, tx) => sum + Math.max(0, Number(tx?.days) || 0), 0)
  );
}

function resolveRollFlags(policy) {
  const capCfg = policy?.monthlyLeaveApplicationCap || {};
  const includeEL = !!capCfg.includeEL;
  const elPaidInPayroll = policy?.earnedLeave?.useAsPaidInPayroll !== false;
  const elInPool = !!policy?.earnedLeave?.enabled && includeEL && !elPaidInPayroll;
  return {
    CL: policy?.carryForward?.casualLeave?.carryMonthlyClCreditToNextPayrollMonth !== false,
    CCL: policy?.carryForward?.compensatoryOff?.carryMonthlyPoolToNextPayrollMonth !== false,
    EL: elInPool && policy?.carryForward?.earnedLeave?.carryMonthlyPoolToNextPayrollMonth !== false,
    elInPool,
  };
}

function slotCredits(slot, rollFlags) {
  return {
    CL: roundHalf(Number(slot?.clCredits) || 0),
    CCL: roundHalf(Number(slot?.compensatoryOffs) || 0),
    EL: rollFlags.elInPool ? roundHalf(Number(slot?.elCredits) || 0) : 0,
  };
}

function sumCreditDays(doc, { leaveType, autoGeneratedType, excludeAutoPrefix = [] }) {
  let total = 0;
  const lt = String(leaveType || '').toUpperCase();
  for (const slot of doc?.months || []) {
    for (const tx of slot?.transactions || []) {
      if (String(tx?.leaveType || '').toUpperCase() !== lt) continue;
      if (String(tx?.transactionType || '').toUpperCase() !== 'CREDIT') continue;
      const autoType = String(tx?.autoGeneratedType || '');
      if (autoGeneratedType && autoType !== autoGeneratedType) continue;
      if (excludeAutoPrefix.some((prefix) => autoType.startsWith(prefix))) continue;
      if (isReversalCredit(tx)) continue;
      total += Math.max(0, Number(tx?.days) || 0);
    }
  }
  return round2(total);
}

function snapshotYearAggregates(doc) {
  const scheduledCl = sumCreditDays(doc, {
    leaveType: 'CL',
    autoGeneratedType: 'MONTHLY_CL_SCHEDULE',
  });
  const cclCreditDays = sumCreditDays(doc, {
    leaveType: 'CCL',
    excludeAutoPrefix: [TRANSFER_IN_PREFIX],
  });
  return {
    stored: {
      yearlyPolicyClScheduledTotal: round2(Number(doc?.yearlyPolicyClScheduledTotal) || 0),
      yearlyClCreditDaysPosted: round2(Number(doc?.yearlyClCreditDaysPosted) || 0),
      yearlyCclCreditDaysPosted: round2(Number(doc?.yearlyCclCreditDaysPosted) || 0),
      casualBalance: round2(Number(doc?.casualBalance) || 0),
      compensatoryOffBalance: round2(Number(doc?.compensatoryOffBalance) || 0),
      earnedLeaveBalance: round2(Number(doc?.earnedLeaveBalance) || 0),
    },
    recomputed: {
      yearlyPolicyClScheduledTotal: scheduledCl,
      yearlyClCreditDaysPosted: scheduledCl,
      yearlyCclCreditDaysPosted: cclCreditDays,
    },
  };
}

function reconcileYearAggregates(doc) {
  const before = snapshotYearAggregates(doc);
  doc.yearlyPolicyClScheduledTotal = before.recomputed.yearlyPolicyClScheduledTotal;
  doc.yearlyClCreditDaysPosted = before.recomputed.yearlyClCreditDaysPosted;
  doc.yearlyCclCreditDaysPosted = before.recomputed.yearlyCclCreditDaysPosted;
  doc.markModified('yearlyPolicyClScheduledTotal');
  doc.markModified('yearlyClCreditDaysPosted');
  doc.markModified('yearlyCclCreditDaysPosted');
  return {
    before: before.stored,
    after: {
      ...before.stored,
      ...before.recomputed,
    },
  };
}

function activeLedgerUsedForType(slot, leaveType, leaveStatusById) {
  const lt = String(leaveType || '').toUpperCase();
  let debits = 0;
  let reversalCredits = 0;
  const ignoredStaleApplicationDebits = [];

  for (const tx of slot?.transactions || []) {
    if (String(tx?.leaveType || '').toUpperCase() !== lt) continue;
    if (isTransferTx(tx)) continue;

    const txType = String(tx?.transactionType || '').toUpperCase();
    const days = Math.max(0, Number(tx?.days) || 0);
    if (txType === 'DEBIT') {
      const appId = tx?.applicationId ? String(tx.applicationId) : null;
      const appStatus = appId ? leaveStatusById.get(appId) : null;
      if (appId && appStatus && appStatus !== 'approved') {
        ignoredStaleApplicationDebits.push({ applicationId: appId, status: appStatus, days });
        continue;
      }
      debits += days;
    }
    if (isReversalCredit(tx)) reversalCredits += days;
  }

  return {
    used: roundHalf(Math.max(0, debits - reversalCredits)),
    ignoredStaleApplicationDebits,
  };
}

function overlapDaysInclusive(aStart, aEnd, bStart, bEnd) {
  const day = 24 * 60 * 60 * 1000;
  const utcDay = (d) => {
    const x = new Date(d);
    return Date.UTC(x.getUTCFullYear(), x.getUTCMonth(), x.getUTCDate());
  };
  const start = Math.max(utcDay(aStart), utcDay(bStart));
  const end = Math.min(utcDay(aEnd), utcDay(bEnd));
  if (end < start) return 0;
  return Math.floor((end - start) / day) + 1;
}

function normalizedLeaveDays(leave, overlapDays) {
  const totalSpan = overlapDaysInclusive(leave.fromDate, leave.toDate, leave.fromDate, leave.toDate);
  const totalDays = Number(leave.numberOfDays) || 0;
  if (totalDays <= 0 || totalSpan <= 0 || overlapDays <= 0) return 0;
  return roundHalf((totalDays * overlapDays) / totalSpan);
}

async function buildActualApprovedUsage(employeeId, ordered, targetIdx) {
  const first = ordered[0]?.slot;
  const last = ordered[targetIdx]?.slot;
  const rangeStart = first?.payPeriodStart || first?.payPeriodEnd;
  const rangeEnd = last?.payPeriodEnd || last?.payPeriodStart;
  const bySlotPayroll = new Map();
  const leaveStatusById = new Map();

  for (let p = 0; p <= targetIdx; p++) {
    const slot = ordered[p].slot;
    bySlotPayroll.set(monthKey(slot), { CL: 0, CCL: 0, EL: 0 });
  }

  const leaves = await Leave.find({
    employeeId,
    isActive: { $ne: false },
    fromDate: { $lte: rangeEnd },
    toDate: { $gte: rangeStart },
  })
    .select('_id leaveType status splitStatus fromDate toDate numberOfDays')
    .lean();

  for (const leave of leaves) {
    leaveStatusById.set(String(leave._id), String(leave.status || '').toLowerCase());
  }

  const splitLeaveIds = leaves
    .filter((leave) => String(leave.splitStatus || '').toLowerCase() === 'split_approved')
    .map((leave) => leave._id);
  const splits = splitLeaveIds.length
    ? await LeaveSplit.find({
        leaveId: { $in: splitLeaveIds },
        status: 'approved',
        date: { $gte: rangeStart, $lte: rangeEnd },
      })
        .select('leaveId leaveType date numberOfDays isHalfDay')
        .lean()
    : [];

  for (const leave of leaves) {
    if (String(leave.status || '').toLowerCase() !== 'approved') continue;
    if (String(leave.splitStatus || '').toLowerCase() === 'split_approved') continue;
    const lt = String(leave.leaveType || '').toUpperCase();
    if (!LEAVE_TYPES.includes(lt)) continue;

    for (let p = 0; p <= targetIdx; p++) {
      const slot = ordered[p].slot;
      const overlap = overlapDaysInclusive(leave.fromDate, leave.toDate, slot.payPeriodStart, slot.payPeriodEnd);
      const days = normalizedLeaveDays(leave, overlap);
      if (days <= 0) continue;
      bySlotPayroll.get(monthKey(slot))[lt] = roundHalf(bySlotPayroll.get(monthKey(slot))[lt] + days);
    }
  }

  for (const split of splits) {
    const lt = String(split.leaveType || '').toUpperCase();
    if (!LEAVE_TYPES.includes(lt)) continue;
    const days = roundHalf(Number(split.numberOfDays) || (split.isHalfDay ? 0.5 : 1));
    if (days <= 0) continue;

    for (let p = 0; p <= targetIdx; p++) {
      const slot = ordered[p].slot;
      const t = new Date(split.date).getTime();
      const s = new Date(slot.payPeriodStart).getTime();
      const e = new Date(slot.payPeriodEnd).getTime();
      if (t < s || t > e) continue;
      bySlotPayroll.get(monthKey(slot))[lt] = roundHalf(bySlotPayroll.get(monthKey(slot))[lt] + days);
      break;
    }
  }

  return { actualByPayroll: bySlotPayroll, leaveStatusById };
}

function computeUsed(slot, rollFlags, actualByPayroll, leaveStatusById) {
  const payroll = monthKey(slot);
  const actual = actualByPayroll.get(payroll) || { CL: 0, CCL: 0, EL: 0 };
  const out = {};
  const stale = [];
  for (const lt of LEAVE_TYPES) {
    const ledger = activeLedgerUsedForType(slot, lt, leaveStatusById);
    out[lt] = roundHalf(Math.max(ledger.used, Number(actual[lt]) || 0));
    stale.push(...ledger.ignoredStaleApplicationDebits.map((row) => ({ leaveType: lt, ...row })));
  }
  if (!rollFlags.elInPool) out.EL = activeLedgerUsedForType(slot, 'EL', leaveStatusById).used;
  return { used: out, stale };
}

function allocateLockedByPriority(lockedDays, credits, used, rollFlags) {
  let remaining = roundHalf(lockedDays);
  const locked = { CL: 0, CCL: 0, EL: 0 };
  for (const lt of LEAVE_TYPES) {
    if (lt === 'EL' && !rollFlags.elInPool) continue;
    const availableAfterUsed = roundHalf(Math.max(0, (Number(credits[lt]) || 0) - (Number(used[lt]) || 0)));
    const take = roundHalf(Math.min(remaining, availableAfterUsed));
    locked[lt] = take;
    remaining = roundHalf(Math.max(0, remaining - take));
  }
  return { locked, unallocatedLocked: remaining };
}

function computeCarry(slot, rollFlags, actualByPayroll, leaveStatusById) {
  const credits = slotCredits(slot, rollFlags);
  const c = computeUsed(slot, rollFlags, actualByPayroll, leaveStatusById);
  const monthLocked = roundHalf(
    Math.max(Number(slot?.lockedCredits) || 0, Number(slot?.monthlyApplyLocked) || 0)
  );
  const lockAllocation = allocateLockedByPriority(monthLocked, credits, c.used, rollFlags);
  return {
    credits,
    used: c.used,
    locked: lockAllocation.locked,
    monthLocked,
    unallocatedLocked: lockAllocation.unallocatedLocked,
    stale: c.stale,
    carry: {
      CL: rollFlags.CL ? roundHalf(Math.max(0, credits.CL - c.used.CL - lockAllocation.locked.CL)) : 0,
      CCL: rollFlags.CCL ? roundHalf(Math.max(0, credits.CCL - c.used.CCL - lockAllocation.locked.CCL)) : 0,
      EL: rollFlags.EL ? roundHalf(Math.max(0, credits.EL - c.used.EL - lockAllocation.locked.EL)) : 0,
    },
  };
}

function snapshotMonths(doc, targetIdx, rollFlags, actualByPayroll, leaveStatusById) {
  const ordered = sortSlotRefs(doc.months);
  return ordered.slice(0, targetIdx + 1).map(({ slot }) => {
    const c = computeCarry(slot, rollFlags, actualByPayroll, leaveStatusById);
    const actual = actualByPayroll.get(monthKey(slot)) || { CL: 0, CCL: 0, EL: 0 };
    return {
      label: slot.label || monthKey(slot),
      payroll: monthKey(slot),
      credits: {
        cl: round2(Number(slot.clCredits) || 0),
        ccl: round2(Number(slot.compensatoryOffs) || 0),
        el: round2(Number(slot.elCredits) || 0),
        lockedCl: round2(Number(slot.lockedCredits) || 0),
      },
      actualApprovedUsed: {
        cl: round2(actual.CL || 0),
        ccl: round2(actual.CCL || 0),
        el: round2(actual.EL || 0),
      },
      usedForCarry: {
        cl: c.used.CL,
        ccl: c.used.CCL,
        el: c.used.EL,
      },
      lockedForCarry: {
        monthLocked: c.monthLocked,
        cl: c.locked.CL,
        ccl: c.locked.CCL,
        el: c.locked.EL,
        unallocated: c.unallocatedLocked,
      },
      ignoredStaleApplicationDebits: c.stale,
      transferLedger: {
        in: {
          cl: sumTransfer(slot, 'in', 'CL'),
          ccl: sumTransfer(slot, 'in', 'CCL'),
          el: sumTransfer(slot, 'in', 'EL'),
        },
        out: {
          cl: sumTransfer(slot, 'out', 'CL'),
          ccl: sumTransfer(slot, 'out', 'CCL'),
          el: sumTransfer(slot, 'out', 'EL'),
        },
      },
      poolCarryForwardIn: {
        cl: round2(Number(slot.poolCarryForwardIn?.cl) || 0),
        ccl: round2(Number(slot.poolCarryForwardIn?.ccl) || 0),
        el: round2(Number(slot.poolCarryForwardIn?.el) || 0),
      },
      poolCarryForwardOut: {
        cl: round2(Number(slot.poolCarryForwardOut?.cl) || 0),
        ccl: round2(Number(slot.poolCarryForwardOut?.ccl) || 0),
        el: round2(Number(slot.poolCarryForwardOut?.el) || 0),
      },
      wouldCarryFromThisSlot: {
        cl: c.carry.CL,
        ccl: c.carry.CCL,
        el: c.carry.EL,
      },
    };
  });
}

function stripTransfersThroughTarget(doc, targetIdx) {
  const ordered = sortSlotRefs(doc.months);
  const removed = [];
  const revertedCarryIn = [];

  for (let p = 0; p <= targetIdx; p++) {
    const slot = ordered[p]?.slot;
    if (!slot) continue;

    if (p > 0) {
      const pin = slot.poolCarryForwardIn || {};
      const dCl = roundHalf(Number(pin.cl) || 0);
      const dCcl = roundHalf(Number(pin.ccl) || 0);
      const dEl = roundHalf(Number(pin.el) || 0);
      if (dCl || dCcl || dEl) {
        slot.clCredits = roundHalf(Math.max(0, (Number(slot.clCredits) || 0) - dCl));
        slot.compensatoryOffs = roundHalf(Math.max(0, (Number(slot.compensatoryOffs) || 0) - dCcl));
        slot.elCredits = roundHalf(Math.max(0, (Number(slot.elCredits) || 0) - dEl));
        revertedCarryIn.push({ slot: monthKey(slot), cl: dCl, ccl: dCcl, el: dEl });
      }
      slot.poolCarryForwardIn = { cl: 0, ccl: 0, el: 0 };
      slot.poolCarryForwardFromLabel = '';
    }

    const before = Array.isArray(slot.transactions) ? slot.transactions.length : 0;
    slot.transactions = (slot.transactions || []).filter((tx) => !isTransferTx(tx));
    const removedCount = Math.max(0, before - slot.transactions.length);
    if (removedCount > 0) removed.push({ slot: monthKey(slot), removedCount });

    slot.poolCarryForwardOut = { cl: 0, ccl: 0, el: 0 };
    slot.poolCarryForwardOutAt = null;
    slot.poolCarryForwardAllocation = undefined;
  }

  return { removed, revertedCarryIn };
}

function pushTransferTx(slot, leaveType, txType, days, autoGeneratedType, date, reason) {
  const d = roundHalf(days);
  if (d <= 0) return;
  if (!Array.isArray(slot.transactions)) slot.transactions = [];
  slot.transactions.push({
    at: new Date(),
    leaveType,
    transactionType: txType,
    days: d,
    openingBalance: 0,
    closingBalance: 0,
    startDate: date,
    endDate: date,
    reason,
    status: 'APPROVED',
    autoGenerated: true,
    autoGeneratedType,
  });
}

function rebuildTransfersThroughTarget(doc, targetIdx, rollFlags, actualByPayroll, leaveStatusById) {
  const ordered = sortSlotRefs(doc.months);
  const edges = [];

  for (let p = 0; p < targetIdx; p++) {
    const cur = ordered[p]?.slot;
    const next = ordered[p + 1]?.slot;
    if (!cur || !next) continue;

    const c = computeCarry(cur, rollFlags, actualByPayroll, leaveStatusById);
    const carry = c.carry;
    const fromLabel = monthKey(cur);
    const toLabel = monthKey(next);
    const lockedCreditsReleasedToTransferOut = roundHalf(Number(cur.lockedCredits) || 0);

    cur.lockedCredits = 0;
    cur.poolCarryForwardAllocation = {
      source: 'reconcile_leave_register_all_transfers_to_opening',
      credits: c.credits,
      actualOrLedgerUsed: c.used,
      lockedDeducted: c.locked,
      monthLocked: c.monthLocked,
      unallocatedLocked: c.unallocatedLocked,
      ignoredStaleApplicationDebits: c.stale,
      lockedCreditsReleasedToTransferOut,
      carryPosted: {
        cl: carry.CL,
        ccl: carry.CCL,
        el: carry.EL,
      },
      rollFlags,
    };

    const posted = carry.CL > 0 || carry.CCL > 0 || carry.EL > 0;
    if (posted) {
      cur.poolCarryForwardOut = { cl: carry.CL, ccl: carry.CCL, el: carry.EL };
      cur.poolCarryForwardOutAt = new Date();

      next.clCredits = roundHalf((Number(next.clCredits) || 0) + carry.CL);
      next.compensatoryOffs = roundHalf((Number(next.compensatoryOffs) || 0) + carry.CCL);
      next.elCredits = roundHalf((Number(next.elCredits) || 0) + carry.EL);
      next.poolCarryForwardIn = { cl: carry.CL, ccl: carry.CCL, el: carry.EL };
      next.poolCarryForwardFromLabel = cur.label || fromLabel;

      const outAt = cur.payPeriodEnd ? new Date(cur.payPeriodEnd) : new Date(cur.payPeriodStart || new Date());
      const inAt = next.payPeriodStart ? new Date(next.payPeriodStart) : new Date(next.payPeriodEnd || outAt);

      for (const lt of LEAVE_TYPES) {
        if (carry[lt] <= 0) continue;
        pushTransferTx(
          cur,
          lt,
          'DEBIT',
          carry[lt],
          transferAutoType('out', lt),
          outAt,
          `Reconciled transfer out unused monthly pool ${lt} from payroll ${fromLabel} to ${toLabel}.`
        );
        pushTransferTx(
          next,
          lt,
          'CREDIT',
          carry[lt],
          transferAutoType('in', lt),
          inAt,
          `Reconciled transfer in unused monthly pool ${lt} from payroll ${fromLabel} to ${toLabel}.`
        );
      }
    }

    edges.push({
      from: fromLabel,
      to: toLabel,
      credits: c.credits,
      usedForCarry: c.used,
      lockedDeducted: c.locked,
      monthLocked: c.monthLocked,
      unallocatedLocked: c.unallocatedLocked,
      ignoredStaleApplicationDebits: c.stale,
      carry,
      posted,
    });
  }

  return edges;
}

async function syncTouchedSlots(employeeId, doc, targetIdx) {
  const ordered = sortSlotRefs(doc.months);
  const seen = new Set();
  for (let p = 0; p <= targetIdx; p++) {
    const slot = ordered[p]?.slot;
    const anchor = slot?.payPeriodStart || slot?.payPeriodEnd;
    if (!anchor) continue;
    const key = new Date(anchor).toISOString();
    if (seen.has(key)) continue;
    seen.add(key);
    await leaveRegisterYearMonthlyApplyService.syncStoredMonthApplyFieldsForEmployeeDate(employeeId, anchor);
  }
}

function compactComparison(before, after) {
  const byPayroll = new Map(after.map((row) => [row.payroll, row]));
  return before.map((b) => {
    const a = byPayroll.get(b.payroll);
    return {
      payroll: b.payroll,
      label: b.label,
      credits: {
        cl: `${b.credits.cl} -> ${a?.credits.cl ?? 0}`,
        ccl: `${b.credits.ccl} -> ${a?.credits.ccl ?? 0}`,
        el: `${b.credits.el} -> ${a?.credits.el ?? 0}`,
      },
      usedForCarry: {
        cl: a?.usedForCarry.cl ?? 0,
        ccl: a?.usedForCarry.ccl ?? 0,
        el: a?.usedForCarry.el ?? 0,
      },
      transferIn: {
        cl: `${b.transferLedger.in.cl} -> ${a?.transferLedger.in.cl ?? 0}`,
        ccl: `${b.transferLedger.in.ccl} -> ${a?.transferLedger.in.ccl ?? 0}`,
        el: `${b.transferLedger.in.el} -> ${a?.transferLedger.in.el ?? 0}`,
      },
      transferOut: {
        cl: `${b.transferLedger.out.cl} -> ${a?.transferLedger.out.cl ?? 0}`,
        ccl: `${b.transferLedger.out.ccl} -> ${a?.transferLedger.out.ccl ?? 0}`,
        el: `${b.transferLedger.out.el} -> ${a?.transferLedger.out.el ?? 0}`,
      },
      wouldCarryFromThisSlot: a?.wouldCarryFromThisSlot || { cl: 0, ccl: 0, el: 0 },
      staleApplicationDebitsIgnored: a?.ignoredStaleApplicationDebits || [],
    };
  });
}

async function main() {
  const empNo = parseArg('empNo');
  const untilMonth = Number(parseArg('untilMonth') || parseArg('month') || '5');
  const untilYear = Number(parseArg('untilYear') || parseArg('year') || '2026');
  const financialYearArg = parseArg('financialYear');
  const apply = hasFlag('apply');

  if (!empNo) throw new Error('Pass --empNo <number>');
  if (!Number.isFinite(untilMonth) || untilMonth < 1 || untilMonth > 12 || !Number.isFinite(untilYear)) {
    throw new Error('Invalid --untilMonth / --untilYear');
  }
  if (!process.env.MONGODB_URI) throw new Error('MONGODB_URI missing');

  await mongoose.connect(process.env.MONGODB_URI);

  const emp = await Employee.findOne({
    $or: [{ emp_no: String(empNo) }, { emp_no: Number(empNo) }],
  })
    .select('_id emp_no employee_name casualLeaves paidLeaves compensatoryOffs is_active')
    .lean();
  if (!emp) throw new Error(`Employee not found: ${empNo}`);

  const fyName = financialYearArg
    ? String(financialYearArg).trim()
    : (await dateCycleService.getFinancialYearForDate(new Date(untilYear, untilMonth - 1, 1))).name;
  const policy = await LeavePolicySettings.getSettings().catch(() => ({}));
  const rollFlags = resolveRollFlags(policy);

  const beforeDoc = await LeaveRegisterYear.findOne({ employeeId: emp._id, financialYear: fyName });
  if (!beforeDoc) throw new Error(`LeaveRegisterYear not found for empNo ${empNo}, FY ${fyName}`);

  const ordered = sortSlotRefs(beforeDoc.months);
  const targetIdx = findTargetIndex(ordered, untilMonth, untilYear);
  if (targetIdx < 0) {
    throw new Error(
      `Target payroll slot ${untilMonth}/${untilYear} not found. Existing slots: ${ordered
        .map(({ slot }) => monthKey(slot))
        .join(', ')}`
    );
  }

  const actual = await buildActualApprovedUsage(emp._id, ordered, targetIdx);
  const before = snapshotMonths(beforeDoc, targetIdx, rollFlags, actual.actualByPayroll, actual.leaveStatusById);
  const yearAggregatesBefore = snapshotYearAggregates(beforeDoc).stored;

  const workingDoc = await LeaveRegisterYear.findById(beforeDoc._id);
  const strip = stripTransfersThroughTarget(workingDoc, targetIdx);
  const rebuiltEdges = rebuildTransfersThroughTarget(
    workingDoc,
    targetIdx,
    rollFlags,
    actual.actualByPayroll,
    actual.leaveStatusById
  );
  const yearAggregates = reconcileYearAggregates(workingDoc);

  let after = snapshotMonths(workingDoc, targetIdx, rollFlags, actual.actualByPayroll, actual.leaveStatusById);
  let registerServiceAfter = null;

  if (apply) {
    workingDoc.markModified('months');
    await workingDoc.save();
    for (const lt of LEAVE_TYPES) {
      await leaveRegisterYearLedgerService.recalculateRegisterBalances(emp._id, lt, null);
    }
    const aggregateFresh = await LeaveRegisterYear.findById(workingDoc._id);
    reconcileYearAggregates(aggregateFresh);
    await aggregateFresh.save();
    await syncTouchedSlots(emp._id, workingDoc, targetIdx);
    const fresh = await LeaveRegisterYear.findById(workingDoc._id);
    after = snapshotMonths(fresh, targetIdx, rollFlags, actual.actualByPayroll, actual.leaveStatusById);
    const grouped = await leaveRegisterService.getLeaveRegister({ employeeId: emp._id, financialYear: fyName }, null, null);
    const row = Array.isArray(grouped) ? grouped[0] : grouped;
    registerServiceAfter = {
      summary: row?.summary || null,
      yearSnapshot: row?.yearSnapshot || null,
    };
  }

  const result = {
    ok: true,
    dryRun: !apply,
    message: apply
      ? 'Applied transfer reconciliation up to target opening.'
      : 'Dry run only. Re-run with --apply to persist.',
    database: redactMongoUri(process.env.MONGODB_URI),
    employee: {
      _id: String(emp._id),
      emp_no: emp.emp_no,
      employee_name: emp.employee_name,
      is_active: emp.is_active,
      employeeBalancesBeforeRun: {
        casualLeaves: emp.casualLeaves,
        compensatoryOffs: emp.compensatoryOffs,
        paidLeaves: emp.paidLeaves,
      },
    },
    financialYear: fyName,
    targetOpening: { month: untilMonth, year: untilYear },
    rollFlags,
    removedTransferRows: strip.removed.reduce((sum, row) => sum + row.removedCount, 0),
    revertedCarryInSlots: strip.revertedCarryIn,
    rebuiltEdges,
    yearAggregates: {
      before: yearAggregatesBefore,
      after: apply
        ? snapshotYearAggregates(await LeaveRegisterYear.findById(workingDoc._id)).stored
        : yearAggregates.after,
    },
    comparison: compactComparison(before, after),
    before,
    after,
    registerServiceAfter,
  };

  console.log(JSON.stringify(result, null, 2));
  await mongoose.disconnect();
}

main().catch(async (error) => {
  console.error(error?.stack || error?.message || error);
  try {
    await mongoose.disconnect();
  } catch {}
  process.exit(1);
});
