/**
 * One-time fix: EL PAYROLL_USE debits were dated at payroll cycle START, so balance
 * recalc applied them before that month's EARNED_LEAVE credit and clamped the deduction.
 *
 * This script moves each PAYROLL_USE debit to the cycle END (same date as accrual credit),
 * then recalculates EL balances and syncs Employee.paidLeaves.
 *
 * Usage (from backend/):
 *   node scripts/reconcile_payroll_use_el_debit_dates.js --dept=Paddy --dry-run
 *   node scripts/reconcile_payroll_use_el_debit_dates.js --dept=Paddy --apply
 *   node scripts/reconcile_payroll_use_el_debit_dates.js --empNo=2213 --apply
 *   node scripts/reconcile_payroll_use_el_debit_dates.js --all --apply
 *
 * Flags:
 *   --dry-run   report only (default)
 *   --apply     write date fixes + recalc EL
 *   --dept=     department name or code
 *   --empNo=    single employee
 *   --all       all employees with at least one PAYROLL_USE EL debit
 */

const path = require('path');
const mongoose = require('mongoose');
require('dotenv').config({ path: path.join(__dirname, '../.env') });

require('../departments/model/Department');
const Employee = require('../employees/model/Employee');
const LeaveRegisterYear = require('../leaves/model/LeaveRegisterYear');
const dateCycleService = require('../leaves/services/dateCycleService');
const leaveRegisterYearLedgerService = require('../leaves/services/leaveRegisterYearLedgerService');
const { resolveDepartmentFromCli } = require('./lib/resolveDepartmentFromCli');

function parseArgs() {
  const o = { apply: false, dept: null, empNo: null, all: false };
  for (const a of process.argv.slice(2)) {
    if (a === '--apply') o.apply = true;
    else if (a === '--dry-run') o.apply = false;
    else if (a === '--all') o.all = true;
    else if (a.startsWith('--dept=')) o.dept = a.slice('--dept='.length).trim();
    else if (a.startsWith('--empNo=')) o.empNo = a.slice('--empNo='.length).trim();
  }
  return o;
}

function isPayrollUseElDebit(tx) {
  return (
    String(tx?.leaveType || '').toUpperCase() === 'EL' &&
    String(tx?.transactionType || '').toUpperCase() === 'DEBIT' &&
    tx?.autoGeneratedType === 'PAYROLL_USE'
  );
}

function sameDay(a, b) {
  if (!a || !b) return false;
  const da = new Date(a);
  const db = new Date(b);
  return (
    da.getFullYear() === db.getFullYear() &&
    da.getMonth() === db.getMonth() &&
    da.getDate() === db.getDate()
  );
}

async function resolveEmployeeIds(opts) {
  if (opts.empNo) {
    const emp = await Employee.findOne({
      $or: [{ emp_no: opts.empNo }, { emp_no: Number(opts.empNo) }],
    })
      .select('_id emp_no employee_name')
      .lean();
    if (!emp) throw new Error(`Employee not found: ${opts.empNo}`);
    return [emp];
  }
  if (opts.dept) {
    const d = await resolveDepartmentFromCli(opts.dept);
    return Employee.find({ is_active: true, department_id: d._id })
      .select('_id emp_no employee_name')
      .sort({ emp_no: 1 })
      .lean();
  }
  if (opts.all) {
    const ids = await LeaveRegisterYear.distinct('employeeId', {
      months: {
        $elemMatch: {
          transactions: {
            $elemMatch: {
              leaveType: 'EL',
              autoGeneratedType: 'PAYROLL_USE',
              transactionType: 'DEBIT',
            },
          },
        },
      },
    });
    return Employee.find({ _id: { $in: ids } })
      .select('_id emp_no employee_name')
      .sort({ emp_no: 1 })
      .lean();
  }
  throw new Error('Pass --dept=NAME, --empNo=..., or --all');
}

async function getElBalance(employeeId) {
  return leaveRegisterYearLedgerService.getCurrentBalanceLedgerOnly(employeeId, 'EL', new Date());
}

async function reconcileEmployee(emp, apply) {
  const docs = await LeaveRegisterYear.find({ employeeId: emp._id });
  const changes = [];
  let docsTouched = 0;

  for (const doc of docs) {
    let docChanged = false;
    for (let mi = 0; mi < (doc.months || []).length; mi++) {
      const slot = doc.months[mi];
      const pm = Number(slot.payrollCycleMonth);
      const py = Number(slot.payrollCycleYear);
      if (!pm || !py) continue;

      const cycle = await dateCycleService.getPayrollCycleForMonth(py, pm);
      const cycleEnd = cycle.endDate;
      const cycleStart = cycle.startDate;

      for (let ti = 0; ti < (slot.transactions || []).length; ti++) {
        const tx = slot.transactions[ti];
        if (!isPayrollUseElDebit(tx)) continue;

        const curStart = tx.startDate ? new Date(tx.startDate) : null;
        const needsFix =
          !sameDay(curStart, cycleEnd) &&
          (sameDay(curStart, cycleStart) || (curStart && curStart < cycleEnd));

        if (!needsFix) continue;

        changes.push({
          fy: doc.financialYear,
          slot: `${pm}/${py}`,
          days: tx.days,
          from: curStart?.toISOString?.().slice(0, 10),
          to: cycleEnd.toISOString().slice(0, 10),
          batchId: tx.payrollBatchId ? String(tx.payrollBatchId) : null,
        });

        if (apply) {
          tx.startDate = cycleEnd;
          tx.endDate = cycleEnd;
          docChanged = true;
          doc.markModified(`months.${mi}.transactions`);
        }
      }
    }
    if (docChanged) {
      docsTouched += 1;
      await doc.save();
    }
  }

  let elBefore = null;
  let elAfter = null;
  if (changes.length > 0 && apply) {
    elBefore = await getElBalance(emp._id);
    await leaveRegisterYearLedgerService.recalculateRegisterBalances(emp._id, 'EL', null);
    elAfter = await getElBalance(emp._id);
  } else if (changes.length > 0) {
    elBefore = await getElBalance(emp._id);
  }

  return { changes, docsTouched, elBefore, elAfter };
}

async function main() {
  const opts = parseArgs();
  const uri = process.env.MONGODB_URI || process.env.MONGO_URI;
  if (!uri) throw new Error('MONGODB_URI not set');

  await mongoose.connect(uri);
  console.log(`[reconcile-payroll-use-el] connected (${opts.apply ? 'APPLY' : 'DRY-RUN'})\n`);

  const employees = await resolveEmployeeIds(opts);
  console.log(`Employees in scope: ${employees.length}\n`);

  let totalChanges = 0;
  let employeesFixed = 0;

  for (const emp of employees) {
    const { changes, docsTouched, elBefore, elAfter } = await reconcileEmployee(emp, opts.apply);
    if (!changes.length) continue;

    employeesFixed += 1;
    totalChanges += changes.length;
    console.log(`--- ${emp.emp_no} ${emp.employee_name || ''} ---`);
    for (const c of changes) {
      console.log(
        `  FY ${c.fy} slot ${c.slot}: PAYROLL_USE ${c.days}d  start ${c.from} → ${c.to}${c.batchId ? ` batch=${c.batchId.slice(-6)}` : ''}`
      );
    }
    if (opts.apply) {
      console.log(`  EL balance: ${elBefore} → ${elAfter} (docs saved: ${docsTouched})`);
    } else if (elBefore != null) {
      console.log(`  EL balance now (wrong order): ${elBefore} — run --apply to fix dates + recalc`);
    }
    console.log('');
  }

  console.log('=== Summary ===');
  console.log(`Employees with PAYROLL_USE date fixes needed: ${employeesFixed}`);
  console.log(`Transaction rows to move to cycle-end: ${totalChanges}`);
  if (!opts.apply && totalChanges > 0) {
    console.log('\nRe-run with --apply to persist fixes and recalculate EL / paidLeaves.');
  }

  await mongoose.disconnect();
}

main().catch(async (e) => {
  console.error(e.message || e);
  try {
    await mongoose.disconnect();
  } catch {}
  process.exit(1);
});
