/**
 * Full leave-register **monthly pool carry** repair for one employee, a division, or everyone:
 * 1. **Strip (clean slate)** — delete all monthly pool carry rows: `MONTHLY_POOL_TRANSFER_OUT_*` / `IN_*`, plus legacy
 *    auto-generated carry rows that match the same “Transfer in/out — unused monthly apply pool …” reasons when
 *    `autoGeneratedType` was missing (so duplicates are actually removed before replay).
 *    clear carry metadata (including `poolCarryForwardAllocation`), and **subtract** prior carry-in from slot
 *    `clCredits` / `compensatoryOffs` / `elCredits` so counts are back to **native credits only** (no double carry-in).
 * 2. **Replay oldest → newest** — for each **closed** payroll month before the open cycle (sorted by `payPeriodEnd`),
 *    recompute unused pool from **credits − used − CL monthly-apply lock** (`monthlyApplyLocked`; legacy `lockedCredits` ignored), then **create** fresh transfer OUT on the
 *    closing slot and transfer IN on the next via `monthlyPoolCarryForwardService` (same as accrual cron).
 * 3. Caps replay to the **present payroll cycle month/year** by default (`--throughPresent true`) so June–Dec
 *    are not processed while you are still in May (same idea as production reconcile).
 * 4. Re-chains CL/CCL/EL ledger balances, syncs monthly apply + register display snapshot.
 * 5. Prints a per-month audit: register **Carried in / Transfer out** (view vs txn sums) plus **OK/MISMATCH**,
 *    and checks **Balance** = Credits + Carried in − Used − Transfer out vs API `poolBalance` when present.
 *
 * Usage (from backend folder):
 *   node scripts/reconcile_leave_register_pool_transactions.js --empNo 2146
 *   node scripts/reconcile_leave_register_pool_transactions.js --empNo 2146 --fy 2026
 *   node scripts/reconcile_leave_register_pool_transactions.js --all --limit 50
 *   node scripts/reconcile_leave_register_pool_transactions.js --divisionName "PYDAHSOFT"
 *
 * Flags:
 *   --asOf ISO              Reference “today” for open-cycle cutoff (default: now)
 *   --throughPresent false  Do not cap by current payroll cycle month/year (replay all closed months in FY)
 *   --throughPayrollMonth N Override month cap (e.g. 5)
 *   --throughPayrollYear Y  Override year (optional with month)
 *   --fy NAME               Financial year for audit table (default: FY for --asOf)
 *   --auditOnly true        Skip strip/replay; only print audit (read-only)
 *   --dryRun true           Print planned closing count + audit-only, no writes
 *   --clearPendingLocks false  Skip Phase 0 (default: run Phase 0 on full reconcile — reject
 *                              in-pipeline cap-counted leaves in pay periods with lock, sync apply fields, zero all slot `lockedCredits` for the employee)
 *
 * Env: MONGODB_URI or MONGO_URI
 */

const path = require('path');
const mongoose = require('mongoose');
require('dotenv').config({ path: path.resolve(__dirname, '../.env') });

require('../departments/model/Designation');
require('../departments/model/Department');
require('../departments/model/Division');

const Employee = require('../employees/model/Employee');
const Division = require('../departments/model/Division');
const LeaveRegisterYear = require('../leaves/model/LeaveRegisterYear');
const leaveRegisterService = require('../leaves/services/leaveRegisterService');
const leaveRegisterYearLedgerService = require('../leaves/services/leaveRegisterYearLedgerService');
const leaveRegisterYearMonthlyApplyService = require('../leaves/services/leaveRegisterYearMonthlyApplyService');
const dateCycleService = require('../leaves/services/dateCycleService');
const leaveRegisterPoolCarryReconcileService = require('../leaves/services/leaveRegisterPoolCarryReconcileService');
const leaveRegisterPoolReconcileClearLocksService = require('../leaves/services/leaveRegisterPoolReconcileClearLocksService');
const leaveRegisterYearService = require('../leaves/services/leaveRegisterYearService');
const { createISTDate, getTodayISTDateString } = require('../shared/utils/dateUtils');
const {
  isOptimisticLockConflict,
  optimisticRetryDelayMs,
  sleep: optimisticLockSleep,
} = require('../shared/utils/mongooseOptimisticRetry');

function escapeRegex(s) {
  return String(s).replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function parseArg(name) {
  const key = String(name).replace(/^--/, '');
  const idx = process.argv.findIndex((a) => a === `--${key}`);
  if (idx >= 0 && process.argv[idx + 1] != null) return process.argv[idx + 1];
  return undefined;
}

function parseBool(v, defaultValue = false) {
  if (v == null) return defaultValue;
  const s = String(v).trim().toLowerCase();
  if (['1', 'true', 'yes', 'y', 'on'].includes(s)) return true;
  if (['0', 'false', 'no', 'n', 'off'].includes(s)) return false;
  return defaultValue;
}

function sumTransferTxDays(txs, dir, leaveType) {
  const wantLt = String(leaveType || '').toUpperCase();
  const prefix = dir === 'IN' ? 'MONTHLY_POOL_TRANSFER_IN_' : 'MONTHLY_POOL_TRANSFER_OUT_';
  if (!Array.isArray(txs)) return 0;
  let sum = 0;
  for (const t of txs) {
    const ag = String(t?.autoGeneratedType || '');
    if (!ag.startsWith(prefix)) continue;
    if (String(t?.leaveType || '').toUpperCase() !== wantLt) continue;
    sum += Number(t.days) || 0;
  }
  return Math.round(sum * 100) / 100;
}

/** Count rows about to be stripped (all FY docs for employee). */
async function countMonthlyPoolTransferArtifacts(employeeId) {
  const docs = await LeaveRegisterYear.find({ employeeId }).select('financialYear months').lean();
  let transferTxRows = 0;
  let slotsWithCarryMeta = 0;
  for (const d of docs) {
    for (const s of d.months || []) {
      if (s.poolCarryForwardIn || s.poolCarryForwardOut != null || s.poolCarryForwardOutAt) {
        slotsWithCarryMeta += 1;
      }
      for (const t of s.transactions || []) {
        if (leaveRegisterYearService.isMonthlyPoolCarrySlotTransaction(t)) {
          transferTxRows += 1;
        }
      }
    }
  }
  return { transferTxRows, slotsWithCarryMeta, fyDocCount: docs.length };
}

function numOrDash(v) {
  if (v === null || v === undefined || v === '—') return null;
  const n = Number(v);
  return Number.isFinite(n) ? n : null;
}

/**
 * UI grid: Balance = Credits + Carried in − Used − Transfer out, Used = debits + lock.
 * Confirms API `poolBalance` matches that identity when present.
 */
function poolBalanceGridAuditIssues(rm) {
  const triples = [
    ['CL', rm.policyScheduledCl, rm.cl],
    ['CCL', rm.policyScheduledCco, rm.ccl],
    ['EL', rm.policyScheduledEl, rm.el],
  ];
  const bad = [];
  for (const [lt, pol, b] of triples) {
    if (!b || b.poolBalance == null || !Number.isFinite(Number(b.poolBalance))) continue;
    const cr = numOrDash(pol);
    const tin = numOrDash(b.transferIn);
    if (cr == null && tin == null) continue;
    const tout = Number(b.transferOut) || 0;
    const ul = (Number(b.used) || 0) + (Number(b.locked) || 0);
    const expected = (cr ?? 0) + (tin ?? 0) - ul - tout;
    const actual = Number(b.poolBalance);
    if (Math.abs(expected - actual) > 0.02) bad.push(lt);
  }
  return bad;
}

/** Per month: OK if register transfer columns match summed FY-slot txs for CL/CCL/EL. */
function poolTransferAuditStatus(rm, txs) {
  const checks = [
    ['CL', rm.cl?.transferIn, rm.cl?.transferOut, 'CL'],
    ['CCL', rm.ccl?.transferIn, rm.ccl?.transferOut, 'CCL'],
    ['EL', rm.el?.transferIn, rm.el?.transferOut, 'EL'],
  ];
  const bad = [];
  for (const [, vin, vout, lt] of checks) {
    const a = numOrDash(vin);
    const b = numOrDash(vout);
    const tin = sumTransferTxDays(txs, 'IN', lt);
    const tout = sumTransferTxDays(txs, 'OUT', lt);
    if (a !== tin || b !== tout) bad.push(lt);
  }
  return bad.length === 0 ? 'OK' : `MISMATCH:${bad.join(',')}`;
}

/** Closed payroll slots strictly before open cycle start, optionally capped by payroll month/year. */
async function countPlannedCarryEdges(employeeId, asOf, throughPayrollMonth, throughPayrollYear) {
  const periodInfo = await dateCycleService.getPeriodInfo(asOf);
  const currentCycleStart = periodInfo?.payrollCycle?.startDate;
  const carryCutoff =
    currentCycleStart != null ? new Date(currentCycleStart) : createISTDate(getTodayISTDateString());

  const closings = [];
  const refreshed = await LeaveRegisterYear.find({ employeeId }).sort({ financialYearStart: 1 }).lean();
  for (const d of refreshed) {
    for (const slot of d.months || []) {
      if (!slot.payPeriodEnd) continue;
      if (!leaveRegisterYearService.isPayrollPeriodClosedBeforeAsOf(slot.payPeriodEnd, carryCutoff)) continue;
      closings.push({
        pm: Number(slot.payrollCycleMonth),
        py: Number(slot.payrollCycleYear),
        t: new Date(slot.payPeriodEnd).getTime(),
      });
    }
  }
  const seen = new Set();
  let ordered = closings
    .filter((c) => {
      if (!Number.isFinite(c.pm) || !Number.isFinite(c.py)) return false;
      const k = `${c.py}-${c.pm}`;
      if (seen.has(k)) return false;
      seen.add(k);
      return true;
    })
    .sort((a, b) => a.t - b.t);

  if (throughPayrollMonth != null && Number.isFinite(Number(throughPayrollMonth))) {
    const capM = Number(throughPayrollMonth);
    const capY = throughPayrollYear;
    ordered = ordered.filter((c) => {
      if (Number(c.pm) > capM) return false;
      if (capY != null && Number.isFinite(Number(capY)) && Number(c.py) !== Number(capY)) return false;
      return true;
    });
  }

  return {
    edges: ordered.length,
    carryCutoffIso: carryCutoff?.toISOString?.() || String(carryCutoff),
    currentPayrollCycle: periodInfo?.payrollCycle
      ? { month: periodInfo.payrollCycle.month, year: periodInfo.payrollCycle.year }
      : null,
  };
}

async function recalcOne(employeeId) {
  await leaveRegisterYearLedgerService.recalculateRegisterBalances(employeeId, 'CL', null);
  await leaveRegisterYearLedgerService.recalculateRegisterBalances(employeeId, 'CCL', null);
  await leaveRegisterYearLedgerService.recalculateRegisterBalances(employeeId, 'EL', null);
}

async function syncMonthApplySnapshot(employeeId, asOf) {
  try {
    await leaveRegisterYearMonthlyApplyService.syncStoredMonthApplyFieldsForEmployeeDate(employeeId, asOf);
  } catch (e) {
    console.warn(`  (syncMonthlyApply warn) ${e.message || e}`);
  }
}

async function syncRegisterDisplaySnapshot(employeeId, fyName) {
  try {
    if (!fyName) return;
    const leaveRegisterYearRegisterDisplaySyncService = require('../leaves/services/leaveRegisterYearRegisterDisplaySyncService');
    await leaveRegisterYearRegisterDisplaySyncService.syncRegisterDisplaySnapshotsForEmployeeFy(employeeId, fyName);
  } catch (e) {
    console.warn(`  (registerDisplaySnapshot warn) ${e.message || e}`);
  }
}

/** After lock clear / reconcile: stored monthly apply + admin lock per slot (read from DB). */
async function printMonthlyApplyLockAudit(employeeId, fyName) {
  const y = await LeaveRegisterYear.findOne({ employeeId, financialYear: fyName })
    .select('months.label months.payrollCycleMonth months.payrollCycleYear months.monthlyApplyLocked months.lockedCredits months.monthlyApplyConsumed')
    .lean();
  if (!y?.months?.length) {
    console.log(`  Lock audit FY ${fyName}: no year row`);
    return;
  }
  console.log(`\n--- FY ${fyName} monthly apply lock snapshot (stored slot fields) ---`);
  console.log(['Month', 'pm/py', 'Lk(slot)', 'mApplyLocked', 'mApplyConsumed'].join('\t'));
  for (const m of y.months) {
    const pm = Number(m.payrollCycleMonth);
    const py = Number(m.payrollCycleYear);
    console.log(
      [
        m.label || `${pm}/${py}`,
        `${pm}/${py}`,
        Number(m.lockedCredits) || 0,
        Number(m.monthlyApplyLocked) || 0,
        m.monthlyApplyConsumed != null ? Number(m.monthlyApplyConsumed) : '—',
      ].join('\t')
    );
  }
}

/**
 * @param {{ compact?: boolean }} [opts] — compact: one-line summary only (for --all bulk).
 */
async function printPoolTransferAudit(employeeId, fyName, opts = {}) {
  const compact = opts.compact === true;
  const grouped = await leaveRegisterService.getLeaveRegister({ employeeId, financialYear: fyName }, null, null);
  const row = Array.isArray(grouped) ? grouped[0] : grouped;
  const months = row?.registerMonths || [];
  const ydoc = await LeaveRegisterYear.findOne({ employeeId, financialYear: fyName }).lean();

  let mismatchMonths = 0;
  let balanceMismatchMonths = 0;
  let monthsWithPoolBalance = 0;
  const tableLines = [];
  for (const rm of months) {
    const pm = Number(rm.month);
    const py = Number(rm.year);
    const slot = (ydoc?.months || []).find(
      (s) => Number(s.payrollCycleMonth) === pm && Number(s.payrollCycleYear) === py
    );
    const txs = slot?.transactions || [];
    const st = poolTransferAuditStatus(rm, txs);
    if (st !== 'OK') mismatchMonths += 1;
    const balIssues = poolBalanceGridAuditIssues(rm);
    if (balIssues.length) balanceMismatchMonths += 1;
    if (['CL', 'CCL', 'EL'].some((lt) => {
      const b = lt === 'CL' ? rm.cl : lt === 'CCL' ? rm.ccl : rm.el;
      return b?.poolBalance != null && Number.isFinite(Number(b.poolBalance));
    })) {
      monthsWithPoolBalance += 1;
    }
    tableLines.push({
      label: rm.label || `${pm}/${py}`,
      line: [
        rm.label || `${pm}/${py}`,
        rm.cl?.transferIn ?? '—',
        rm.cl?.transferOut ?? '—',
        sumTransferTxDays(txs, 'IN', 'CL'),
        sumTransferTxDays(txs, 'OUT', 'CL'),
        rm.ccl?.transferIn ?? '—',
        rm.ccl?.transferOut ?? '—',
        sumTransferTxDays(txs, 'IN', 'CCL'),
        sumTransferTxDays(txs, 'OUT', 'CCL'),
        rm.el?.transferIn ?? '—',
        rm.el?.transferOut ?? '—',
        sumTransferTxDays(txs, 'IN', 'EL'),
        sumTransferTxDays(txs, 'OUT', 'EL'),
        st,
      ].join('\t'),
    });
  }

  if (compact) {
    const ok = mismatchMonths === 0;
    const okBal = balanceMismatchMonths === 0;
    let line = `  Audit FY ${fyName}: ${months.length} month row(s), ${ok ? 'all OK (view = txn sums)' : `${mismatchMonths} row(s) MISMATCH — pass --verbose for full table`}`;
    if (monthsWithPoolBalance > 0) {
      line += ` | grid balance ${okBal ? 'OK' : `${balanceMismatchMonths} mo MISMATCH`}`;
    }
    console.log(line);
  } else {
    console.log(`\n--- FY ${fyName} pool transfer audit ---`);
    console.log(
      'UI: Credits=policy pool; Carried in=transfer IN; Used=debits+lock; Balance=Credits+Carried in−Used−Transfer out.'
    );
    console.log(
      'Columns: *_v_in/out = register Carried in / Transfer out; *_tx_* = summed FY-slot MONTHLY_POOL_TRANSFER_IN_* / OUT_*'
    );
    console.log(
      [
        'Month',
        'CL_v_in',
        'CL_v_out',
        'CL_tx_in',
        'CL_tx_out',
        'CCL_v_in',
        'CCL_v_out',
        'CCL_tx_in',
        'CCL_tx_out',
        'EL_v_in',
        'EL_v_out',
        'EL_tx_in',
        'EL_tx_out',
        'audit',
      ].join('\t')
    );
    for (const { line } of tableLines) {
      console.log(line);
    }
    console.log(
      mismatchMonths === 0
        ? `Summary: all ${months.length} month row(s) — view vs txn sums OK.`
        : `Summary: ${mismatchMonths} month row(s) flagged MISMATCH (see audit column).`
    );
    if (monthsWithPoolBalance > 0) {
      console.log(
        balanceMismatchMonths === 0
          ? `Grid balance: API poolBalance matches Credits+Carried in−Used−Transfer out for all ${monthsWithPoolBalance} month row(s) that expose poolBalance.`
          : `Grid balance: ${balanceMismatchMonths} month row(s) where poolBalance ≠ Credits+Carried in−Used−Transfer out (check policy credits vs slot).`
      );
    }
  }
  return { monthCount: months.length, mismatchMonths, balanceMismatchMonths };
}

async function main() {
  const uri = process.env.MONGODB_URI || process.env.MONGO_URI;
  if (!uri) throw new Error('MONGODB_URI (or MONGO_URI) not set');

  await mongoose.connect(uri);
  if (typeof mongoose.connection.asPromise === 'function') {
    await mongoose.connection.asPromise();
  }
  console.log('[reconcile_leave_register_pool_transactions] connected');

  const dryRun = parseBool(parseArg('dryRun'), false) || parseBool(process.env.DRY_RUN, false);
  const auditOnly = parseBool(parseArg('auditOnly'), false);
  const all = process.argv.includes('--all');
  const empNo = parseArg('empNo') || process.env.EMP_NO;
  const divisionToken = parseArg('divisionName');
  const limit = Math.max(0, Number(parseArg('limit') || process.env.LIMIT || 0));

  const asOfRaw = parseArg('asOf');
  const asOf = asOfRaw ? new Date(asOfRaw) : new Date();
  if (Number.isNaN(asOf.getTime())) throw new Error(`Invalid --asOf: ${asOfRaw}`);

  const throughPresent = parseBool(parseArg('throughPresent'), true);
  let throughPayrollMonth = null;
  let throughPayrollYear = null;
  if (throughPresent) {
    const pi = await dateCycleService.getPeriodInfo(asOf);
    if (pi?.payrollCycle?.month != null && pi?.payrollCycle?.year != null) {
      throughPayrollMonth = Number(pi.payrollCycle.month);
      throughPayrollYear = Number(pi.payrollCycle.year);
    }
  }
  const tpmOverride = parseArg('throughPayrollMonth');
  const tpyOverride = parseArg('throughPayrollYear');
  if (tpmOverride != null && String(tpmOverride).trim() !== '') {
    const n = parseInt(String(tpmOverride).trim(), 10);
    if (Number.isFinite(n)) throughPayrollMonth = n;
  }
  if (tpyOverride != null && String(tpyOverride).trim() !== '') {
    const n = parseInt(String(tpyOverride).trim(), 10);
    if (Number.isFinite(n)) throughPayrollYear = n;
  }

  const fyArg = parseArg('fy');
  const periodInfo = await dateCycleService.getPeriodInfo(asOf);
  const fyDefault = periodInfo?.financialYear?.name;
  const fyName = (fyArg && String(fyArg).trim()) || fyDefault;
  if (!fyName) throw new Error('Could not resolve financial year (pass --fy)');
  console.log(`asOf=${asOf.toISOString()} FY(audit)=${fyName}`);
  console.log(
    `throughPresent=${throughPresent} cap=${throughPayrollMonth != null ? `pm<=${throughPayrollMonth}${throughPayrollYear != null ? ` py=${throughPayrollYear}` : ''}` : 'none'}\n`
  );

  let employees = [];
  if (all) {
    const q = Employee.find({ is_active: true }).select('_id emp_no employee_name').sort({ emp_no: 1 }).lean();
    const list = await q;
    employees = limit > 0 ? list.slice(0, limit) : list;
    console.log(`Mode: --all (${employees.length} employees${limit ? `, limit ${limit}` : ''})`);
  } else if (divisionToken) {
    const divisions = await Division.find({
      name: new RegExp(escapeRegex(String(divisionToken).trim()), 'i'),
    })
      .select('_id name')
      .lean();
    if (!divisions.length) {
      console.error('No division matched:', divisionToken);
      process.exit(1);
    }
    console.log(`Mode: --divisionName "${divisionToken}" → ${divisions.map((d) => d.name).join(', ')}`);
    const divIds = divisions.map((d) => d._id);
    const list = await Employee.find({ division_id: { $in: divIds }, is_active: true })
      .select('_id emp_no employee_name')
      .sort({ emp_no: 1 })
      .lean();
    employees = limit > 0 ? list.slice(0, limit) : list;
    console.log(`Employees in scope: ${employees.length}`);
  } else if (empNo) {
    const emp = await Employee.findOne({
      $or: [{ emp_no: String(empNo) }, { emp_no: Number(empNo) }],
    })
      .select('_id emp_no employee_name')
      .lean();
    if (!emp) {
      console.error('Employee not found:', empNo);
      process.exit(1);
    }
    employees = [emp];
    console.log(`Mode: --empNo ${empNo} (${emp.employee_name || 'n/a'})`);
  } else {
    console.error('Pass --empNo <n>, --all [--limit N], or --divisionName <substring>');
    process.exit(1);
  }

  let ok = 0;
  let fail = 0;
  let auditMismatchEmployees = 0;
  let auditGridBalanceMismatchEmployees = 0;
  const verbose = parseBool(parseArg('verbose'), false);
  const clearPendingLocks = auditOnly ? false : parseBool(parseArg('clearPendingLocks'), true);

  for (const e of employees) {
    const id = e._id;
    const label = `${e.emp_no} ${e.employee_name || ''}`.trim();
    try {
      const plan = await countPlannedCarryEdges(id, asOf, throughPayrollMonth, throughPayrollYear);
      console.log(
        `→ ${label} | plannedClosedCarrySteps=${plan.edges} closedBefore=${plan.carryCutoffIso} payrollCycle(now)=${JSON.stringify(plan.currentPayrollCycle)}`
      );

      if (dryRun || auditOnly) {
        if (dryRun && clearPendingLocks) {
          const c0 = await leaveRegisterPoolReconcileClearLocksService.clearPendingMonthlyCapLocksForEmployee(id, {
            dryRun: true,
          });
          console.log(
            `  Phase 0 (dry run) — clear cap locks: slotsWithLock=${c0.slotsScanned}, wouldRejectLeaves=${c0.leavesRejected}`
          );
        }
        if (dryRun) {
          const pre = await countMonthlyPoolTransferArtifacts(id);
          console.log(
            `  Dry run — would strip ${pre.transferTxRows} pool-transfer txn row(s); ${pre.slotsWithCarryMeta} slot month(s) with carry metadata (${pre.fyDocCount} FY doc(s)).`
          );
        }
        const auDry = await printPoolTransferAudit(id, fyName, {
          compact: employees.length > 1 && !verbose,
        });
        if ((auDry.balanceMismatchMonths ?? 0) > 0) {
          auditGridBalanceMismatchEmployees += 1;
          console.warn(
            `  WARNING: ${auDry.balanceMismatchMonths} month row(s) — poolBalance ≠ Credits+Carried in−Used−Transfer out.`
          );
        }
        if (auditOnly && verbose && employees.length === 1) {
          await printMonthlyApplyLockAudit(id, fyName);
        }
        ok++;
        continue;
      }

      if (clearPendingLocks) {
        console.log(
          '  Phase 0 — clear monthly cap locks: reject in-pipeline cap-counted leaves in pay periods with stored lock; zero slot lockedCredits; resync monthlyApply*. '
        );
        const c0 = await leaveRegisterPoolReconcileClearLocksService.clearPendingMonthlyCapLocksForEmployee(id, {
          dryRun: false,
        });
        console.log(
          `  Phase 0 done: slotsWithLock=${c0.slotsScanned}, leavesRejected=${c0.leavesRejected}, syncPeriods=${c0.syncPeriods}, lockedCreditsSlotsCleared=${c0.lockedCreditsSlotsCleared}`
        );
        if (c0.leaveIds?.length && verbose) {
          console.log(`  Rejected leave _id(s): ${c0.leaveIds.join(', ')}`);
        }
      }

      const preStrip = await countMonthlyPoolTransferArtifacts(id);
      console.log(
        `  Phase 1 — strip: remove ${preStrip.transferTxRows} pool-transfer txn row(s); ` +
          `clear carry metadata on ${preStrip.slotsWithCarryMeta} slot month(s) across ${preStrip.fyDocCount} FY doc(s); ` +
          `revert rolled-in amounts on slot credits (CL/CCL/EL).`
      );
      console.log(
        '  Phase 2 — replay: closed payroll months in calendar order (earliest first); each month posts OUT = unused pool ' +
          '(credits − used − CL lock where applicable), then IN on the next month.'
      );

      let r = { ok: false, error: 'not started' };
      for (let attempt = 1; attempt <= 10; attempt++) {
        r = await leaveRegisterPoolCarryReconcileService.reconcilePoolCarryChainAfterRegisterChange(id, {
          asOfDate: asOf,
          throughPayrollMonth: throughPayrollMonth != null ? throughPayrollMonth : undefined,
          throughPayrollYear: throughPayrollYear != null ? throughPayrollYear : undefined,
        });
        if (r.ok) break;
        if (!isOptimisticLockConflict(r.error) || attempt === 10) break;
        console.warn(`  (reconcile strip+replay retry ${attempt}/10) ${r.error}`);
        await optimisticLockSleep(optimisticRetryDelayMs(attempt));
      }
      if (!r.ok) {
        console.warn(`  FAIL reconcile: ${r.error}`);
        fail++;
        continue;
      }
      for (let attempt = 1; attempt <= 10; attempt++) {
        try {
          await recalcOne(id);
          break;
        } catch (e) {
          if (!isOptimisticLockConflict(e) || attempt === 10) throw e;
          console.warn(`  (recalc balances retry ${attempt}/10) ${e.message || e}`);
          await optimisticLockSleep(optimisticRetryDelayMs(attempt));
        }
      }
      await syncMonthApplySnapshot(id, asOf);
      await syncRegisterDisplaySnapshot(id, fyName);

      console.log(
        `  OK reconcile: FY rows=${r.yearsTouched}, steps=${r.edgesApplied}, poolTxPairs=${r.carriesPosted || 0}${r.carryErrors ? `, carryErr=${r.carryErrors}` : ''}`
      );
      const au = await printPoolTransferAudit(id, fyName, {
        compact: employees.length > 1 && !verbose,
      });
      if (au.mismatchMonths > 0) auditMismatchEmployees += 1;
      if ((au.balanceMismatchMonths ?? 0) > 0) {
        auditGridBalanceMismatchEmployees += 1;
        console.warn(
          `  WARNING: ${au.balanceMismatchMonths} month row(s) — poolBalance ≠ Credits+Carried in−Used−Transfer out (register grid identity).`
        );
      }
      const post = await countMonthlyPoolTransferArtifacts(id);
      console.log(
        `  Post-reconcile: ${post.transferTxRows} pool-transfer txn row(s) on file; carry metadata on ${post.slotsWithCarryMeta} slot month(s).`
      );
      if (au.mismatchMonths > 0) {
        console.warn(
          `  WARNING: ${au.mismatchMonths} audit month row(s) view≠txn for this employee${employees.length > 1 && !verbose ? ' (re-run with --verbose for tables)' : ''}.`
        );
      }
      if (verbose && employees.length === 1) {
        await printMonthlyApplyLockAudit(id, fyName);
      }
      ok++;
    } catch (err) {
      fail++;
      console.error(`FAIL: ${label}`, err.message || err);
    }
  }

  console.log(
    `\nDone. success=${ok} failed=${fail}${dryRun ? ' (dry run)' : ''}${auditOnly ? ' (audit only)' : ''}` +
      (employees.length > 1 && !dryRun && !auditOnly
        ? ` | employees_with_audit_month_mismatch=${auditMismatchEmployees} (of ${employees.length}; view vs txn)` +
            (auditGridBalanceMismatchEmployees > 0
              ? ` | employees_with_grid_balance_mismatch=${auditGridBalanceMismatchEmployees}`
              : '')
        : '') +
      (employees.length > 1 && (dryRun || auditOnly) && auditGridBalanceMismatchEmployees > 0
        ? ` | employees_with_grid_balance_mismatch=${auditGridBalanceMismatchEmployees}`
        : '')
  );
  await mongoose.disconnect();
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
