/**
 * Reconcile LeaveRegisterYear.months[].clCredits from transaction truth.
 *
 * For each target slot:
 *   clCredits = sum(MONTHLY_CL_SCHEDULE CREDIT CL transactions) + poolCarryForwardIn.cl
 *
 * This fixes frontend/admin fields when transfer reconciliation changed carry-in but
 * the stored scheduled CL pool did not line up with the scheduled CL transaction row.
 *
 * Usage:
 *   node scripts/reconcile_leave_register_scheduled_cl_from_transactions.js --empNo 2202 --untilMonth 5 --untilYear 2026
 *   node scripts/reconcile_leave_register_scheduled_cl_from_transactions.js --all --untilMonth 5 --untilYear 2026 --apply
 */

const path = require('path');
const mongoose = require('mongoose');
require('dotenv').config({ path: path.join(__dirname, '../.env') });

const Employee = require('../employees/model/Employee');
const LeaveRegisterYear = require('../leaves/model/LeaveRegisterYear');
const leaveRegisterYearMonthlyApplyService = require('../leaves/services/leaveRegisterYearMonthlyApplyService');

function parseArg(name) {
  const key = String(name).replace(/^--/, '');
  const idx = process.argv.findIndex((a) => a === `--${key}`);
  if (idx >= 0 && process.argv[idx + 1] != null && !String(process.argv[idx + 1]).startsWith('--')) {
    return process.argv[idx + 1];
  }
  return undefined;
}

function hasFlag(name) {
  return process.argv.includes(`--${name}`);
}

function round2(value) {
  const n = Number(value) || 0;
  return Math.round(n * 100) / 100;
}

function sumMonthlyClSchedule(slot) {
  let total = 0;
  for (const tx of slot?.transactions || []) {
    if (String(tx?.leaveType || '').toUpperCase() !== 'CL') continue;
    if (String(tx?.transactionType || '').toUpperCase() !== 'CREDIT') continue;
    if (String(tx?.autoGeneratedType || '') !== 'MONTHLY_CL_SCHEDULE') continue;
    total += Math.max(0, Number(tx?.days) || 0);
  }
  return round2(total);
}

function sortSlots(months) {
  return (months || [])
    .map((slot, idx) => ({
      slot,
      idx,
      time: new Date(slot?.payPeriodStart || slot?.payPeriodEnd || 0).getTime(),
    }))
    .sort((a, b) => a.time - b.time);
}

function targetPosition(ordered, untilMonth, untilYear) {
  return ordered.findIndex(
    ({ slot }) =>
      Number(slot.payrollCycleMonth) === Number(untilMonth) &&
      Number(slot.payrollCycleYear) === Number(untilYear)
  );
}

function reconcileDoc(doc, targetIdx) {
  const ordered = sortSlots(doc.months);
  const changes = [];
  for (let p = 0; p <= targetIdx; p++) {
    const { slot, idx } = ordered[p] || {};
    if (!slot) continue;
    const scheduledTx = sumMonthlyClSchedule(slot);
    if (scheduledTx <= 0) continue;
    const transferIn = round2(Number(slot.poolCarryForwardIn?.cl) || 0);
    const expected = round2(scheduledTx + transferIn);
    const before = round2(Number(slot.clCredits) || 0);
    if (before === expected) continue;
    slot.clCredits = expected;
    changes.push({
      payroll: `${slot.payrollCycleMonth}/${slot.payrollCycleYear}`,
      label: slot.label,
      before,
      after: expected,
      scheduledTx,
      transferIn,
      idx,
      anchor: slot.payPeriodStart || slot.payPeriodEnd || null,
    });
  }
  return changes;
}

async function main() {
  const all = hasFlag('all');
  const apply = hasFlag('apply');
  const empNo = parseArg('empNo');
  const financialYear = String(parseArg('financialYear') || '2026').trim();
  const untilMonth = Number(parseArg('untilMonth') || parseArg('month') || '5');
  const untilYear = Number(parseArg('untilYear') || parseArg('year') || '2026');

  if (!process.env.MONGODB_URI) throw new Error('MONGODB_URI missing');
  if (!all && !empNo) throw new Error('Missing --empNo or --all');

  await mongoose.connect(process.env.MONGODB_URI);

  const query = { financialYear };
  if (!all) {
    const emp = await Employee.findOne({
      $or: [{ emp_no: String(empNo) }, { emp_no: Number(empNo) }],
    })
      .select('_id emp_no employee_name')
      .lean();
    if (!emp) {
      console.log(JSON.stringify({ ok: false, error: 'Employee not found', empNo }, null, 2));
      await mongoose.disconnect();
      return;
    }
    query.employeeId = emp._id;
  }

  const docs = await LeaveRegisterYear.find(query).sort({ empNo: 1 });
  const summary = {
    ok: true,
    dryRun: !apply,
    message: apply
      ? 'Applied scheduled CL slot reconciliation.'
      : 'Dry run only. Re-run with --apply to persist scheduled CL slot reconciliation.',
    financialYear,
    targetThrough: { month: untilMonth, year: untilYear },
    scanned: docs.length,
    changedDocs: 0,
    changedSlots: 0,
    failed: 0,
    rows: [],
    errors: [],
  };

  for (const doc of docs) {
    try {
      const ordered = sortSlots(doc.months);
      const targetIdx = targetPosition(ordered, untilMonth, untilYear);
      if (targetIdx < 0) continue;
      const changes = reconcileDoc(doc, targetIdx);
      if (!changes.length) continue;
      summary.changedDocs++;
      summary.changedSlots += changes.length;
      summary.rows.push({
        empNo: doc.empNo,
        employeeName: doc.employeeName,
        employeeId: String(doc.employeeId),
        changes: changes.map(({ idx, anchor, ...row }) => row),
      });
      if (apply) {
        doc.markModified('months');
        await doc.save();
        for (const change of changes) {
          if (!change.anchor) continue;
          await leaveRegisterYearMonthlyApplyService.syncStoredMonthApplyFieldsForEmployeeDate(
            doc.employeeId,
            change.anchor
          );
        }
      }
    } catch (error) {
      summary.failed++;
      summary.errors.push({
        empNo: doc.empNo,
        employeeId: String(doc.employeeId),
        error: error?.message || String(error),
      });
    }
  }

  console.log(JSON.stringify(summary, null, 2));
  await mongoose.disconnect();
}

main().catch(async (error) => {
  console.error(error?.stack || error?.message || error);
  try {
    await mongoose.disconnect();
  } catch {}
  process.exit(1);
});
