/**
 * One-time cleanup: Reset CL leave register so ONLY scheduled CL credits remain.
 *
 * What it does (MongoDB):
 * 1) LeaveRegisterYear (collection: leave_register_years):
 *    - Keeps only scheduled CL CREDIT movements (MONTHLY_CL_SCHEDULE) in months[].transactions.
 *    - Removes ALL other CL credits/debits (applications, transfers, carry, adjustments, etc.).
 *    - Clears CL carry-forward pools and all monthly apply / used cached aggregates on each slot.
 *    - Removes CL rows from yearlyTransactions.
 *    - Sets slot.clCredits = sum(scheduled CL tx days).
 *
 * 2) LeaveRegister (collection: leave_register) — legacy flat ledger:
 *    - Deletes ALL CL rows except scheduled CL CREDIT (MONTHLY_CL_SCHEDULE).
 *
 * 3) Snapshots:
 *    - Zeros CL used/locked fields in leave_register_monthly_snapshots.
 *
 * 4) Recalculates CL balances on LeaveRegisterYear + Employee.casualLeaves.
 *
 * Does NOT touch leave applications (Leave collection).
 *
 * Safety:
 * - DRY RUN by default. To apply: `--apply` OR DRY_RUN=false.
 *
 * Usage:
 *   cd backend
 *   node scripts/reset_cl_register_keep_only_scheduled.js
 *   node scripts/reset_cl_register_keep_only_scheduled.js --apply
 *
 * Optional:
 *   --financialYear "2025-2026"
 *   --empNo 2202
 *   --limit 50
 */
const path = require('path');
const mongoose = require('mongoose');
require('dotenv').config({ path: path.join(__dirname, '../.env') });

const Employee = require('../employees/model/Employee');
const LeaveRegister = require('../leaves/model/LeaveRegister');
const LeaveRegisterYear = require('../leaves/model/LeaveRegisterYear');
const leaveRegisterYearLedgerService = require('../leaves/services/leaveRegisterYearLedgerService');

function parseArg(name) {
  const key = String(name).replace(/^--/, '');
  const idx = process.argv.findIndex((a) => a === `--${key}`);
  if (idx >= 0 && process.argv[idx + 1] != null && !String(process.argv[idx + 1]).startsWith('--')) {
    return process.argv[idx + 1];
  }
  return undefined;
}

function hasFlag(name) {
  return process.argv.includes(`--${name}`);
}

function parseBool(v, defaultValue = true) {
  if (v == null) return defaultValue;
  const s = String(v).trim().toLowerCase();
  if (['1', 'true', 'yes', 'y', 'on'].includes(s)) return true;
  if (['0', 'false', 'no', 'n', 'off'].includes(s)) return false;
  return defaultValue;
}

function round2(value) {
  const n = Number(value) || 0;
  return Math.round(n * 100) / 100;
}

function isScheduledClTx(tx) {
  if (!tx) return false;
  return (
    String(tx.leaveType || '').toUpperCase() === 'CL' &&
    String(tx.transactionType || '').toUpperCase() === 'CREDIT' &&
    String(tx.autoGeneratedType || '') === 'MONTHLY_CL_SCHEDULE'
  );
}

function sumScheduledCl(slot) {
  let total = 0;
  for (const tx of slot?.transactions || []) {
    if (!isScheduledClTx(tx)) continue;
    total += Math.max(0, Number(tx.days) || 0);
  }
  return Math.round(total * 100) / 100;
}

function maskMongoUri(uri) {
  const s = String(uri || '');
  return s.replace(/(\/\/)([^/:@]+):([^@]+)@/g, '$1$2:***@');
}

function clearSlotClAggregates(slot) {
  let changed = false;

  slot.poolCarryForwardIn = {
    ...(slot.poolCarryForwardIn || {}),
    cl: 0,
  };
  slot.poolCarryForwardOut = {
    ...(slot.poolCarryForwardOut || {}),
    cl: 0,
  };
  slot.poolCarryForwardOutAt = null;
  slot.poolCarryForwardFromLabel = '';
  slot.poolCarryForwardAllocation = null;

  slot.lockedCredits = 0;
  slot.monthlyApplyCeiling = 0;
  slot.monthlyApplyConsumed = 0;
  slot.monthlyApplyLocked = 0;
  slot.monthlyApplyApproved = 0;
  slot.monthlyApplySyncedAt = new Date();

  return changed;
}

async function main() {
  const apply = hasFlag('apply');
  const dryRun = !apply && parseBool(process.env.DRY_RUN, true);

  const financialYear = parseArg('financialYear') || process.env.FINANCIAL_YEAR || null;
  const empNo = parseArg('empNo') || null;
  const limit = Number(parseArg('limit') || process.env.LIMIT || 0);

  const uri =
    process.env.MONGODB_URI ||
    process.env.MONGO_URI ||
    process.env.MONGODB_URL ||
    null;

  if (!uri) throw new Error('Mongo URI not found. Expected MONGODB_URI (backend/.env).');

  console.log(
    JSON.stringify(
      {
        script: 'reset_cl_register_keep_only_scheduled',
        dryRun,
        apply: !dryRun,
        financialYear,
        empNo,
        limit: limit > 0 ? limit : null,
        mongo: maskMongoUri(uri),
      },
      null,
      2
    )
  );

  await mongoose.connect(uri);

  let employeeQuery = {};
  if (empNo) {
    employeeQuery = { $or: [{ emp_no: String(empNo) }, { emp_no: Number(empNo) }] };
  }

  let employees = await Employee.find(employeeQuery)
    .select('_id emp_no employee_name')
    .sort({ emp_no: 1 })
    .lean();

  if (limit > 0) employees = employees.slice(0, limit);

  const yrQuery = {};
  if (financialYear) yrQuery.financialYear = String(financialYear).trim();
  if (empNo && employees.length) {
    yrQuery.employeeId = { $in: employees.map((e) => e._id) };
  } else if (limit > 0 && employees.length) {
    yrQuery.employeeId = { $in: employees.map((e) => e._id) };
  }

  const yearDocs = await LeaveRegisterYear.find(yrQuery);

  const employeeIdSet = new Set([
    ...employees.map((e) => String(e._id)),
    ...yearDocs.map((d) => String(d.employeeId)),
  ]);
  const employeeIds = [...employeeIdSet].map((id) => new mongoose.Types.ObjectId(id));

  if (!yearDocs.length && !employeeIds.length) {
    console.log('No leave register year docs or employees found. Nothing to do.');
    await mongoose.disconnect();
    return;
  }

  let yrDocsChanged = 0;
  let yrSlotsChanged = 0;
  let yrClTxRemoved = 0;
  let yrClYearlyTxRemoved = 0;

  for (const doc of yearDocs) {
    let changed = false;
    let slotsTouched = 0;
    let removedTx = 0;

    for (const slot of doc.months || []) {
      if (!slot) continue;
      let slotChanged = false;

      if (Array.isArray(slot.transactions) && slot.transactions.length > 0) {
        const before = slot.transactions.length;
        const filtered = slot.transactions.filter((tx) => {
          const lt = String(tx?.leaveType || '').toUpperCase();
          if (lt !== 'CL') return true;
          return isScheduledClTx(tx);
        });
        const removed = before - filtered.length;
        if (removed > 0) {
          slot.transactions = filtered;
          removedTx += removed;
          changed = true;
          slotChanged = true;
        }
      }

      clearSlotClAggregates(slot);
      changed = true;
      slotChanged = true;

      const scheduled = sumScheduledCl(slot);
      const beforeClCredits = round2(Number(slot.clCredits) || 0);
      if (beforeClCredits !== scheduled) {
        slot.clCredits = scheduled;
        changed = true;
        slotChanged = true;
      }

      if (slotChanged) slotsTouched++;
    }

    if (Array.isArray(doc.yearlyTransactions) && doc.yearlyTransactions.length > 0) {
      const beforeYt = doc.yearlyTransactions.length;
      doc.yearlyTransactions = doc.yearlyTransactions.filter(
        (tx) => String(tx?.leaveType || '').toUpperCase() !== 'CL'
      );
      const removedYt = beforeYt - doc.yearlyTransactions.length;
      if (removedYt > 0) {
        yrClYearlyTxRemoved += removedYt;
        changed = true;
      }
    }

    const scheduledTotal = round2(
      (doc.months || []).reduce((acc, s) => acc + (Number(s?.clCredits) || 0), 0)
    );

    if (round2(Number(doc.yearlyPolicyClScheduledTotal) || 0) !== scheduledTotal) {
      doc.yearlyPolicyClScheduledTotal = scheduledTotal;
      changed = true;
    }
    if (round2(Number(doc.yearlyClCreditDaysPosted) || 0) !== scheduledTotal) {
      doc.yearlyClCreditDaysPosted = scheduledTotal;
      changed = true;
    }

    if (changed) {
      yrDocsChanged++;
      yrSlotsChanged += slotsTouched;
      yrClTxRemoved += removedTx;
      if (!dryRun) {
        doc.markModified('months');
        doc.markModified('yearlyPolicyClScheduledTotal');
        doc.markModified('yearlyClCreditDaysPosted');
        doc.markModified('yearlyTransactions');
        await doc.save();
      }
    }
  }

  const leaveRegisterDeleteFilter = {
    leaveType: 'CL',
    $nor: [{ transactionType: 'CREDIT', autoGeneratedType: 'MONTHLY_CL_SCHEDULE' }],
  };
  if (empNo || limit > 0) {
    leaveRegisterDeleteFilter.employeeId = { $in: employeeIds };
  }

  let deletedLeaveRegister = 0;
  if (!dryRun) {
    const res = await LeaveRegister.deleteMany(leaveRegisterDeleteFilter);
    deletedLeaveRegister = res?.deletedCount || 0;
  } else {
    deletedLeaveRegister = await LeaveRegister.countDocuments(leaveRegisterDeleteFilter);
  }

  const snapshotFilter = empNo || limit > 0 ? { employeeId: { $in: employeeIds } } : {};
  let snapshotsUpdated = 0;
  if (!dryRun) {
    const res = await mongoose.connection.db.collection('leave_register_monthly_snapshots').updateMany(
      snapshotFilter,
      {
        $set: {
          clUsedThisMonth: 0,
          clPendingThisMonth: 0,
          clLockedThisMonth: 0,
          clAllowedRemaining: 0,
          pendingAllDays: 0,
        },
      }
    );
    snapshotsUpdated = res?.modifiedCount || 0;
  } else {
    snapshotsUpdated = await mongoose.connection.db
      .collection('leave_register_monthly_snapshots')
      .countDocuments({
        ...snapshotFilter,
        $or: [
          { clUsedThisMonth: { $gt: 0 } },
          { clPendingThisMonth: { $gt: 0 } },
          { clLockedThisMonth: { $gt: 0 } },
        ],
      });
  }

  const recalcEmployeeIds = [
    ...new Set(yearDocs.map((d) => String(d.employeeId))),
  ].map((id) => new mongoose.Types.ObjectId(id));

  let recalculated = 0;
  if (!dryRun) {
    for (const eid of recalcEmployeeIds) {
      await leaveRegisterYearLedgerService.recalculateRegisterBalances(eid, 'CL');
      recalculated++;
    }
  }

  console.log(
    JSON.stringify(
      {
        ok: true,
        dryRun,
        employeesMatched: employees.length,
        employeeIdsInScope: employeeIds.length,
        recalcEmployeeIds: recalcEmployeeIds.length,
        leaveRegisterYearDocsScanned: yearDocs.length,
        leaveRegisterYearDocsChanged: yrDocsChanged,
        leaveRegisterYearSlotsTouched: yrSlotsChanged,
        leaveRegisterYearClTxRemoved: yrClTxRemoved,
        leaveRegisterYearClYearlyTxRemoved: yrClYearlyTxRemoved,
        leaveRegisterClRowsDeleted: deletedLeaveRegister,
        monthlySnapshotsUpdated: snapshotsUpdated,
        clBalancesRecalculatedEmployees: recalculated,
        note:
          'CL register only. Keeps MONTHLY_CL_SCHEDULE credits. Does NOT modify leave applications.',
      },
      null,
      2
    )
  );

  await mongoose.disconnect();
}

main().catch(async (error) => {
  console.error('❌ Error:', error?.stack || error?.message || error);
  try {
    await mongoose.disconnect();
  } catch {}
  process.exit(1);
});
