/**
 * Reset wrong EL balances, then re-post accrual from current policy (same as reconcileEarnedLeaveAccrualCredits).
 *
 * Per employee (active, optional department):
 *   1) Remove all auto EL accrual rows (CREDIT + EARNED_LEAVE) from leave register year doc(s).
 *   2) Recalculate EL ledger → syncs Employee.paidLeaves from remaining EL transactions.
 *   3) Compare policy calculateEarnedLeave vs ledger for the given payroll month; fix if needed.
 *
 * Does NOT remove manual EL credits, PAYROLL_USE debits, or other auto types.
 *
 * Usage (from backend/):
 *   node scripts/reset_el_profile_and_reconcile_accrual.js <month 1-12> <year> --dry-run
 *   node scripts/reset_el_profile_and_reconcile_accrual.js 4 2026 --apply
 *   node scripts/reset_el_profile_and_reconcile_accrual.js 4 2026 --dept=Civil --apply
 *   node scripts/reset_el_profile_and_reconcile_accrual.js 4 2026 --apply --force
 *
 * Flags:
 *   --check          report only (same as --dry-run)
 *   --dry-run        no writes
 *   --apply          perform reset + reconcile
 *   --dept=NAME      filter by department name/code (omit = all active)
 *   --force          reconcile even if PAYROLL_USE EL debit exists for that month
 *   --all-fy         strip EARNED_LEAVE auto credits in every FY (default: FY of payroll month only)
 *   --inactive       include inactive employees
 */

const mongoose = require('mongoose');
require('dotenv').config();

require('../departments/model/Department');
const Employee = require('../employees/model/Employee');
const LeaveRegisterYear = require('../leaves/model/LeaveRegisterYear');
const earnedLeaveService = require('../leaves/services/earnedLeaveService');
const leaveRegisterService = require('../leaves/services/leaveRegisterService');
const leaveRegisterYearLedgerService = require('../leaves/services/leaveRegisterYearLedgerService');
const dateCycleService = require('../leaves/services/dateCycleService');
const { resolveDepartmentFromCli } = require('./lib/resolveDepartmentFromCli');

function roundHalf(x) {
  const n = Number(x) || 0;
  if (n <= 0) return 0;
  return Math.round(n * 2) / 2;
}

function parseArgs(argv) {
  const positional = [];
  let deptToken = null;
  let dryRun = true;
  let force = false;
  let allFy = false;
  let includeInactive = false;
  for (const a of argv) {
    if (a === '--apply') dryRun = false;
    else if (a === '--check' || a === '--dry-run') dryRun = true;
    else if (a === '--force') force = true;
    else if (a === '--all-fy') allFy = true;
    else if (a === '--inactive') includeInactive = true;
    else if (a.startsWith('--dept=')) deptToken = a.slice('--dept='.length).trim();
    else if (a.startsWith('-')) throw new Error(`Unknown flag: ${a}`);
    else positional.push(a);
  }
  const month = Number(positional[0]);
  const year = Number(positional[1]);
  if (positional[2] && !deptToken) deptToken = positional[2];
  return { month, year, deptToken, dryRun, force, allFy, includeInactive };
}

function isEarnedLeaveAutoCredit(tx) {
  return (
    tx.leaveType === 'EL' &&
    String(tx.transactionType || '').toUpperCase() === 'CREDIT' &&
    tx.autoGeneratedType === 'EARNED_LEAVE'
  );
}

/**
 * @returns {{ removedRows: number, affectedFys: string[] }}
 */
async function removeEarnedLeaveAutoCreditsForEmployee(employeeId, { financialYear } = {}) {
  const query = { employeeId };
  if (financialYear) query.financialYear = financialYear;
  const docs = await LeaveRegisterYear.find(query);
  let removedRows = 0;
  const affectedFys = new Set();

  for (const doc of docs) {
    let docChanged = false;
    for (let mi = 0; mi < (doc.months || []).length; mi++) {
      const slot = doc.months[mi];
      const txs = slot.transactions || [];
      const keep = [];
      for (const t of txs) {
        if (isEarnedLeaveAutoCredit(t)) {
          removedRows += 1;
          docChanged = true;
        } else {
          keep.push(t);
        }
      }
      if (docChanged) {
        slot.transactions = keep;
        doc.markModified(`months.${mi}.transactions`);
      }
    }
    if (docChanged) {
      affectedFys.add(doc.financialYear);
      await doc.save();
    }
  }

  if (removedRows > 0) {
    await leaveRegisterYearLedgerService.recalculateRegisterBalances(employeeId, 'EL', null);
  }

  return { removedRows, affectedFys: [...affectedFys] };
}

async function main() {
  let opts;
  try {
    opts = parseArgs(process.argv.slice(2));
  } catch (e) {
    console.error(e.message);
    process.exit(1);
  }
  const { month, year, deptToken, dryRun, force, allFy, includeInactive } = opts;
  if (!month || month < 1 || month > 12 || !year) {
    console.error(
      'Usage: node scripts/reset_el_profile_and_reconcile_accrual.js <month> <year> [--dept=name] [--check|--apply] [--force] [--all-fy] [--inactive]'
    );
    process.exit(1);
  }

  const uri = process.env.MONGODB_URI || process.env.MONGO_URI || 'mongodb://localhost:27017/hrms';
  await mongoose.connect(uri);

  let departmentId = null;
  let deptLabel = 'all departments';
  if (deptToken) {
    const d = await resolveDepartmentFromCli(deptToken);
    departmentId = d._id;
    deptLabel = `${d.name}${d.code ? ` (${d.code})` : ''}`;
  }

  const cycleTargetDate = new Date(year, month - 1, 15);
  const cycleInfo = await dateCycleService.getPayrollCycleForDate(cycleTargetDate);
  const cycleStart = cycleInfo.startDate;
  const cycleEnd = cycleInfo.endDate;
  const monthYYYYMM = `${year}-${String(month).padStart(2, '0')}`;
  const fyWrap = await dateCycleService.getFinancialYearForDate(cycleTargetDate);
  const stripFyName = allFy ? null : fyWrap?.name || null;

  console.log(
    `[reset-el] mode=${dryRun ? 'CHECK (dry-run)' : 'APPLY'} payroll=${month}/${year} (${monthYYYYMM}) dept=${deptLabel}`
  );
  console.log(
    `[reset-el] strip auto EARNED_LEAVE credits: ${allFy ? 'all financial years' : `FY "${stripFyName}"`}`
  );

  const empQuery = includeInactive ? {} : { is_active: true };
  if (departmentId) empQuery.department_id = departmentId;

  const summary = {
    scanned: 0,
    hadPaidLeavesBefore: 0,
    autoCreditsRemovedRows: 0,
    employeesStripped: 0,
    profilePaidLeavesAfterRecalc: 0,
    reconcileOk: 0,
    reconcileWouldFix: 0,
    reconcileFixed: 0,
    skippedPayrollLocked: 0,
    errors: [],
  };

  const employees = await Employee.find(empQuery)
    .select('_id emp_no employee_name paidLeaves department_id')
    .sort({ emp_no: 1 })
    .lean();

  console.log(`[reset-el] Employees in scope: ${employees.length}\n`);

  for (const emp of employees) {
    summary.scanned += 1;
    const paidBefore = Math.max(0, Number(emp.paidLeaves) || 0);
    if (paidBefore > 0) summary.hadPaidLeavesBefore += 1;

    try {
      let removedRows = 0;
      let paidAfterStrip = paidBefore;

      if (!dryRun) {
        const strip = await removeEarnedLeaveAutoCreditsForEmployee(emp._id, {
          financialYear: stripFyName,
        });
        removedRows = strip.removedRows;
        if (removedRows > 0) summary.employeesStripped += 1;
        summary.autoCreditsRemovedRows += removedRows;

        const fresh = await Employee.findById(emp._id).select('paidLeaves').lean();
        paidAfterStrip = Math.max(0, Number(fresh?.paidLeaves) || 0);
      } else {
        const q = { employeeId: emp._id };
        if (stripFyName) q.financialYear = stripFyName;
        const docs = await LeaveRegisterYear.find(q).lean();
        for (const doc of docs) {
          for (const slot of doc.months || []) {
            for (const t of slot.transactions || []) {
              if (isEarnedLeaveAutoCredit(t)) removedRows += 1;
            }
          }
        }
        if (removedRows > 0) summary.employeesStripped += 1;
        summary.autoCreditsRemovedRows += removedRows;
        paidAfterStrip = paidBefore;
      }

      if (paidAfterStrip > 0) summary.profilePaidLeavesAfterRecalc += 1;

      if (!force) {
        const payrollDebit = await leaveRegisterYearLedgerService.findExistingPayrollElDebitForPayrollMonth(
          emp._id,
          monthYYYYMM
        );
        if (payrollDebit) {
          summary.skippedPayrollLocked += 1;
          if (removedRows > 0 || paidBefore > 0) {
            console.log(
              `[reset-el] ${emp.emp_no}: stripped ${removedRows} auto row(s), paidLeaves=${paidAfterStrip} — skipped reconcile (PAYROLL_USE for ${monthYYYYMM}; use --force)`
            );
          }
          continue;
        }
      }

      const calc = await earnedLeaveService.calculateEarnedLeave(emp._id, month, year, cycleStart, cycleEnd);
      const expected =
        calc.eligible && Number(calc.elEarned) > 0 ? roundHalf(Number(calc.elEarned)) : 0;

      const { total: actual, count: autoCreditCount } =
        await leaveRegisterYearLedgerService.getEarnedLeaveAutoCreditTotalForPayrollCycle(
          emp._id,
          month,
          year
        );

      const shapeOk =
        expected === actual && (expected === 0 ? autoCreditCount === 0 : autoCreditCount === 1);

      if (shapeOk) {
        summary.reconcileOk += 1;
        if (removedRows > 0 || paidBefore !== paidAfterStrip) {
          console.log(
            `[reset-el] ${emp.emp_no} ${emp.employee_name || ''}: stripped=${removedRows} paidLeaves ${paidBefore}→${paidAfterStrip} reconcile OK (expected=${expected})`
          );
        }
        continue;
      }

      summary.reconcileWouldFix += 1;
      console.log(
        `[reset-el] ${emp.emp_no} ${emp.employee_name || ''}: stripped=${removedRows} paidLeaves ${paidBefore}→${paidAfterStrip} reconcile expected=${expected} actual=${actual} rows=${autoCreditCount}${dryRun ? ' (would fix)' : ''}`
      );

      if (dryRun) continue;

      await leaveRegisterYearLedgerService.removeEarnedLeaveAutoCreditsForPayrollCycle(emp._id, month, year);
      if (expected > 0) {
        await leaveRegisterService.addEarnedLeaveCredit(
          emp._id,
          expected,
          month,
          year,
          calc.calculationBreakdown,
          cycleEnd
        );
      }
      summary.reconcileFixed += 1;
    } catch (err) {
      summary.errors.push({ empNo: emp.emp_no, error: err.message });
      console.error(`[reset-el] ${emp.emp_no}: ${err.message}`);
    }
  }

  console.log('\n[reset-el] Summary:', JSON.stringify(summary, null, 2));
  if (dryRun && summary.reconcileWouldFix > 0) {
    console.log('\nTo apply: node scripts/reset_el_profile_and_reconcile_accrual.js', month, year, deptToken ? `--dept=${deptToken}` : '', '--apply');
  }
  await mongoose.disconnect();
}

main().catch(async (e) => {
  console.error('[reset-el] Failed:', e?.message || e);
  try {
    await mongoose.disconnect();
  } catch {}
  process.exit(1);
});
