/**
 * Scan ALL employees with a LeaveRegisterYear for FY: display transfer chain vs raw ledger mismatches.
 *
 * Usage:
 *   node scripts/scan_all_transfer_display_audit.js --financialYear 2026
 *   node scripts/scan_all_transfer_display_audit.js --financialYear 2026 --untilMonth 5
 */

const path = require('path');
const mongoose = require('mongoose');
require('dotenv').config({ path: path.join(__dirname, '../.env') });

require('../departments/model/Designation');
require('../departments/model/Department');
require('../departments/model/Division');

const LeaveRegisterYear = require('../leaves/model/LeaveRegisterYear');
const LeavePolicySettings = require('../settings/model/LeavePolicySettings');
const {
  allocateLockedByPriorityForSlot,
  isPayrollPeriodEndedOnOrBeforeAsOf,
} = require('../leaves/services/leaveRegisterYearService');

const LEAVE_TYPES = ['CL', 'CCL', 'EL'];
const TRANSFER_OUT_PREFIX = 'MONTHLY_POOL_TRANSFER_OUT_';
const TRANSFER_IN_PREFIX = 'MONTHLY_POOL_TRANSFER_IN_';

function parseArg(name) {
  const key = String(name).replace(/^--/, '');
  const idx = process.argv.findIndex((a) => a === `--${key}`);
  if (idx >= 0 && process.argv[idx + 1] != null && !String(process.argv[idx + 1]).startsWith('--')) {
    return process.argv[idx + 1];
  }
  return undefined;
}

function roundHalf(v) {
  const n = Number(v) || 0;
  if (n <= 0) return 0;
  return Math.round(n * 2) / 2;
}

function sortSlotRefs(months) {
  return (months || [])
    .map((slot, idx) => ({ idx, slot, time: new Date(slot?.payPeriodStart || slot?.payPeriodEnd || 0).getTime() }))
    .sort((a, b) => a.time - b.time);
}

function monthKey(slot) {
  return `${Number(slot?.payrollCycleMonth)}/${Number(slot?.payrollCycleYear)}`;
}

function transferAutoType(direction, leaveType) {
  return `${direction === 'out' ? TRANSFER_OUT_PREFIX : TRANSFER_IN_PREFIX}${leaveType}`;
}

function isTransferTx(tx) {
  const autoType = String(tx?.autoGeneratedType || '');
  return autoType.startsWith(TRANSFER_OUT_PREFIX) || autoType.startsWith(TRANSFER_IN_PREFIX);
}

function isReversalCredit(tx) {
  return (
    String(tx?.transactionType || '').toUpperCase() === 'CREDIT' &&
    String(tx?.reason || '').includes('Leave Application Cancelled/Reversed')
  );
}

function sumTransfer(slot, direction, leaveType) {
  const expected = transferAutoType(direction, leaveType);
  return roundHalf(
    (slot?.transactions || [])
      .filter((tx) => String(tx?.autoGeneratedType || '') === expected)
      .reduce((sum, tx) => sum + Math.max(0, Number(tx?.days) || 0), 0)
  );
}

function netUsedDaysForType(slot, leaveType) {
  const lt = String(leaveType || '').toUpperCase();
  let debits = 0;
  let reversalCredits = 0;
  for (const tx of slot?.transactions || []) {
    if (String(tx?.leaveType || '').toUpperCase() !== lt) continue;
    if (isTransferTx(tx)) continue;
    const txType = String(tx?.transactionType || '').toUpperCase();
    const days = Math.max(0, Number(tx?.days) || 0);
    if (txType === 'DEBIT') debits += days;
    if (isReversalCredit(tx)) reversalCredits += days;
  }
  return roundHalf(Math.max(0, debits - reversalCredits));
}

function resolveRollFlags(policy) {
  const capCfg = policy?.monthlyLeaveApplicationCap || {};
  const includeEL = !!capCfg.includeEL;
  const elPaidInPayroll = policy?.earnedLeave?.useAsPaidInPayroll !== false;
  const elInPool = !!policy?.earnedLeave?.enabled && includeEL && !elPaidInPayroll;
  return {
    CL: policy?.carryForward?.casualLeave?.carryMonthlyClCreditToNextPayrollMonth !== false,
    CCL: policy?.carryForward?.compensatoryOff?.carryMonthlyPoolToNextPayrollMonth !== false,
    EL: elInPool && policy?.carryForward?.earnedLeave?.carryMonthlyPoolToNextPayrollMonth !== false,
    elInPool,
  };
}

function computeCarry(slot, rollFlags) {
  const credits = {
    CL: roundHalf(Number(slot?.clCredits) || 0),
    CCL: roundHalf(Number(slot?.compensatoryOffs) || 0),
    EL: rollFlags.elInPool ? roundHalf(Number(slot?.elCredits) || 0) : 0,
  };
  const usedCl = netUsedDaysForType(slot, 'CL');
  const usedCcl = netUsedDaysForType(slot, 'CCL');
  const usedEl = netUsedDaysForType(slot, 'EL');
  const periodEnded =
    slot?.payPeriodEnd && isPayrollPeriodEndedOnOrBeforeAsOf(slot.payPeriodEnd, new Date());
  const slotForLock =
    periodEnded && Number(slot?.monthlyApplyLocked) > 0
      ? { ...slot, monthlyApplyLocked: 0 }
      : slot;
  const locked = allocateLockedByPriorityForSlot(
    slotForLock,
    { cl: credits.CL, ccl: credits.CCL, el: credits.EL },
    { cl: usedCl, ccl: usedCcl, el: usedEl },
    rollFlags.elInPool
  );
  return {
    credits,
    used: { CL: usedCl, CCL: usedCcl, EL: usedEl },
    locked,
    carry: {
      CL: rollFlags.CL ? roundHalf(Math.max(0, credits.CL - usedCl - locked.cl)) : 0,
      CCL: rollFlags.CCL ? roundHalf(Math.max(0, credits.CCL - usedCcl - locked.ccl)) : 0,
      EL: rollFlags.EL ? roundHalf(Math.max(0, credits.EL - usedEl - locked.el)) : 0,
    },
    poolOut: {
      CL: roundHalf(Number(slot?.poolCarryForwardOut?.cl) || 0),
      CCL: roundHalf(Number(slot?.poolCarryForwardOut?.ccl) || 0),
      EL: roundHalf(Number(slot?.poolCarryForwardOut?.el) || 0),
    },
    poolIn: {
      CL: roundHalf(Number(slot?.poolCarryForwardIn?.cl) || 0),
      CCL: roundHalf(Number(slot?.poolCarryForwardIn?.ccl) || 0),
      EL: roundHalf(Number(slot?.poolCarryForwardIn?.el) || 0),
    },
  };
}

function reconcileUsedFromAllocation(slot, leaveType) {
  const alloc = slot?.poolCarryForwardAllocation;
  if (!alloc || typeof alloc !== 'object') return null;
  const key = leaveType === 'CL' ? 'CL' : leaveType === 'CCL' ? 'CCL' : 'EL';
  const u = alloc.actualOrLedgerUsed;
  if (!u || typeof u !== 'object') return null;
  const v = u[key];
  return v != null && Number.isFinite(Number(v)) ? roundHalf(Number(v)) : null;
}

function auditEmployee(doc, rollFlags, untilMonth) {
  const ordered = sortSlotRefs(doc.months);
  const empNo = doc.empNo;
  const name = doc.employeeName;
  const issues = [];

  for (let i = 0; i < ordered.length; i++) {
    const slot = ordered[i].slot;
    const mk = monthKey(slot);
    const m = Number(slot?.payrollCycleMonth);
    if (untilMonth != null && m > untilMonth) continue;

    const periodEnded =
      slot?.payPeriodEnd && isPayrollPeriodEndedOnOrBeforeAsOf(slot.payPeriodEnd, new Date());
    if (!periodEnded) continue;

    const c = computeCarry(slot, rollFlags);

    for (const lt of LEAVE_TYPES) {
      const ledgerUsed = c.used[lt];
      const reconcileUsed = reconcileUsedFromAllocation(slot, lt);
      const poolOut = c.poolOut[lt];
      const poolIn = c.poolIn[lt];
      const postedOut = sumTransfer(slot, 'out', lt);
      const postedIn = sumTransfer(slot, 'in', lt);
      const expectedCarryFromLedger = c.carry[lt];

      // What the UI shows (same source as API): poolCarryForwardIn/Out
      if (reconcileUsed != null && ledgerUsed !== reconcileUsed) {
        issues.push({
          empNo,
          name,
          month: mk,
          category: 'display_vs_ledger_used',
          leaveType: lt,
          ledgerUsed,
          displayUsed: reconcileUsed,
          poolOut,
          note: 'Grid Used follows reconcile/approved; transaction list sums all debits',
        });
      } else if (reconcileUsed == null && ledgerUsed !== expectedCarryFromLedger && poolOut !== ledgerUsed) {
        const impliedDisplayUsed = roundHalf(c.credits[lt] - poolOut);
        if (ledgerUsed !== impliedDisplayUsed && ledgerUsed > impliedDisplayUsed) {
          issues.push({
            empNo,
            name,
            month: mk,
            category: 'display_vs_ledger_used',
            leaveType: lt,
            ledgerUsed,
            displayUsed: impliedDisplayUsed,
            poolOut,
            note: 'Inferred display used from pool; ledger debits higher (stale/rejected debits likely)',
          });
        }
      }

      if (postedOut !== poolOut) {
        issues.push({
          empNo,
          name,
          month: mk,
          category: 'pool_out_vs_posted_txn',
          leaveType: lt,
          poolOut,
          postedOut,
        });
      }

      if (postedIn !== poolIn) {
        issues.push({
          empNo,
          name,
          month: mk,
          category: 'pool_in_vs_posted_txn',
          leaveType: lt,
          poolIn,
          postedIn,
        });
      }

      if (i < ordered.length - 1 && poolOut !== expectedCarryFromLedger && ledgerUsed > 0) {
        issues.push({
          empNo,
          name,
          month: mk,
          category: 'transfer_out_vs_all_debits',
          leaveType: lt,
          postedOut: poolOut,
          expectedIfAllDebitsCounted: expectedCarryFromLedger,
          ledgerUsed,
          credits: c.credits[lt],
        });
      }
    }

    if (i > 0) {
      const prev = ordered[i - 1].slot;
      const prevEnded =
        prev?.payPeriodEnd && isPayrollPeriodEndedOnOrBeforeAsOf(prev.payPeriodEnd, new Date());
      if (!prevEnded) continue;
      const prevMk = monthKey(prev);
      const prevC = computeCarry(prev, rollFlags);

      for (const lt of LEAVE_TYPES) {
        const prevOut = prevC.poolOut[lt];
        const curIn = c.poolIn[lt];
        const prevReconcileUsed = reconcileUsedFromAllocation(prev, lt);
        const prevDisplayCarry =
          prevReconcileUsed != null
            ? roundHalf(Math.max(0, prevC.credits[lt] - prevReconcileUsed - (prevC.locked[lt === 'CL' ? 'cl' : lt === 'CCL' ? 'ccl' : 'el'] || 0)))
            : prevOut;

        if (prevOut !== curIn) {
          issues.push({
            empNo,
            name,
            month: mk,
            category: 'display_chain_break',
            leaveType: lt,
            fromMonth: prevMk,
            priorTransferOut: prevOut,
            currentCarriedIn: curIn,
            note: 'Screen Carried in should equal prior month Transfer out',
          });
        }

        if (curIn !== prevDisplayCarry && prevReconcileUsed != null) {
          issues.push({
            empNo,
            name,
            month: mk,
            category: 'carried_in_vs_prior_reconcile_carry',
            leaveType: lt,
            fromMonth: prevMk,
            carriedIn: curIn,
            priorReconcileCarry: prevDisplayCarry,
            priorLedgerUsed: prevC.used[lt],
            priorReconcileUsed,
          });
        } else if (curIn !== prevC.carry[lt] && prevC.used[lt] > 0) {
          issues.push({
            empNo,
            name,
            month: mk,
            category: 'carried_in_vs_prior_ledger_carry',
            leaveType: lt,
            fromMonth: prevMk,
            carriedIn: curIn,
            priorLedgerCarry: prevC.carry[lt],
            priorLedgerUsed: prevC.used[lt],
            note: 'Only if counting every debit; display/reconcile may differ',
          });
        }
      }
    }
  }

  return { empNo, name, issueCount: issues.length, issues };
}

function aggregateByMonth(employeeResults) {
  const byMonth = {};
  for (const er of employeeResults) {
    for (const iss of er.issues) {
      const mk = iss.month;
      if (!byMonth[mk]) {
        byMonth[mk] = {
          display_chain_break: new Set(),
          display_vs_ledger_used: new Set(),
          carried_in_vs_prior_reconcile_carry: new Set(),
          carried_in_vs_prior_ledger_carry: new Set(),
          transfer_out_vs_all_debits: new Set(),
          pool_out_vs_posted_txn: new Set(),
          pool_in_vs_posted_txn: new Set(),
        };
      }
      const cat = iss.category;
      if (byMonth[mk][cat]) byMonth[mk][cat].add(iss.empNo);
    }
  }
  const summary = {};
  for (const [mk, cats] of Object.entries(byMonth)) {
    summary[mk] = {};
    for (const [cat, set] of Object.entries(cats)) {
      summary[mk][cat] = { count: set.size, empNos: [...set].sort((a, b) => String(a).localeCompare(String(b), undefined, { numeric: true })) };
    }
  }
  return summary;
}

async function main() {
  const financialYear = String(parseArg('financialYear') || '2026').trim();
  const untilMonth = parseArg('untilMonth') != null ? Number(parseArg('untilMonth')) : 5;
  const maxList = Number(parseArg('maxListPerCategory') || 30);

  if (!process.env.MONGODB_URI) {
    console.error('MONGODB_URI missing');
    process.exit(1);
  }

  await mongoose.connect(process.env.MONGODB_URI);
  const policy = await LeavePolicySettings.getSettings().catch(() => ({}));
  const rollFlags = resolveRollFlags(policy);

  const docs = await LeaveRegisterYear.find({ financialYear })
    .select('empNo employeeName months')
    .sort({ empNo: 1 })
    .lean();

  const employeeResults = [];
  for (const doc of docs) {
    const r = auditEmployee(doc, rollFlags, untilMonth);
    if (r.issueCount > 0) employeeResults.push(r);
  }

  const byMonth = aggregateByMonth(employeeResults);

  const countByCategory = {};
  for (const er of employeeResults) {
    for (const iss of er.issues) {
      countByCategory[iss.category] = (countByCategory[iss.category] || 0) + 1;
    }
  }

  const employeesWithDisplayChainBreak = new Set();
  const employeesWithDisplayVsLedger = new Set();
  for (const er of employeeResults) {
    for (const iss of er.issues) {
      if (iss.category === 'display_chain_break') employeesWithDisplayChainBreak.add(iss.empNo);
      if (iss.category === 'display_vs_ledger_used') employeesWithDisplayVsLedger.add(iss.empNo);
    }
  }

  const uniqueEmployeesWithIssues = [
    ...new Set(employeeResults.map((r) => r.empNo)),
  ].sort((a, b) => String(a).localeCompare(String(b), undefined, { numeric: true }));

  const sampleIssues = {};
  for (const cat of Object.keys(countByCategory)) {
    const samples = [];
    for (const er of employeeResults) {
      for (const iss of er.issues) {
        if (iss.category === cat) samples.push(iss);
      }
    }
    sampleIssues[cat] = samples.slice(0, maxList);
  }

  const report = {
        database: process.env.MONGODB_URI?.replace(/\/\/[^@]+@/, '//***@'),
        financialYear,
        endedMonthsThrough: untilMonth,
        rollFlags,
        scannedEmployees: docs.length,
        employeesWithAnyIssue: employeeResults.length,
        employeesClean: docs.length - employeeResults.length,
        employeesWithDisplayChainBreak: employeesWithDisplayChainBreak.size,
        employeesWithDisplayVsLedgerUsed: employeesWithDisplayVsLedger.size,
        uniqueEmployeesWithIssues,
        issueCountsByCategory: countByCategory,
        issuesByMonth: byMonth,
        sampleIssues,
        explanation: {
          display_chain_break:
            'Real bug: prior month Transfer (out) ≠ this month Carried in — screen chain broken.',
          display_vs_ledger_used:
            'Confusing not wrong: grid Used (approved/reconcile) ≠ sum of all debit lines in transactions.',
          carried_in_vs_prior_reconcile_carry:
            'Usually OK after reconcile: Carried in matches reconcile carry, not raw ledger debits.',
          carried_in_vs_prior_ledger_carry:
            'Same as above when prior month has extra/rejected debits still in ledger.',
          transfer_out_vs_all_debits:
            'Transfer out posted for reconcile Used; ledger still has extra debits.',
          pool_out_vs_posted_txn: 'poolCarryForwardOut field ≠ transfer transaction rows.',
          pool_in_vs_posted_txn: 'poolCarryForwardIn field ≠ transfer-in transaction rows.',
        },
      };

  const outPath = path.join(__dirname, '_scan_all_transfer_audit.json');
  require('fs').writeFileSync(outPath, JSON.stringify(report, null, 2), 'utf8');
  console.log(JSON.stringify(report, null, 2));

  await mongoose.disconnect();
}

main().catch(async (err) => {
  console.error(err?.stack || err);
  try {
    await mongoose.disconnect();
  } catch {}
  process.exit(1);
});
