/**
 * Set Casual Leave balance to 12 for every employee.
 * Creates one ADJUSTMENT transaction per employee in the leave register;
 * the register service updates Employee.casualLeaves automatically.
 *
 * Usage: node scripts/set_cl_12_for_all_employees.js
 * Run from backend directory.
 */

const mongoose = require('mongoose');
require('dotenv').config({ path: require('path').resolve(__dirname, '../.env') });

const DEFAULT_CL_BALANCE = 12;

async function setCL12ForAll() {
    try {
        console.log('Connecting to MongoDB...');
        await mongoose.connect(process.env.MONGO_URI || 'mongodb://localhost:27017/hrms');
        console.log('Connected to MongoDB');

        const Employee = require('../employees/model/Employee');
        const leaveRegisterService = require('../leaves/services/leaveRegisterService');

        const employees = await Employee.find({}).lean();
        console.log(`Found ${employees.length} employee(s).`);

        let done = 0;
        let errCount = 0;
        for (const emp of employees) {
            try {
                await leaveRegisterService.addTransaction({
                    employeeId: emp._id,
                    empNo: emp.emp_no,
                    employeeName: emp.employee_name || 'N/A',
                    designation: 'N/A',
                    department: 'N/A',
                    divisionId: emp.division_id,
                    departmentId: emp.department_id,
                    dateOfJoining: emp.doj || new Date(),
                    employmentStatus: emp.is_active ? 'active' : 'inactive',
                    leaveType: 'CL',
                    transactionType: 'ADJUSTMENT',
                    startDate: new Date(),
                    endDate: new Date(),
                    days: DEFAULT_CL_BALANCE,
                    reason: 'Initial CL balance set to 12 (script)',
                    status: 'APPROVED',
                    autoGenerated: false,
                });
                done++;
                if (done % 50 === 0) console.log(`  ... ${done} done`);
            } catch (e) {
                console.error(`  Error for ${emp.emp_no}:`, e.message);
                errCount++;
            }
        }

        console.log(`Done. Set CL to ${DEFAULT_CL_BALANCE} for ${done} employee(s). Errors: ${errCount}.`);
    } catch (error) {
        console.error('Fatal error:', error);
        process.exit(1);
    } finally {
        await mongoose.disconnect();
        console.log('Disconnected from MongoDB');
        process.exit(0);
    }
}

setCL12ForAll();
