/**
 * Integration simulation: CCL register reconciliation, audit, sample employees.
 *
 * Usage: node scripts/test_ccl_register_reconciliation_simulation.js [--fy 2026]
 */
const mongoose = require('mongoose');
const path = require('path');
const fs = require('fs');
require('dotenv').config({ path: path.join(__dirname, '../.env') });

require('../departments/model/Designation');
require('../departments/model/Department');
require('../departments/model/Division');

const LeaveRegisterYear = require('../leaves/model/LeaveRegisterYear');
const Employee = require('../employees/model/Employee');
const leaveRegisterYearLedgerService = require('../leaves/services/leaveRegisterYearLedgerService');
const monthlyTransferReconciliationService = require('../leaves/services/monthlyTransferReconciliationService');
const leaveRegisterService = require('../leaves/services/leaveRegisterService');
const { netUsedDaysForType } = require('../leaves/services/monthlyTransferReconciliationService');

const FY = (() => {
  const i = process.argv.indexOf('--fy');
  return i >= 0 && process.argv[i + 1] ? String(process.argv[i + 1]).trim() : '2026';
})();

const SAMPLE_EMP_NOS = ['1890', '5008', '2017', '1954', '2295', '155'];

function round2(v) {
  return Math.round((Number(v) || 0) * 100) / 100;
}

function sumCclDebits(slot) {
  let d = 0;
  for (const tx of slot?.transactions || []) {
    if (String(tx.leaveType || '').toUpperCase() !== 'CCL') continue;
    if (String(tx.transactionType || '').toUpperCase() !== 'DEBIT') continue;
    if (String(tx.autoGeneratedType || '').startsWith('MONTHLY_POOL_TRANSFER_OUT_')) continue;
    d += Math.max(0, Number(tx.days) || 0);
  }
  return round2(d);
}

function lastClosingCcl(slot) {
  let last = null;
  for (const tx of slot?.transactions || []) {
    if (String(tx.leaveType || '').toUpperCase() !== 'CCL') continue;
    const c = Number(tx.closingBalance);
    if (Number.isFinite(c)) last = c;
  }
  return last;
}

function isCclReversalCredit(tx) {
  return (
    String(tx?.leaveType || '').toUpperCase() === 'CCL' &&
    String(tx?.transactionType || '').toUpperCase() === 'CREDIT' &&
    String(tx?.reason || '').includes('Leave Application Cancelled/Reversed')
  );
}

async function auditCclReversalPairs(fy) {
  const docs = await LeaveRegisterYear.find({ financialYear: fy }).lean();
  let cclMonthsWithReversalAndDebits = 0;
  let employeesWithCclMismatch = 0;
  const mismatchSamples = [];

  for (const doc of docs) {
    for (const slot of doc.months || []) {
      const hasRev = (slot.transactions || []).some(isCclReversalCredit);
      const debits = sumCclDebits(slot);
      const netUsed = netUsedDaysForType(slot, 'CCL');
      if (hasRev && debits > 0) cclMonthsWithReversalAndDebits += 1;
      const pool = round2(Number(slot.compensatoryOffs) || 0);
      const xferOut = round2(Number(slot.poolCarryForwardOut?.ccl) || 0);
      const impliedBal = round2(pool - debits - xferOut);
      const closing = lastClosingCcl(slot);
      if (closing != null && Math.abs(closing - impliedBal) > 0.01 && debits > 0) {
        employeesWithCclMismatch += 1;
        if (mismatchSamples.length < 5) {
          mismatchSamples.push({
            empNo: doc.empNo,
            month: `${slot.payrollCycleMonth}/${slot.payrollCycleYear}`,
            pool,
            debits,
            xferOut,
            closing,
            impliedBal,
          });
        }
      }
    }
  }
  return {
    docsScanned: docs.length,
    cclMonthsWithReversalAndDebits,
    employeesWithCclMonthPoolClosingMismatch: employeesWithCclMismatch,
    mismatchSamples,
  };
}

async function employeeSnapshot(empNo, fy) {
  const emp = await Employee.findOne({ emp_no: empNo }).select('_id emp_no compensatoryOffs').lean();
  if (!emp) return { empNo, ok: false, error: 'not_found' };

  const yDoc = await LeaveRegisterYear.findOne({ employeeId: emp._id, financialYear: fy }).lean();
  const ledgerBal = await leaveRegisterYearLedgerService.getCurrentBalance(emp._id, 'CCL', new Date());

  let may = null;
  if (yDoc?.months) {
    const slot = yDoc.months.find(
      (m) => Number(m.payrollCycleMonth) === 5 && Number(m.payrollCycleYear) === 2026
    );
    if (slot) {
      may = {
        pool: round2(slot.compensatoryOffs),
        usedDebits: sumCclDebits(slot),
        netUsed: netUsedDaysForType(slot, 'CCL'),
        xferOut: round2(slot.poolCarryForwardOut?.ccl || 0),
        closing: lastClosingCcl(slot),
        reversalCredits: (slot.transactions || []).filter(isCclReversalCredit).length,
      };
    }
  }

  const register = await leaveRegisterService.getLeaveRegister(
    { employeeIds: [emp._id], financialYear: fy },
    null,
    null,
    { lite: true }
  );
  const row = Array.isArray(register) ? register[0] : register?.entries?.[0];
  const mayApi = row?.months?.find((m) => Number(m.month) === 5 && Number(m.year) === 2026);

  return {
    empNo,
    ok: true,
    employeeCompensatoryOffs: round2(emp.compensatoryOffs),
    yearDocCompensatoryOffBalance: round2(yDoc?.compensatoryOffBalance),
    ledgerBalance: round2(ledgerBal),
    mayDb: may,
    mayApi: mayApi
      ? {
          scheduledCco: mayApi.scheduledCco,
          cclUsed: mayApi.ccl?.used,
          cclTransferOut: mayApi.ccl?.transferOut,
          cclBalance: mayApi.cclBalance,
        }
      : null,
  };
}

async function main() {
  if (!process.env.MONGODB_URI) {
    console.error('MONGODB_URI missing');
    process.exit(1);
  }

  const results = {
    ranAt: new Date().toISOString(),
    financialYear: FY,
    unitTestsNote: 'Run: npm test -- leaves/services/__tests__/leaveRegisterYearLedger.cclReconciliation.test.js',
    apiChecks: {},
    audit: {},
    employees: [],
    reconcileDryRun: {},
  };

  results.apiChecks.scheduleRegisterReconciliationFromDate =
    typeof monthlyTransferReconciliationService.scheduleRegisterReconciliationFromDate === 'function';
  results.apiChecks.netUsedDaysForTypeCclIgnoresReversal = (() => {
    const slot = {
      transactions: [
        { leaveType: 'CCL', transactionType: 'DEBIT', days: 2 },
        {
          leaveType: 'CCL',
          transactionType: 'CREDIT',
          days: 1,
          reason: 'Leave Application Cancelled/Reversed',
        },
      ],
    };
    return netUsedDaysForType(slot, 'CCL') === 2;
  })();

  await mongoose.connect(process.env.MONGODB_URI);

  results.audit = await auditCclReversalPairs(FY);

  for (const empNo of SAMPLE_EMP_NOS) {
    results.employees.push(await employeeSnapshot(empNo, FY));
  }

  const emp1890 = await Employee.findOne({ emp_no: '1890' }).select('_id').lean();
  if (emp1890) {
    results.reconcileDryRun = await monthlyTransferReconciliationService.reconcileEmployeeFromDate({
      employeeId: emp1890._id,
      fromDate: new Date('2026-04-01'),
      apply: false,
    });
    await leaveRegisterYearLedgerService.recalculateRegisterBalances(
      emp1890._id,
      'CCL',
      new Date('2026-04-01')
    );
    const after1890 = await employeeSnapshot('1890', FY);
    results.employees = results.employees.map((e) =>
      e.empNo === '1890' ? { ...e, afterRecalc: after1890 } : e
    );
  }

  const outPath = path.join(__dirname, '_test_ccl_reconciliation_results.json');
  fs.writeFileSync(outPath, JSON.stringify(results, null, 2));

  console.log(JSON.stringify(results, null, 2));
  console.log('\nWritten:', outPath);

  await mongoose.disconnect();

  const failed =
    !results.apiChecks.scheduleRegisterReconciliationFromDate ||
    !results.apiChecks.netUsedDaysForTypeCclIgnoresReversal ||
    results.audit.cclMonthsWithReversalAndDebits > 0;

  process.exit(failed ? 1 : 0);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
