/**
 * Sync leave register DEBIT rows with approved LeaveSplit rows.
 * Fixes split-after-approval cases where register still holds the original full debit.
 */
const Leave = require('../model/Leave');
const LeaveSplit = require('../model/LeaveSplit');
const LeaveRegisterYear = require('../model/LeaveRegisterYear');
const Employee = require('../../employees/model/Employee');

const REGISTER_DEBIT_TYPES = new Set(['CL', 'CCL', 'EL', 'LOP']);

function round2(v) {
  return Math.round((Number(v) || 0) * 100) / 100;
}

function splitRowDays(split) {
  if (split?.isHalfDay) return 0.5;
  const n = Number(split?.numberOfDays);
  return Number.isFinite(n) && n > 0 ? n : 1;
}

function sumByLeaveType(debitsByType) {
  const out = {};
  for (const [k, v] of Object.entries(debitsByType || {})) {
    out[String(k).toUpperCase()] = round2(v);
  }
  return out;
}

function sumRegisterDebitsByType(yearDocs, leaveId) {
  const appId = String(leaveId);
  const byType = {};
  for (const doc of yearDocs || []) {
    for (const slot of doc.months || []) {
      for (const tx of slot.transactions || []) {
        if (!tx?.applicationId || String(tx.applicationId) !== appId) continue;
        if (String(tx.transactionType || '').toUpperCase() !== 'DEBIT') continue;
        const auto = String(tx.autoGeneratedType || '');
        if (auto.startsWith('MONTHLY_POOL_TRANSFER_OUT_')) continue;
        const lt = String(tx.leaveType || '').toUpperCase();
        byType[lt] = round2((byType[lt] || 0) + (Number(tx.days) || 0));
      }
    }
  }
  return byType;
}

function buildApprovedSplitDebitsByType(splits) {
  const byType = {};
  for (const s of splits || []) {
    if (String(s.status || '').toLowerCase() !== 'approved') continue;
    const lt = String(s.leaveType || '').toUpperCase();
    if (!REGISTER_DEBIT_TYPES.has(lt)) continue;
    byType[lt] = round2((byType[lt] || 0) + splitRowDays(s));
  }
  return byType;
}

function buildApprovedSplitDebitRows(splits) {
  const rows = [];
  for (const s of splits || []) {
    if (String(s.status || '').toLowerCase() !== 'approved') continue;
    const lt = String(s.leaveType || '').toUpperCase();
    if (!REGISTER_DEBIT_TYPES.has(lt)) continue;
    rows.push({
      leaveType: lt,
      startDate: s.date,
      endDate: s.date,
      days: splitRowDays(s),
    });
  }
  rows.sort(
    (a, b) =>
      new Date(a.startDate).getTime() - new Date(b.startDate).getTime() ||
      String(a.leaveType).localeCompare(String(b.leaveType))
  );
  return rows;
}

function computeTypeDiffs(approvedByType, registerDebits) {
  const allTypes = new Set([
    ...Object.keys(approvedByType || {}),
    ...Object.keys(registerDebits || {}),
  ]);
  const typeDiffs = [];
  for (const lt of allTypes) {
    const approved = round2(approvedByType[lt] || 0);
    const debited = round2(registerDebits[lt] || 0);
    const delta = round2(debited - approved);
    if (Math.abs(delta) >= 0.01) {
      typeDiffs.push({
        leaveType: lt,
        approvedSplitDays: approved,
        registerDebitDays: debited,
        excessDebit: delta,
      });
    }
  }
  return typeDiffs;
}

function leaveOverlapsFy(leave, fyFilter) {
  if (!fyFilter) return true;
  const fromY = new Date(leave.fromDate).getFullYear();
  const toY = new Date(leave.toDate).getFullYear();
  const fyNum = Number(fyFilter);
  return fromY === fyNum || toY === fyNum;
}

async function loadYearDocsForEmployee(employeeId) {
  return LeaveRegisterYear.find({ employeeId }).select('employeeId financialYear months').lean();
}

async function buildSyncPlanForLeave(leave, yearDocs) {
  const splits = await LeaveSplit.find({ leaveId: leave._id }).sort({ date: 1 }).lean();
  const approvedByType = buildApprovedSplitDebitsByType(splits);
  const registerDebits = sumRegisterDebitsByType(yearDocs, leave._id);
  const typeDiffs = computeTypeDiffs(approvedByType, registerDebits);
  const plannedDebits = buildApprovedSplitDebitRows(splits);

  return {
    leaveId: String(leave._id),
    emp_no: leave.emp_no,
    employeeId: String(leave.employeeId),
    fromDate: leave.fromDate,
    toDate: leave.toDate,
    requestDays: leave.numberOfDays,
    leaveType: leave.leaveType,
    splitStatus: leave.splitStatus,
    leaveStatus: leave.status,
    approvedByType,
    registerDebits,
    typeDiffs,
    plannedDebits,
    needsSync: typeDiffs.length > 0,
  };
}

async function findMismatchedSplitLeaves({ fyFilter = null, empNo = null } = {}) {
  const query = {
    splitStatus: 'split_approved',
    isActive: { $ne: false },
  };
  if (empNo != null && String(empNo).trim()) {
    query.emp_no = String(empNo).trim();
  }

  let leaves = await Leave.find(query)
    .select('_id emp_no employeeId leaveType numberOfDays fromDate toDate status splitStatus')
    .lean();

  if (fyFilter) {
    leaves = leaves.filter((l) => leaveOverlapsFy(l, fyFilter));
  }

  const empIds = [...new Set(leaves.map((l) => String(l.employeeId)))];
  const yearDocsByEmp = new Map();
  if (empIds.length) {
    const allYearDocs = await LeaveRegisterYear.find({ employeeId: { $in: empIds } })
      .select('employeeId financialYear months')
      .lean();
    for (const yd of allYearDocs) {
      const k = String(yd.employeeId);
      if (!yearDocsByEmp.has(k)) yearDocsByEmp.set(k, []);
      yearDocsByEmp.get(k).push(yd);
    }
  }

  const plans = [];
  for (const leave of leaves) {
    const yearDocs = yearDocsByEmp.get(String(leave.employeeId)) || [];
    const plan = await buildSyncPlanForLeave(leave, yearDocs);
    if (plan.needsSync) plans.push(plan);
  }

  plans.sort((a, b) => String(a.emp_no).localeCompare(String(b.emp_no)));
  return plans;
}

async function buildEmployeeTransactionBase(leaveRecord, approvedByUserId = null) {
  const employee = await Employee.findById(leaveRecord.employeeId)
    .populate('department_id', 'name')
    .populate('designation_id', 'name');
  if (!employee) throw new Error('Employee not found');

  const mongoose = require('mongoose');
  const approvedBy =
    approvedByUserId && mongoose.Types.ObjectId.isValid(approvedByUserId)
      ? approvedByUserId
      : undefined;

  return {
    employeeId: leaveRecord.employeeId,
    empNo: employee.emp_no,
    employeeName: employee.employee_name || 'N/A',
    designation:
      (employee.designation_id && employee.designation_id.name) ||
      employee.designation?.name ||
      'N/A',
    department:
      (employee.department_id && employee.department_id.name) ||
      employee.department?.name ||
      'N/A',
    divisionId: employee.division_id,
    departmentId: employee.department_id,
    dateOfJoining: employee.doj,
    employmentStatus: employee.is_active ? 'active' : 'inactive',
    applicationId: leaveRecord._id,
    applicationDate: leaveRecord.createdAt,
    approvalDate: leaveRecord.updatedAt || new Date(),
    approvedBy,
    status: 'APPROVED',
    reason: leaveRecord.purpose || leaveRecord.reason || '',
  };
}

/**
 * Reverse existing register debits for this leave and post debits from approved splits.
 * @param {Object} leaveRecord - Leave doc or lean object with _id, employeeId, fromDate, etc.
 * @param {Object} [options]
 * @param {boolean} [options.dryRun=false]
 * @param {mongoose.Types.ObjectId} [options.approvedByUserId]
 */
async function syncLeaveRegisterFromSplits(leaveRecord, options = {}) {
  const { dryRun = false, approvedByUserId = null } = options;
  const leave =
    leaveRecord?.splitStatus != null
      ? leaveRecord
      : await Leave.findById(leaveRecord._id || leaveRecord);

  if (!leave) throw new Error('Leave not found');
  if (String(leave.splitStatus || '') !== 'split_approved') {
    return { skipped: true, reason: 'not_split_approved', leaveId: String(leave._id) };
  }

  const yearDocs = await loadYearDocsForEmployee(leave.employeeId);
  const plan = await buildSyncPlanForLeave(leave, yearDocs);
  if (!plan.needsSync) {
    return { skipped: true, reason: 'already_in_sync', leaveId: String(leave._id), plan };
  }

  if (dryRun) {
    return { dryRun: true, applied: false, leaveId: String(leave._id), plan };
  }

  const leaveRegisterService = require('./leaveRegisterService');
  const leaveRegisterYearMonthlyApplyService = require('./leaveRegisterYearMonthlyApplyService');
  const { reconcileForLeaveChange } = require('./monthlyTransferReconciliationService');

  const reverseResult = await leaveRegisterService.reverseLeaveDebit(leave, approvedByUserId);
  const base = await buildEmployeeTransactionBase(leave, approvedByUserId);

  const posted = [];
  for (const row of plan.plannedDebits) {
    const result = await leaveRegisterService.addTransaction({
      ...base,
      leaveType: row.leaveType,
      transactionType: 'DEBIT',
      startDate: row.startDate,
      endDate: row.endDate,
      days: row.days,
    });
    posted.push({
      leaveType: row.leaveType,
      days: row.days,
      startDate: row.startDate,
      endDate: row.endDate,
      transactionId: result?._id ? String(result._id) : null,
    });
  }

  let monthlyTransferReconciliation = null;
  try {
    monthlyTransferReconciliation = await reconcileForLeaveChange(leave);
  } catch (e) {
    console.warn('[split register sync] transfer reconcile:', e?.message || e);
  }

  try {
    await leaveRegisterYearMonthlyApplyService.syncStoredMonthApplyFieldsForEmployeeDate(
      leave.employeeId,
      leave.fromDate
    );
  } catch (e) {
    console.warn('[split register sync] monthly apply sync:', e?.message || e);
  }

  return {
    applied: true,
    leaveId: String(leave._id),
    emp_no: leave.emp_no,
    reverseResult,
    posted,
    plan,
    monthlyTransferReconciliation,
  };
}

module.exports = {
  REGISTER_DEBIT_TYPES,
  round2,
  splitRowDays,
  sumRegisterDebitsByType,
  buildApprovedSplitDebitsByType,
  buildApprovedSplitDebitRows,
  computeTypeDiffs,
  buildSyncPlanForLeave,
  findMismatchedSplitLeaves,
  syncLeaveRegisterFromSplits,
};
