/**
 * When carryForward.casualLeave.carryMonthlyClCreditToNextPayrollMonth is false,
 * at payroll cycle end we forfeit unused scheduled CL for that month (clCredits − CL debits in that slot),
 * capped by current CL balance. When true, no action (unused credit remains in the balance pool).
 */

const LeaveRegisterYear = require('../model/LeaveRegisterYear');
const { getLeavePolicyResolved } = require('../../settings/services/leavePolicyTypeConfigService');
const Employee = require('../../employees/model/Employee');
const dateCycleService = require('./dateCycleService');
const leaveRegisterService = require('./leaveRegisterService');

const FORFEIT_TYPE = 'MONTHLY_CL_SCHEDULED_FORFEIT';

function sumClDebitsInSlot(slot) {
  const txs = slot?.transactions || [];
  let d = 0;
  for (const t of txs) {
    if (String(t.leaveType || '').toUpperCase() === 'CL' && String(t.transactionType || '').toUpperCase() === 'DEBIT') {
      d += Number(t.days) || 0;
    }
  }
  return d;
}

function alreadyForfeited(slot) {
  return (slot?.transactions || []).some((t) => t.autoGeneratedType === FORFEIT_TYPE);
}

/**
 * @param {number} payrollCycleMonth 1-12
 * @param {number} payrollCycleYear calendar year label for the cycle
 * @returns {Promise<{ processed: number, forfeitsPosted: number, skipped: number, errors: Array<{ empNo?: string, error: string }> }>}
 */
async function forfeitUnusedScheduledClIfNeeded(payrollCycleMonth, payrollCycleYear) {
  const results = { processed: 0, forfeitsPosted: 0, skipped: 0, errors: [] };
  const settings = await getLeavePolicyResolved();
  if (settings?.carryForward?.casualLeave?.carryMonthlyClCreditToNextPayrollMonth !== false) {
    return results;
  }

  const pm = Number(payrollCycleMonth);
  const py = Number(payrollCycleYear);
  const midDate = new Date(py, pm - 1, 15);
  const periodInfo = await dateCycleService.getPeriodInfo(midDate);
  const cycleEnd = periodInfo.payrollCycle.endDate;

  const docs = await LeaveRegisterYear.find({
    months: {
      $elemMatch: { payrollCycleMonth: pm, payrollCycleYear: py },
    },
  });

  for (const doc of docs) {
    results.processed++;
    try {
      const months = doc.months || [];
      const mi = months.findIndex(
        (m) => Number(m.payrollCycleMonth) === pm && Number(m.payrollCycleYear) === py
      );
      if (mi < 0) {
        results.skipped++;
        continue;
      }
      const slot = months[mi];
      if (alreadyForfeited(slot)) {
        results.skipped++;
        continue;
      }

      const scheduled = Number(slot.clCredits) || 0;
      if (scheduled <= 0) {
        results.skipped++;
        continue;
      }

      const usedInSlot = sumClDebitsInSlot(slot);
      const unusedScheduled = Math.max(0, scheduled - usedInSlot);
      if (unusedScheduled <= 0) {
        results.skipped++;
        continue;
      }

      const balance = await leaveRegisterService.getCurrentBalance(doc.employeeId, 'CL', cycleEnd);
      const forfeitDays = Math.min(unusedScheduled, Math.max(0, Number(balance) || 0));
      if (forfeitDays <= 0) {
        results.skipped++;
        continue;
      }

      const employee = await Employee.findById(doc.employeeId)
        .select('_id emp_no employee_name department_id division_id designation_id doj is_active')
        .populate('department_id', 'name')
        .populate('division_id', 'name')
        .populate('designation_id', 'name')
        .lean();
      if (!employee) {
        results.errors.push({ error: `Employee missing for year doc ${doc._id}` });
        continue;
      }

      const department = employee.department_id?.name || 'N/A';
      const designation = employee.designation_id?.name || 'N/A';

      await leaveRegisterService.addTransaction({
        employeeId: doc.employeeId,
        empNo: employee.emp_no,
        employeeName: employee.employee_name || 'N/A',
        designation,
        department,
        divisionId: employee.division_id?._id || employee.division_id,
        departmentId: employee.department_id?._id || employee.department_id,
        dateOfJoining: employee.doj,
        employmentStatus: employee.is_active ? 'active' : 'inactive',
        leaveType: 'CL',
        transactionType: 'EXPIRY',
        startDate: cycleEnd,
        endDate: cycleEnd,
        days: forfeitDays,
        reason: `Unused scheduled CL for payroll ${pm}/${py} (${scheduled} scheduled, ${usedInSlot} used) — policy: monthly credit does not roll`,
        status: 'APPROVED',
        autoGenerated: true,
        autoGeneratedType: FORFEIT_TYPE,
      });
      results.forfeitsPosted++;
    } catch (e) {
      results.errors.push({
        empNo: doc.empNo,
        error: e.message || String(e),
      });
    }
  }

  return results;
}

module.exports = {
  forfeitUnusedScheduledClIfNeeded,
  FORFEIT_TYPE,
};
