/**
 * odCclRetroSyncService.js
 *
 * Retroactive CCL sync for approved ODs when a holiday or week-off is added
 * to the attendance/payroll calendar AFTER the OD was already applied.
 *
 * Scenario:
 *   1. Employee applies an OD on 2026-08-15.
 *   2. At apply time, the day was a normal working day → isCOEligible = false.
 *   3. Admin later marks 2026-08-15 as a holiday in the calendar.
 *   4. This service finds all approved ODs on that date for affected employees,
 *      sets isCOEligible = true, and credits CCL +1 (or +0.5 for half-day OD).
 *
 * Duplicate guard: Checks LeaveRegisterYear for an existing OD_HOLIDAY_WO_CO_CREDIT
 * transaction on the same date before issuing a new credit.
 *
 * Called from:
 *   - holidayController.applyRosterEntriesAndSync (after HOL/WO roster entries are written)
 *   - POST /api/od/admin/retro-ccl-sync (manual trigger by super_admin)
 */

'use strict';

const OD = require('../model/OD');
const Employee = require('../../employees/model/Employee');
const LeaveRegisterYear = require('../model/LeaveRegisterYear');
const leaveRegisterService = require('./leaveRegisterService');
const { isHolidayOrWeekOff } = require('./odHolidayApplyContextService');
const { getRosterHalfHolidayForEmployeeDate } = require('./odHalfHolidayRosterService');
const AttendanceDaily = require('../../attendance/model/AttendanceDaily');
const { extractISTComponents, createISTDate, getAllDatesInRange } = require('../../shared/utils/dateUtils');

/**
 * Check if there is already a CCL credit of type OD_HOLIDAY_WO_CO_CREDIT
 * for this employee on this date (duplicate guard).
 */
async function hasExistingCclCredit(employeeId, dateStr) {
  const dayStart = createISTDate(dateStr, '00:00');
  const dayEnd = createISTDate(dateStr, '23:59');
  const row = await LeaveRegisterYear.findOne({
    employeeId,
    months: {
      $elemMatch: {
        transactions: {
          $elemMatch: {
            leaveType: 'CCL',
            transactionType: 'CREDIT',
            autoGeneratedType: 'OD_HOLIDAY_WO_CO_CREDIT',
            startDate: { $gte: dayStart, $lte: dayEnd },
          },
        },
      },
    },
  })
    .select('_id')
    .lean();
  return !!row;
}

/**
 * Re-check whether a given date qualifies as holiday/week-off for an employee,
 * using the same logic as dayQualifiesForHolidayWeekOffCo in odController.
 */
async function dateQualifiesForCo(empNo, dateStr, isCOEligible) {
  // 1. Roster-based check (PreScheduledShift HOL / WO status or half-HOL)
  if (await isHolidayOrWeekOff(empNo, dateStr)) return true;

  // 2. Half-roster holiday
  const halfCtx = await getRosterHalfHolidayForEmployeeDate(empNo, dateStr);
  if (halfCtx.hasHalfHoliday) return true;

  // 3. AttendanceDaily status
  const raw = String(empNo || '').trim();
  const variants = [...new Set([raw.toUpperCase(), raw].filter(Boolean))];
  const att = await AttendanceDaily.findOne({
    date: dateStr,
    employeeNumber: variants.length ? { $in: variants } : raw.toUpperCase(),
  })
    .select('status')
    .lean();
  const st = String(att?.status || '').toUpperCase();
  if (st === 'HOLIDAY' || st === 'WEEK_OFF') return true;

  // 4. Apply-time CO flag (already set from original apply context)
  if (isCOEligible === true) return true;

  return false;
}

/**
 * Core sync function.
 *
 * @param {Array<{employeeNumber: string, date: string}>} rosterEntries
 *   Entries whose status was just set to HOL or WO. Only full-day HOL/WO entries
 *   are processed (the caller may pass all roster entries; this function filters).
 * @param {object} [options]
 * @param {boolean} [options.dryRun=false]  If true, log intent but make no writes.
 * @param {Function} [options.onProgress]   Optional callback(info) for progress.
 * @returns {Promise<{credited: number, skipped: number, errors: number, details: Array}>}
 */
async function syncCclForNewHolidayWoEntries(rosterEntries, options = {}) {
  const { dryRun = false, onProgress } = options;

  const result = { credited: 0, skipped: 0, errors: 0, details: [] };

  // Filter: only HOL or WO entries (status-based calendar days)
  const holWoEntries = (rosterEntries || []).filter(
    (e) => e.status === 'HOL' || e.status === 'WO'
  );

  if (holWoEntries.length === 0) return result;

  // Group by date for batch processing
  const byDate = new Map();
  for (const e of holWoEntries) {
    const key = e.date;
    if (!byDate.has(key)) byDate.set(key, new Set());
    byDate.get(key).add(String(e.employeeNumber || '').toUpperCase());
  }

  let processed = 0;
  const total = holWoEntries.length;

  for (const [dateStr, empNos] of byDate.entries()) {
    for (const empNo of empNos) {
      processed++;
      if (onProgress) onProgress({ processed, total, dateStr, empNo });

      try {
        // Find all approved ODs for this employee on this date
        const dayStart = createISTDate(dateStr, '00:00');
        const dayEnd = createISTDate(dateStr, '23:59');

        const ods = await OD.find({
          emp_no: { $in: [empNo, empNo.toLowerCase()] },
          status: 'approved',
          fromDate: { $lte: dayEnd },
          toDate: { $gte: dayStart },
        })
          .select('_id emp_no employeeId fromDate toDate isHalfDay odType_extended isCOEligible numberOfDays')
          .lean();

        if (ods.length === 0) {
          result.skipped++;
          result.details.push({ empNo, dateStr, reason: 'no_approved_od' });
          continue;
        }

        for (const od of ods) {
          const odDateStr = extractISTComponents(od.fromDate).dateStr;
          // Only process ODs whose fromDate falls on this specific calendar day
          if (odDateStr !== dateStr) continue;

          // Skip if already flagged and credited
          const alreadyHasCredit = await hasExistingCclCredit(od.employeeId, dateStr);
          if (alreadyHasCredit) {
            result.skipped++;
            result.details.push({ empNo, dateStr, odId: String(od._id), reason: 'credit_already_exists' });
            continue;
          }

          // Re-evaluate qualification using updated roster
          const qualifies = await dateQualifiesForCo(empNo, dateStr, od.isCOEligible);
          if (!qualifies) {
            result.skipped++;
            result.details.push({ empNo, dateStr, odId: String(od._id), reason: 'not_qualified_after_check' });
            continue;
          }

          const halfDayOd = !!(od.isHalfDay || od.odType_extended === 'half_day');
          const increment = halfDayOd ? 0.5 : 1;

          console.log(
            `[OD-CCL-RETRO] ${dryRun ? '[DRY-RUN] ' : ''}Crediting CCL +${increment} for ${empNo} on ${dateStr} (OD ${od._id})`
          );

          if (!dryRun) {
            // Update isCOEligible on the OD document
            await OD.updateOne({ _id: od._id }, { $set: { isCOEligible: true } });

            // Load employee details for the ledger
            const emp = await Employee.findById(od.employeeId)
              .populate('department_id', 'name')
              .populate('designation_id', 'name')
              .lean();

            if (emp) {
              await leaveRegisterService.addTransaction({
                employeeId: od.employeeId,
                empNo: od.emp_no,
                employeeName: emp.employee_name || 'N/A',
                designation: (emp.designation_id && emp.designation_id.name) || 'N/A',
                department: (emp.department_id && emp.department_id.name) || 'N/A',
                divisionId: emp.division_id,
                departmentId: emp.department_id,
                dateOfJoining: emp.doj || new Date(),
                employmentStatus: emp.is_active ? 'active' : 'inactive',
                leaveType: 'CCL',
                transactionType: 'CREDIT',
                startDate: createISTDate(dateStr),
                endDate: createISTDate(dateStr),
                days: increment,
                reason: `Retro CCL: holiday/week-off set after OD approved (${dateStr})`,
                status: 'APPROVED',
                autoGenerated: true,
                autoGeneratedType: 'OD_HOLIDAY_WO_CO_CREDIT',
                applicationId: od._id,
              });
            } else {
              console.warn(`[OD-CCL-RETRO] Employee not found for employeeId=${od.employeeId}, skipping CCL credit`);
              result.errors++;
              result.details.push({ empNo, dateStr, odId: String(od._id), reason: 'employee_not_found' });
              continue;
            }
          }

          result.credited++;
          result.details.push({
            empNo,
            dateStr,
            odId: String(od._id),
            increment,
            dryRun,
            reason: 'credited',
          });
        }
      } catch (err) {
        console.error(`[OD-CCL-RETRO] Error processing empNo=${empNo} date=${dateStr}:`, err.message || err);
        result.errors++;
        result.details.push({ empNo, dateStr, reason: 'error', error: err.message });
      }
    }
  }

  console.log(
    `[OD-CCL-RETRO] Done. credited=${result.credited} skipped=${result.skipped} errors=${result.errors} dryRun=${dryRun}`
  );
  return result;
}

/**
 * Convenience wrapper for manual admin trigger: given an array of dateStrings and
 * optional employeeNumbers, run the retro-sync.
 * If employeeNumbers is empty, searches ALL employees with approved ODs on those dates.
 *
 * @param {string[]} dates - ISO date strings YYYY-MM-DD
 * @param {string[]} [employeeNumbers] - Optional filter. If empty → all employees.
 * @param {boolean} [dryRun=false]
 */
async function retroSyncForDates(dates, employeeNumbers = [], dryRun = false) {
  const allResults = { credited: 0, skipped: 0, errors: 0, details: [] };

  for (const dateStr of dates) {
    let empNosToCheck = employeeNumbers.map((n) => n.toUpperCase());

    // If no specific employees, find all who have approved ODs on this date
    if (empNosToCheck.length === 0) {
      const dayStart = createISTDate(dateStr, '00:00');
      const dayEnd = createISTDate(dateStr, '23:59');
      const ods = await OD.find({
        status: 'approved',
        fromDate: { $lte: dayEnd },
        toDate: { $gte: dayStart },
      })
        .select('emp_no')
        .lean();
      const uniqueEmpNos = [...new Set(ods.map((o) => String(o.emp_no || '').toUpperCase()).filter(Boolean))];
      empNosToCheck = uniqueEmpNos;
    }

    if (empNosToCheck.length === 0) continue;

    // Build fake roster entries to reuse syncCclForNewHolidayWoEntries
    const fakeEntries = empNosToCheck.map((empNo) => ({
      employeeNumber: empNo,
      date: dateStr,
      status: 'HOL', // We just need HOL/WO to pass the filter
    }));

    const r = await syncCclForNewHolidayWoEntries(fakeEntries, { dryRun });
    allResults.credited += r.credited;
    allResults.skipped += r.skipped;
    allResults.errors += r.errors;
    allResults.details.push(...r.details);
  }

  return allResults;
}

module.exports = {
  syncCclForNewHolidayWoEntries,
  retroSyncForDates,
};
