const mongoose = require('mongoose');
const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '../.env') });

const Employee = require('../employees/model/Employee');
const LeaveRegisterYear = require('../leaves/model/LeaveRegisterYear');

function sumTx(slot, prefix) {
  let s = 0;
  for (const t of slot?.transactions || []) {
    if (String(t.autoGeneratedType || '').startsWith(prefix)) {
      s += Math.max(0, Number(t.days) || 0);
    }
  }
  return s;
}

async function run(empNo) {
  const emp = await Employee.findOne({ $or: [{ emp_no: String(empNo) }, { emp_no: Number(empNo) }] })
    .select('_id emp_no employee_name')
    .lean();
  if (!emp) {
    console.log(`[check] emp_no=${empNo}: not found`);
    return;
  }

  const doc = await LeaveRegisterYear.findOne({ employeeId: emp._id, financialYear: '2026' }).lean();
  if (!doc) {
    console.log(`[check] emp_no=${emp.emp_no}: no LeaveRegisterYear 2026`);
    return;
  }

  console.log(`\n=== ${emp.emp_no} ${emp.employee_name || ''} ===`);
  const ordered = [...(doc.months || [])].sort(
    (a, b) => new Date(a.payPeriodStart || a.payPeriodEnd || 0) - new Date(b.payPeriodStart || b.payPeriodEnd || 0)
  );
  for (const m of ordered) {
    const outCL = sumTx(m, 'MONTHLY_POOL_TRANSFER_OUT_CL');
    const inCL = sumTx(m, 'MONTHLY_POOL_TRANSFER_IN_CL');
    const outCCL = sumTx(m, 'MONTHLY_POOL_TRANSFER_OUT_CCL');
    const inCCL = sumTx(m, 'MONTHLY_POOL_TRANSFER_IN_CCL');
    const outEL = sumTx(m, 'MONTHLY_POOL_TRANSFER_OUT_EL');
    const inEL = sumTx(m, 'MONTHLY_POOL_TRANSFER_IN_EL');
    if (outCL || inCL || outCCL || inCCL || outEL || inEL) {
      console.log(
        `${m.label || `${m.payrollCycleMonth}/${m.payrollCycleYear}`}: ` +
          `CL(out=${outCL}, in=${inCL}) ` +
          `CCL(out=${outCCL}, in=${inCCL}) ` +
          `EL(out=${outEL}, in=${inEL})`
      );
    }
  }
}

async function main() {
  await mongoose.connect(process.env.MONGODB_URI);
  for (const n of [2144, 2145, 2146]) {
    // eslint-disable-next-line no-await-in-loop
    await run(n);
  }
  await mongoose.disconnect();
}

main().catch((e) => {
  console.error(e);
  process.exitCode = 1;
});

