'use client';

import React, { useState, useEffect } from 'react';
import { Calendar, Download, Search, Filter, Plus, Settings, Eye } from 'lucide-react';
import { api } from '@/lib/api';
import { toast } from 'react-hot-toast';

interface Employee {
    employeeId: string;
    empNo: string;
    employeeName: string;
    designation: string;
    department: string;
    divisionName: string;
    clBalance: number;
    elBalance: number;
    compensatoryOffBalance: number;
    presentMonthAllowedLeaves: number;
    cumulativeLeaves: number;
}

interface LeaveTransaction {
    _id: string;
    leaveType: string;
    transactionType: string;
    startDate: string;
    endDate: string;
    days: number;
    openingBalance: number;
    closingBalance: number;
    status: string;
    reason: string;
    applicationDate: string;
    approvalDate: string;
    autoGenerated: boolean;
    payrollCycleStart: string;
    payrollCycleEnd: string;
    financialYear: string;
}

interface EmployeeDetail {
    employeeId: string;
    empNo: string;
    employeeName: string;
    designation: string;
    department: string;
    divisionName: string;
    dateOfJoining: string;
    employmentStatus: string;
    leaveTypes: {
        [key: string]: {
            openingBalance: number;
            closingBalance: number;
            credits: number;
            debits: number;
            transactions: LeaveTransaction[];
        };
    };
}

export default function LeaveRegisterPage() {
    const [employees, setEmployees] = useState<Employee[]>([]);
    const [loading, setLoading] = useState(true);
    const [searchTerm, setSearchTerm] = useState('');
    const [selectedEmployee, setSelectedEmployee] = useState<EmployeeDetail | null>(null);
    const [showDetailModal, setShowDetailModal] = useState(false);
    const [showAdjustModal, setShowAdjustModal] = useState(false);
    const [adjustmentData, setAdjustmentData] = useState({
        employeeId: '',
        clBalance: 0,
        days: '', // positive = add days, negative = subtract
        reason: ''
    });
    const [showEmployeeDetailModal, setShowEmployeeDetailModal] = useState(false);
    const [selectedEmployeeDetail, setSelectedEmployeeDetail] = useState(null);
    const [selectedMonth, setSelectedMonth] = useState(new Date().getMonth() + 1);
    const [selectedYear, setSelectedYear] = useState(new Date().getFullYear());

    useEffect(() => {
        fetchLeaveRegister();
    }, [selectedMonth, selectedYear]);

    const fetchLeaveRegister = async () => {
        try {
            setLoading(true);
            const data = await api.getLeaveRegister({
                month: selectedMonth,
                year: selectedYear
            });
            
            if (data.success) {
                // Backend returns groupByEmployeeMonthly: { employee, casualLeave, earnedLeave, compensatoryOff, totalPaidBalance }
                const formattedEmployees = (data.data || []).map((emp: any) => {
                    const employee = emp.employee || {};
                    const employeeId = employee.id || emp.employeeId?._id || emp.employeeId?.id || emp.employeeId;
                    const casualLeave = emp.casualLeave || {};
                    const earnedLeave = emp.earnedLeave || {};
                    const presentMonth = (casualLeave.accruedThisMonth || 0) + (earnedLeave.accruedThisMonth || 0);
                    return {
                        employeeId,
                        empNo: employee.empNo ?? emp.empNo,
                        employeeName: employee.name ?? emp.employeeName,
                        designation: employee.designation ?? emp.designation,
                        department: employee.department ?? emp.department,
                        divisionName: employee.division ?? emp.divisionName ?? 'N/A',
                        clBalance: casualLeave.balance ?? 0,
                        elBalance: earnedLeave.balance ?? 0,
                        compensatoryOffBalance: (emp.compensatoryOff?.balance) ?? 0,
                        presentMonthAllowedLeaves: presentMonth,
                        cumulativeLeaves: emp.totalPaidBalance ?? 0
                    };
                });
                setEmployees(formattedEmployees);
            } else {
                toast.error('Failed to fetch leave register');
            }
        } catch (error) {
            console.error('Error fetching leave register:', error);
            toast.error('Error fetching leave register');
        } finally {
            setLoading(false);
        }
    };

    const fetchEmployeeDetail = async (employeeId: string) => {
        try {
            const data = await api.getEmployeeRegister(employeeId);
            if (data.success) {
                setSelectedEmployeeDetail(data.data);
                setShowEmployeeDetailModal(true);
            } else {
                toast.error('Failed to fetch employee details');
            }
        } catch (error) {
            console.error('Error fetching employee details:', error);
            toast.error('Error fetching employee details');
        }
    };

    const openAdjustModal = (employee: Employee) => {
        setAdjustmentData({
            employeeId: employee.employeeId,
            clBalance: employee.clBalance,
            days: '',
            reason: ''
        });
        setShowAdjustModal(true);
    };

    const handleAdjustment = async () => {
        const daysNum = parseFloat(adjustmentData.days);
        if (adjustmentData.days === '' || isNaN(daysNum) || !adjustmentData.reason.trim()) {
            toast.error('Please enter days (positive to add, negative to subtract) and reason');
            return;
        }

        try {
            const result = await api.adjustCLBalance({
                employeeId: adjustmentData.employeeId,
                days: daysNum,
                reason: adjustmentData.reason.trim()
            });

            if (result.success) {
                toast.success('CL balance adjusted successfully');
                setShowAdjustModal(false);
                fetchLeaveRegister(); // Refresh data
            } else {
                toast.error(result.message || 'Failed to adjust CL balance');
            }
        } catch (error) {
            console.error('Error adjusting CL balance:', error);
            toast.error('Error adjusting CL balance');
        }
    };

    const exportToExcel = () => {
        // TODO: Implement Excel export
        toast.success('Export feature coming soon!');
    };

    if (loading) {
        return (
            <div className="flex items-center justify-center min-h-96">
                <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-indigo-600"></div>
            </div>
        );
    }

    return (
        <div className="space-y-6">
            {/* Header */}
            <div className="flex items-center justify-between">
                <div>
                    <h1 className="text-2xl font-bold text-gray-900">Leave Register</h1>
                    <p className="text-gray-500">Complete leave ledger for all employees</p>
                </div>
                <button
                    onClick={exportToExcel}
                    className="flex items-center gap-2 px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700"
                >
                    <Download className="w-4 h-4" />
                    Export
                </button>
            </div>

            {/* Filters */}
            <div className="bg-white rounded-lg border p-4">
                <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                    <div className="relative">
                        <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 w-4 h-4" />
                        <input
                            type="text"
                            placeholder="Search employees..."
                            value={searchTerm}
                            onChange={(e) => setSearchTerm(e.target.value)}
                            className="pl-10 pr-4 py-2 border rounded-lg w-full"
                        />
                    </div>
                    
                    <div className="flex items-center gap-2">
                        <Calendar className="w-4 h-4 text-gray-500" />
                        <select
                            value={selectedMonth}
                            onChange={(e) => setSelectedMonth(parseInt(e.target.value))}
                            className="px-3 py-2 border rounded-lg"
                        >
                            {[...Array(12)].map((_, i) => (
                                <option key={i} value={i + 1}>
                                    {new Date(0, i).toLocaleString('default', { month: 'long' })}
                                </option>
                            ))}
                        </select>
                    </div>
                    
                    <div className="flex items-center gap-2">
                        <Calendar className="w-4 h-4 text-gray-500" />
                        <select
                            value={selectedYear}
                            onChange={(e) => setSelectedYear(parseInt(e.target.value))}
                            className="px-3 py-2 border rounded-lg"
                        >
                            {[2024, 2025, 2026].map(year => (
                                <option key={year} value={year}>{year}</option>
                            ))}
                        </select>
                    </div>
                </div>
            </div>

            {/* Employee Table */}
            <div className="bg-white rounded-lg border overflow-hidden">
                <div className="overflow-x-auto">
                    <table className="w-full">
                        <thead className="bg-gray-50">
                            <tr>
                                <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                    Employee Details
                                </th>
                                <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                    Division
                                </th>
                                <th className="px-4 py-3 text-center text-xs font-medium text-gray-500 uppercase tracking-wider">
                                    CL Balance
                                </th>
                                <th className="px-4 py-3 text-center text-xs font-medium text-gray-500 uppercase tracking-wider">
                                    EL Balance
                                </th>
                                <th className="px-4 py-3 text-center text-xs font-medium text-gray-500 uppercase tracking-wider">
                                    Comp Off Balance
                                </th>
                                <th className="px-4 py-3 text-center text-xs font-medium text-gray-500 uppercase tracking-wider">
                                    Present Month
                                </th>
                                <th className="px-4 py-3 text-center text-xs font-medium text-gray-500 uppercase tracking-wider">
                                    Cumulative
                                </th>
                                <th className="px-4 py-3 text-center text-xs font-medium text-gray-500 uppercase tracking-wider">
                                    Actions
                                </th>
                            </tr>
                        </thead>
                        <tbody className="bg-white divide-y divide-gray-200">
                            {filteredEmployees.map((employee) => (
                                <tr key={employee.employeeId} className="hover:bg-gray-50">
                                    <td className="px-4 py-4">
                                        <div>
                                            <div className="font-medium text-gray-900">{employee.employeeName}</div>
                                            <div className="text-sm text-gray-500">{employee.empNo}</div>
                                            <div className="text-sm text-gray-500">{employee.designation}</div>
                                            <div className="text-sm text-gray-500">{employee.department}</div>
                                        </div>
                                    </td>
                                    <td className="px-4 py-4 text-sm text-gray-900">
                                        {employee.divisionName}
                                    </td>
                                    <td className="px-4 py-4 text-center">
                                        <span className={`inline-flex px-2 py-1 text-xs font-semibold rounded-full ${
                                            employee.clBalance > 0 ? 'bg-green-100 text-green-800' : 'bg-red-100 text-red-800'
                                        }`}>
                                            {employee.clBalance}
                                        </span>
                                    </td>
                                    <td className="px-4 py-4 text-center">
                                        <span className={`inline-flex px-2 py-1 text-xs font-semibold rounded-full ${
                                            employee.elBalance > 0 ? 'bg-green-100 text-green-800' : 'bg-red-100 text-red-800'
                                        }`}>
                                            {employee.elBalance}
                                        </span>
                                    </td>
                                    <td className="px-4 py-4 text-center">
                                        <span className={`inline-flex px-2 py-1 text-xs font-semibold rounded-full ${
                                            employee.compensatoryOffBalance > 0 ? 'bg-green-100 text-green-800' : 'bg-gray-100 text-gray-800'
                                        }`}>
                                            {employee.compensatoryOffBalance}
                                        </span>
                                    </td>
                                    <td className="px-4 py-4 text-center text-sm text-gray-900">
                                        {employee.presentMonthAllowedLeaves}
                                    </td>
                                    <td className="px-4 py-4 text-center text-sm text-gray-900">
                                        {employee.cumulativeLeaves}
                                    </td>
                                    <td className="px-4 py-4 text-center">
                                        <button
                                            onClick={() => fetchEmployeeDetail(employee.employeeId)}
                                            className="text-indigo-600 hover:text-indigo-900 inline-flex items-center gap-1 mr-2"
                                        >
                                            <Eye className="w-4 h-4" />
                                            View
                                        </button>
                                        <button
                                            onClick={() => openAdjustModal(employee)}
                                            className="text-green-600 hover:text-green-900 inline-flex items-center gap-1"
                                        >
                                            <Settings className="w-4 h-4" />
                                            Adjust
                                        </button>
                                    </td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>
            </div>

            {/* Employee Detail Modal */}
            {showDetailModal && selectedEmployee && (
                <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
                    <div className="bg-white rounded-lg w-full max-w-6xl max-h-[90vh] overflow-hidden">
                        <div className="p-6 border-b">
                            <div className="flex items-center justify-between">
                                <h2 className="text-xl font-bold">Employee Leave Register</h2>
                                <button
                                    onClick={() => setShowDetailModal(false)}
                                    className="text-gray-400 hover:text-gray-600"
                                >
                                    ×
                                </button>
                            </div>
                        </div>
                        
                        <div className="p-6 overflow-y-auto max-h-[calc(90vh-200px)]">
                            {/* Employee Basic Info */}
                            <div className="bg-gray-50 rounded-lg p-4 mb-6">
                                <h3 className="font-semibold mb-3">Employee Information</h3>
                                <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                                    <div>
                                        <label className="text-sm text-gray-500">Name</label>
                                        <p className="font-medium">{selectedEmployee.employeeName}</p>
                                    </div>
                                    <div>
                                        <label className="text-sm text-gray-500">Employee No</label>
                                        <p className="font-medium">{selectedEmployee.empNo}</p>
                                    </div>
                                    <div>
                                        <label className="text-sm text-gray-500">Designation</label>
                                        <p className="font-medium">{selectedEmployee.designation}</p>
                                    </div>
                                    <div>
                                        <label className="text-sm text-gray-500">Department</label>
                                        <p className="font-medium">{selectedEmployee.department}</p>
                                    </div>
                                    <div>
                                        <label className="text-sm text-gray-500">Date of Joining</label>
                                        <p className="font-medium">{new Date(selectedEmployee.dateOfJoining).toLocaleDateString()}</p>
                                    </div>
                                    <div>
                                        <label className="text-sm text-gray-500">Employment Status</label>
                                        <p className="font-medium">{selectedEmployee.employmentStatus}</p>
                                    </div>
                                </div>
                            </div>

                            {/* Current Balances */}
                            <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
                                {Object.entries(selectedEmployee.leaveTypes).map(([leaveType, data]) => (
                                    <div key={leaveType} className="bg-white border rounded-lg p-4">
                                        <h4 className="font-semibold mb-2">{leaveType} Balance</h4>
                                        <div className="space-y-1">
                                            <div className="flex justify-between">
                                                <span className="text-sm text-gray-500">Opening:</span>
                                                <span className="font-medium">{data.openingBalance}</span>
                                            </div>
                                            <div className="flex justify-between">
                                                <span className="text-sm text-gray-500">Credits:</span>
                                                <span className="font-medium text-green-600">+{data.credits}</span>
                                            </div>
                                            <div className="flex justify-between">
                                                <span className="text-sm text-gray-500">Debits:</span>
                                                <span className="font-medium text-red-600">-{data.debits}</span>
                                            </div>
                                            <div className="flex justify-between border-t pt-1">
                                                <span className="text-sm font-medium">Closing:</span>
                                                <span className="font-bold">{data.closingBalance}</span>
                                            </div>
                                        </div>
                                    </div>
                                ))}
                            </div>

                            {/* Transactions */}
                            <div>
                                <h3 className="font-semibold mb-3">All Transactions</h3>
                                <div className="overflow-x-auto">
                                    <table className="w-full text-sm">
                                        <thead className="bg-gray-50">
                                            <tr>
                                                <th className="px-3 py-2 text-left">Date</th>
                                                <th className="px-3 py-2 text-left">Type</th>
                                                <th className="px-3 py-2 text-left">Transaction</th>
                                                <th className="px-3 py-2 text-center">Days</th>
                                                <th className="px-3 py-2 text-center">Opening</th>
                                                <th className="px-3 py-2 text-center">Closing</th>
                                                <th className="px-3 py-2 text-left">Status</th>
                                                <th className="px-3 py-2 text-left">Reason</th>
                                                <th className="px-3 py-2 text-left">Auto</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {Object.values(selectedEmployee.leaveTypes).flatMap((leaveType) =>
                                                leaveType.transactions.map((transaction, index) => (
                                                    <tr key={`${transaction._id}-${index}`} className="border-b">
                                                        <td className="px-3 py-2">
                                                            {new Date(transaction.startDate).toLocaleDateString()}
                                                        </td>
                                                        <td className="px-3 py-2">
                                                            <span className={`px-2 py-1 text-xs rounded ${
                                                                transaction.leaveType === 'EL' ? 'bg-blue-100 text-blue-800' :
                                                                transaction.leaveType === 'CL' ? 'bg-green-100 text-green-800' :
                                                                transaction.leaveType === 'SL' ? 'bg-yellow-100 text-yellow-800' :
                                                                'bg-gray-100 text-gray-800'
                                                            }`}>
                                                                {transaction.leaveType}
                                                            </span>
                                                        </td>
                                                        <td className="px-3 py-2">
                                                            <span className={`px-2 py-1 text-xs rounded ${
                                                                transaction.transactionType === 'CREDIT' ? 'bg-green-100 text-green-800' :
                                                                transaction.transactionType === 'DEBIT' ? 'bg-red-100 text-red-800' :
                                                                'bg-gray-100 text-gray-800'
                                                            }`}>
                                                                {transaction.transactionType}
                                                            </span>
                                                        </td>
                                                        <td className="px-3 py-2 text-center">{transaction.days}</td>
                                                        <td className="px-3 py-2 text-center">{transaction.openingBalance}</td>
                                                        <td className="px-3 py-2 text-center font-medium">{transaction.closingBalance}</td>
                                                        <td className="px-3 py-2">
                                                            <span className={`px-2 py-1 text-xs rounded ${
                                                                transaction.status === 'APPROVED' ? 'bg-green-100 text-green-800' :
                                                                transaction.status === 'PENDING' ? 'bg-yellow-100 text-yellow-800' :
                                                                'bg-gray-100 text-gray-800'
                                                            }`}>
                                                                {transaction.status}
                                                            </span>
                                                        </td>
                                                        <td className="px-3 py-2 text-sm">{transaction.reason}</td>
                                                        <td className="px-3 py-2 text-center">
                                                            {transaction.autoGenerated && (
                                                                <span className="text-blue-600">✓</span>
                                                            )}
                                                        </td>
                                                    </tr>
                                                ))
                                            )}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            )}

            {/* CL Balance Adjustment Modal */}
            {showAdjustModal && (
                <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
                    <div className="bg-white rounded-lg w-full max-w-md p-6">
                        <div className="flex items-center justify-between mb-4">
                            <h2 className="text-xl font-bold">Adjust CL Balance</h2>
                            <button
                                onClick={() => setShowAdjustModal(false)}
                                className="text-gray-400 hover:text-gray-600"
                            >
                                ×
                            </button>
                        </div>
                        
                        <div className="space-y-4">
                            <div>
                                <label className="block text-sm font-medium text-gray-700 mb-2">
                                    Employee
                                </label>
                                <input
                                    type="text"
                                    value={adjustmentData.employeeId}
                                    disabled
                                    className="w-full px-3 py-2 border border-gray-300 rounded-lg bg-gray-100"
                                />
                            </div>
                            
                            <div>
                                <label className="block text-sm font-medium text-gray-700 mb-2">
                                    Current CL Balance
                                </label>
                                <input
                                    type="text"
                                    value={adjustmentData.clBalance}
                                    readOnly
                                    className="w-full px-3 py-2 border border-gray-300 rounded-lg bg-gray-100"
                                />
                            </div>

                            <div>
                                <label className="block text-sm font-medium text-gray-700 mb-2">
                                    Days to adjust
                                </label>
                                <input
                                    type="number"
                                    step="0.5"
                                    value={adjustmentData.days}
                                    onChange={(e) => setAdjustmentData({ ...adjustmentData, days: e.target.value })}
                                    className="w-full px-3 py-2 border border-gray-300 rounded-lg"
                                    placeholder="e.g. 2 to add, -1 to subtract"
                                />
                            </div>
                            
                            <div>
                                <label className="block text-sm font-medium text-gray-700 mb-2">
                                    Reason for Adjustment
                                </label>
                                <textarea
                                    value={adjustmentData.reason}
                                    onChange={(e) => setAdjustmentData({...adjustmentData, reason: e.target.value})}
                                    className="w-full px-3 py-2 border border-gray-300 rounded-lg"
                                    rows={3}
                                    placeholder="Enter reason for balance adjustment"
                                />
                            </div>
                            
                            <div className="flex gap-3 pt-4">
                                <button
                                    onClick={() => setShowAdjustModal(false)}
                                    className="flex-1 px-4 py-2 border border-gray-300 rounded-lg text-gray-700 hover:bg-gray-50"
                                >
                                    Cancel
                                </button>
                                <button
                                    onClick={handleAdjustment}
                                    className="flex-1 px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700"
                                >
                                    Adjust Balance
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            )}

            {/* Employee Detail Modal */}
            {showEmployeeDetailModal && selectedEmployeeDetail && (
                <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
                    <div className="bg-white rounded-lg p-6 w-full max-w-4xl max-h-[90vh] overflow-y-auto">
                        <div className="flex justify-between items-center mb-4">
                            <h3 className="text-lg font-semibold">
                                Employee Leave Details - {selectedEmployeeDetail.employeeName}
                            </h3>
                            <button
                                onClick={() => setShowEmployeeDetailModal(false)}
                                className="text-gray-400 hover:text-gray-600"
                            >
                                ✕
                            </button>
                        </div>
                        
                        <div className="space-y-6">
                            {/* Employee Information */}
                            <div className="grid grid-cols-2 gap-4">
                                <div>
                                    <h4 className="font-medium text-gray-900 mb-2">Employee Information</h4>
                                    <div className="space-y-2 text-sm">
                                        <div><strong>Employee No:</strong> {selectedEmployeeDetail.empNo}</div>
                                        <div><strong>Name:</strong> {selectedEmployeeDetail.employeeName}</div>
                                        <div><strong>Designation:</strong> {selectedEmployeeDetail.designation}</div>
                                        <div><strong>Department:</strong> {selectedEmployeeDetail.department}</div>
                                        <div><strong>Date of Joining:</strong> {new Date(selectedEmployeeDetail.dateOfJoining).toLocaleDateString()}</div>
                                    </div>
                                </div>
                            </div>

                            {/* Leave Balances */}
                            <div>
                                <h4 className="font-medium text-gray-900 mb-4">Leave Balances</h4>
                                <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                                    {Object.entries(selectedEmployeeDetail.leaveTypes).map(([leaveType, details]: [string, any]) => (
                                        <div key={leaveType} className="border rounded-lg p-4">
                                            <h5 className="font-medium text-lg mb-2">{leaveType}</h5>
                                            <div className="space-y-1 text-sm">
                                                <div><strong>Opening Balance:</strong> {details.openingBalance}</div>
                                                <div><strong>Credits:</strong> {details.credits}</div>
                                                <div><strong>Debits:</strong> {details.debits}</div>
                                                <div><strong>Closing Balance:</strong> {details.closingBalance}</div>
                                            </div>
                                        </div>
                                    ))}
                                </div>
                            </div>

                            {/* Transaction History */}
                            <div>
                                <h4 className="font-medium text-gray-900 mb-4">Transaction History</h4>
                                {Object.entries(selectedEmployeeDetail.leaveTypes).map(([leaveType, details]: [string, any]) => (
                                    <div key={leaveType} className="mb-6">
                                        <h5 className="font-medium mb-2">{leaveType} Transactions</h5>
                                        <div className="overflow-x-auto">
                                            <table className="min-w-full divide-y divide-gray-200">
                                                <thead className="bg-gray-50">
                                                    <tr>
                                                        <th className="px-4 py-2 text-left text-xs font-medium text-gray-500">Date</th>
                                                        <th className="px-4 py-2 text-left text-xs font-medium text-gray-500">Type</th>
                                                        <th className="px-4 py-2 text-left text-xs font-medium text-gray-500">Days</th>
                                                        <th className="px-4 py-2 text-left text-xs font-medium text-gray-500">Opening</th>
                                                        <th className="px-4 py-2 text-left text-xs font-medium text-gray-500">Closing</th>
                                                        <th className="px-4 py-2 text-left text-xs font-medium text-gray-500">Reason</th>
                                                    </tr>
                                                </thead>
                                                <tbody className="bg-white divide-y divide-gray-200">
                                                    {details.transactions.map((transaction: any, index: number) => (
                                                        <tr key={index}>
                                                            <td className="px-4 py-2 text-sm">
                                                                {new Date(transaction.startDate).toLocaleDateString()}
                                                            </td>
                                                            <td className="px-4 py-2 text-sm">
                                                                <span className={`px-2 py-1 text-xs rounded ${
                                                                    transaction.transactionType === 'CREDIT' 
                                                                        ? 'bg-green-100 text-green-800' 
                                                                        : 'bg-red-100 text-red-800'
                                                                }`}>
                                                                    {transaction.transactionType}
                                                                </span>
                                                            </td>
                                                            <td className="px-4 py-2 text-sm">{transaction.days}</td>
                                                            <td className="px-4 py-2 text-sm">{transaction.openingBalance}</td>
                                                            <td className="px-4 py-2 text-sm">{transaction.closingBalance}</td>
                                                            <td className="px-4 py-2 text-sm">{transaction.reason}</td>
                                                        </tr>
                                                    ))}
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                ))}
                            </div>
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
}
