const leaveRegisterService = require('../services/leaveRegisterService');

/**
 * @desc    Get Leave Register data
 * @route   GET /api/leaves/register
 * @access  Private (Manager, HOD, HR, Admin)
 */
exports.getRegister = async (req, res) => {
    try {
        const { divisionId, departmentId, searchTerm, month, year } = req.query;

        // Build filters object based on user role and query
        const filters = {
            divisionId,
            departmentId,
            searchTerm,
        };

        // If user is HOD/Manager, ensure their scope is applied
        // (This is usually handled by applyScopeFilter middleware, 
        // but we can pass it explicitly if needed)
        if (req.user.role === 'hod' || req.user.role === 'manager') {
            if (req.user.divisionMapping) {
                filters.divisionId = req.user.divisionMapping.division_id;
                filters.departmentId = req.user.divisionMapping.department_id;
            }
        }

        const registerData = await leaveRegisterService.getLeaveRegister(filters, month, year);

        res.status(200).json({
            success: true,
            count: registerData.length,
            data: registerData,
        });
    } catch (error) {
        console.error('Error fetching leave register:', error);
        res.status(500).json({
            success: false,
            message: 'Error fetching leave register',
            error: error.message,
        });
    }
};

/**
 * @desc    Get detailed leave register for a specific employee
 * @route   GET /api/leaves/register/employee/:employeeId
 * @access  Private (Manager, HOD, HR, Admin)
 */
exports.getEmployeeRegister = async (req, res) => {
    try {
        const { employeeId } = req.params;
        const { startDate, endDate } = req.query;

        if (!employeeId) {
            return res.status(400).json({
                success: false,
                message: 'Employee ID is required',
            });
        }

        // Get employee's complete leave register
        const employeeData = await leaveRegisterService.getEmployeeRegister(employeeId);
        
        // If date range is specified, filter transactions
        if (startDate && endDate) {
            const start = new Date(startDate);
            const end = new Date(endDate);
            
            // Filter transactions for each leave type
            Object.keys(employeeData.leaveTypes).forEach(leaveType => {
                employeeData.leaveTypes[leaveType].transactions = 
                    employeeData.leaveTypes[leaveType].transactions.filter(transaction => {
                        const transactionDate = new Date(transaction.startDate);
                        return transactionDate >= start && transactionDate <= end;
                    });
            });
        }

        res.status(200).json({
            success: true,
            data: employeeData,
        });
    } catch (error) {
        console.error('Error fetching employee leave register:', error);
        res.status(500).json({
            success: false,
            message: 'Error fetching employee leave register',
            error: error.message,
        });
    }
};

/**
 * @desc    Adjust CL balance for an employee
 * @route   POST /api/leaves/register/adjust-cl
 * @access  Private (HR, Admin, Super Admin)
 */
exports.adjustCLBalance = async (req, res) => {
    try {
        const { employeeId, clBalance, reason } = req.body;

        if (!employeeId || clBalance === undefined || !reason) {
            return res.status(400).json({
                success: false,
                message: 'Employee ID, CL balance, and reason are required'
            });
        }

        // Create adjustment transaction in leave register
        const transactionData = {
            employeeId,
            leaveType: 'CL',
            transactionType: 'ADJUSTMENT',
            startDate: new Date(),
            endDate: new Date(),
            days: clBalance,
            reason: `Balance Adjustment: ${reason}`,
            status: 'APPROVED',
            autoGenerated: false
        };

        const adjustment = await leaveRegisterService.addTransaction(transactionData);

        res.status(200).json({
            success: true,
            message: 'CL balance adjusted successfully',
            data: adjustment
        });
    } catch (error) {
        console.error('Error adjusting CL balance:', error);
        res.status(500).json({
            success: false,
            message: 'Error adjusting CL balance',
            error: error.message
        });
    }
};

/**
 * @desc    Get employee ledger for a specific leave type
 * @route   GET /api/leaves/register/employee/:employeeId/ledger/:leaveType
 * @access  Private (Manager, HOD, HR, Admin)
 */
exports.getEmployeeLedger = async (req, res) => {
    try {
        const { employeeId, leaveType } = req.params;
        const { startDate, endDate } = req.query;

        if (!employeeId || !leaveType) {
            return res.status(400).json({
                success: false,
                message: 'Employee ID and leave type are required',
            });
        }

        const start = startDate ? new Date(startDate) : new Date(new Date().getFullYear(), 0, 1);
        const end = endDate ? new Date(endDate) : new Date();

        const ledger = await leaveRegisterService.getEmployeeLedger(employeeId, leaveType, start, end);

        res.status(200).json({
            success: true,
            data: ledger,
        });
    } catch (error) {
        console.error('Error fetching employee ledger:', error);
        res.status(500).json({
            success: false,
            message: 'Error fetching employee ledger',
            error: error.message,
        });
    }
};
