/**
 * CCL register reconciliation: ledger sort order + balance chain (unit, no DB).
 */
const {
  calculateClosingBalance,
  collectTxnRefsForLeaveType,
} = require('../leaveRegisterYearLedgerService');

function buildFakeYearDoc(monthTxs) {
  return [
    {
      financialYearStart: new Date('2026-01-01'),
      months: [
        {
          payrollCycleMonth: 5,
          payrollCycleYear: 2026,
          payPeriodStart: new Date('2026-04-26'),
          payPeriodEnd: new Date('2026-05-25'),
          transactions: monthTxs,
        },
      ],
    },
  ];
}

/** Employee 1890 May 2026 — historical startDates (debit before matching OD credit). */
function may1890Transactions() {
  return [
    {
      leaveType: 'CCL',
      transactionType: 'CREDIT',
      days: 1,
      startDate: new Date('2026-05-02T18:30:00.000Z'),
      autoGeneratedType: 'OD_HOLIDAY_WO_CO_CREDIT',
      at: new Date('2026-05-03'),
    },
    {
      leaveType: 'CCL',
      transactionType: 'DEBIT',
      days: 1,
      startDate: new Date('2026-05-05T18:30:00.000Z'),
      at: new Date('2026-05-06'),
    },
    {
      leaveType: 'CCL',
      transactionType: 'CREDIT',
      days: 1,
      startDate: new Date('2026-05-09T18:30:00.000Z'),
      autoGeneratedType: 'OD_HOLIDAY_WO_CO_CREDIT',
      at: new Date('2026-05-10'),
    },
    {
      leaveType: 'CCL',
      transactionType: 'DEBIT',
      days: 1,
      startDate: new Date('2026-05-10T18:30:00.000Z'),
      at: new Date('2026-05-11'),
    },
    {
      leaveType: 'CCL',
      transactionType: 'DEBIT',
      days: 1,
      startDate: new Date('2026-05-14T18:30:00.000Z'),
      at: new Date('2026-05-15'),
    },
    {
      leaveType: 'CCL',
      transactionType: 'CREDIT',
      days: 1,
      startDate: new Date('2026-05-16T18:30:00.000Z'),
      autoGeneratedType: 'OD_HOLIDAY_WO_CO_CREDIT',
      at: new Date('2026-05-17'),
    },
    {
      leaveType: 'CCL',
      transactionType: 'CREDIT',
      days: 1,
      startDate: new Date('2026-05-23T18:30:00.000Z'),
      autoGeneratedType: 'OD_HOLIDAY_WO_CO_CREDIT',
      at: new Date('2026-05-24'),
    },
    {
      leaveType: 'CCL',
      transactionType: 'DEBIT',
      days: 1,
      startDate: new Date('2026-05-24T18:30:00.000Z'),
      at: new Date('2026-05-25'),
    },
  ];
}

function closingAfterChain(docs) {
  const refs = collectTxnRefsForLeaveType(docs, 'CCL');
  let bal = 0;
  for (const { tx } of refs) {
    bal = calculateClosingBalance(bal, tx);
  }
  return bal;
}

describe('CCL ledger reconciliation (unit)', () => {
  test('May 1890 scenario: credits-before-debits sort yields closing 0 (not 1)', () => {
    const docs = buildFakeYearDoc(may1890Transactions());
    const closing = closingAfterChain(docs);
    expect(closing).toBe(0);
  });

  test('same txs in raw startDate order would incorrectly leave balance 1', () => {
    const txs = may1890Transactions();
    const sorted = [...txs].sort(
      (a, b) => new Date(a.startDate).getTime() - new Date(b.startDate).getTime()
    );
    let bal = 0;
    for (const tx of sorted) {
      bal = calculateClosingBalance(bal, tx);
    }
    expect(bal).toBe(1);
  });

  test('credits are ordered before debits within the same payroll month', () => {
    const docs = buildFakeYearDoc(may1890Transactions());
    const refs = collectTxnRefsForLeaveType(docs, 'CCL');
    const types = refs.map((r) => r.tx.transactionType);
    const firstDebitIdx = types.indexOf('DEBIT');
    const lastCreditIdx = types.lastIndexOf('CREDIT');
    expect(firstDebitIdx).toBeGreaterThan(lastCreditIdx);
  });
});
