/**
 * Production-style simulations for multi–leave-type annual grid + scheduled CREDIT lines.
 * No database; pure leaveRegisterYearService behavior.
 */
const {
  appendMonthlyClScheduledCreditTransactions,
  appendMonthlyScheduledCreditByGetter,
  applyProRataGridToExistingMonthSlots,
  normalizeTierMonthlyCredits,
} = require('../leaveRegisterYearService');
const { syncSlotLegacyToScheduledMap } = require('../../utils/leaveRegisterScheduledCredits');

function make12Slots() {
  const base = new Date('2026-04-01T00:00:00.000Z');
  return Array.from({ length: 12 }, (_, i) => {
    const start = new Date(base);
    start.setUTCMonth(start.getUTCMonth() + i);
    const end = new Date(start);
    end.setUTCDate(28);
    return {
      payrollMonthIndex: i + 1,
      label: `M${i + 1}`,
      payPeriodStart: new Date(start),
      payPeriodEnd: new Date(end),
      payrollCycleMonth: (start.getUTCMonth() + 1) % 12 || 12,
      payrollCycleYear: 2026,
      clCredits: 1,
      elCredits: 0,
      compensatoryOffs: 0,
      scheduledCreditsByType: {},
      transactions: [],
    };
  });
}

describe('leaveRegisterYear.annualMultiType (simulation)', () => {
  it('appendMonthlyClScheduledCreditTransactions posts one CL CREDIT per month with clCredits > 0', () => {
    const months = make12Slots();
    for (const m of months) m.clCredits = 1;
    appendMonthlyClScheduledCreditTransactions(months, {});
    const tx = months.flatMap((m) => m.transactions || []);
    const cl = tx.filter((t) => t.leaveType === 'CL' && t.transactionType === 'CREDIT' && t.autoGeneratedType === 'MONTHLY_CL_SCHEDULE');
    expect(cl.length).toBe(12);
    expect(cl[0].days).toBe(1);
  });

  it('appendMonthlyScheduledCreditByGetter posts EL scheduled credits from elCredits getter', () => {
    const months = make12Slots();
    for (const m of months) {
      m.elCredits = 2.5;
      m.clCredits = 0;
    }
    appendMonthlyScheduledCreditByGetter(
      months,
      'EL',
      (m) => m.elCredits,
      'MONTHLY_EL_SCHEDULE',
      'EL',
      {}
    );
    const el = months.flatMap((m) => m.transactions).filter((t) => t.autoGeneratedType === 'MONTHLY_EL_SCHEDULE');
    expect(el.length).toBe(12);
    expect(el.every((t) => t.leaveType === 'EL' && t.transactionType === 'CREDIT')).toBe(true);
  });

  it('appendMonthlyScheduledCreditByGetter uses compensatoryOffs for CCL path (getter)', () => {
    const months = make12Slots();
    for (const m of months) {
      m.compensatoryOffs = 0.5;
      m.clCredits = 0;
    }
    appendMonthlyScheduledCreditByGetter(months, 'CCL', (m) => m.compensatoryOffs, 'MONTHLY_CCL_SCHEDULE', 'CCL', {});
    const ccl = months.flatMap((m) => m.transactions).filter((t) => t.autoGeneratedType === 'MONTHLY_CCL_SCHEDULE');
    expect(ccl.length).toBe(12);
    expect(ccl[0].days).toBe(0.5);
  });

  it('applyProRataGridToExistingMonthSlots: el field writes elCredits and syncs scheduled map', () => {
    const months = make12Slots();
    const doj = new Date('2015-01-15T00:00:00.000Z');
    const grid = normalizeTierMonthlyCredits({ casualLeave: 12 }, 12);
    expect(grid.length).toBe(12);
    applyProRataGridToExistingMonthSlots(months, grid, doj, 'el', null, {});
    for (const m of months) {
      expect(m.elCredits).toBeGreaterThanOrEqual(0);
      syncSlotLegacyToScheduledMap(m);
      expect(m.scheduledCreditsByType.EL).toBe(m.elCredits);
    }
  });

  it('applyProRataGridToExistingMonthSlots: ccl field writes compensatoryOffs', () => {
    const months = make12Slots();
    const doj = new Date('2015-01-15T00:00:00.000Z');
    const grid = Array(12).fill(1);
    applyProRataGridToExistingMonthSlots(months, grid, doj, 'ccl', null, {});
    const sumCcl = months.reduce((a, m) => a + (Number(m.compensatoryOffs) || 0), 0);
    expect(sumCcl).toBeGreaterThan(0);
  });

  it('applyProRataGridToExistingMonthSlots: map + PL code writes scheduledCreditsByType[PL]', () => {
    const months = make12Slots();
    const doj = new Date('2015-01-15T00:00:00.000Z');
    const grid = Array(12).fill(0.5);
    applyProRataGridToExistingMonthSlots(months, grid, doj, 'map', 'PL', {});
    for (const m of months) {
      expect(m.scheduledCreditsByType.PL).toBeGreaterThanOrEqual(0);
    }
  });

  it('throughDate on appendMonthlyClScheduledCreditTransactions limits periods', () => {
    const months = make12Slots();
    for (const m of months) m.clCredits = 1;
    const cutoff = new Date('2026-08-10T00:00:00.000Z');
    appendMonthlyClScheduledCreditTransactions(months, { throughDate: cutoff });
    const tx = months.flatMap((m) => m.transactions || []);
    const cl = tx.filter((t) => t.leaveType === 'CL' && t.transactionType === 'CREDIT');
    expect(cl.length).toBeLessThan(12);
    expect(cl.length).toBeGreaterThan(0);
  });
});
