/**
 * Read-only HRMS endpoints the assistant router may call.
 * Paths are relative to /api (no leading slash on path after /api).
 */
const ENDPOINT_CATALOG = [
  {
    id: 'auth_me',
    method: 'GET',
    path: 'auth/me',
    description: 'Current logged-in user profile, role, and permissions context.',
    roles: ['*'],
    queryParams: [],
  },
  {
    id: 'dashboard_stats',
    method: 'GET',
    path: 'dashboard/stats',
    description: 'Dashboard summary counts (leaves, attendance, pending items) for the user scope.',
    roles: ['*'],
    queryParams: [],
  },
  {
    id: 'employees_list',
    method: 'GET',
    path: 'employees',
    description: 'List/search employees visible to the user. Use search, department, division filters.',
    roles: ['manager', 'hod', 'hr', 'sub_admin', 'super_admin'],
    queryParams: ['search', 'department', 'division', 'page', 'limit', 'is_active'],
  },
  {
    id: 'employee_detail',
    method: 'GET',
    path: 'employees/{empNo}',
    description: 'Single employee profile by employee number (emp_no).',
    roles: ['*'],
    pathParams: ['empNo'],
    queryParams: [],
  },
  {
    id: 'employees_count',
    method: 'GET',
    path: 'employees/count',
    description: 'Employee count in user data scope. Use is_active=true for active only, is_active=false for inactive.',
    roles: ['manager', 'hod', 'hr', 'sub_admin', 'super_admin'],
    queryParams: ['is_active'],
  },
  {
    id: 'attendance_list',
    method: 'GET',
    path: 'attendance/list',
    description: 'Attendance records list for a date range. Needs startDate, endDate; optional employeeNumber (emp_no), department.',
    roles: ['*'],
    queryParams: ['startDate', 'endDate', 'employeeNumber', 'department', 'division', 'page', 'limit'],
  },
  {
    id: 'attendance_monthly',
    method: 'GET',
    path: 'attendance/monthly',
    description: 'Monthly attendance grid for a month (YYYY-MM).',
    roles: ['*'],
    queryParams: ['month', 'empNo', 'department', 'division'],
  },
  {
    id: 'attendance_monthly_summary',
    method: 'GET',
    path: 'attendance/monthly-summary/{employeeId}',
    description: 'Monthly attendance summary for one employee (employeeId = emp_no).',
    roles: ['*'],
    pathParams: ['employeeId'],
    queryParams: ['month'],
  },
  {
    id: 'leaves_my',
    method: 'GET',
    path: 'leaves/my',
    description: 'Current user own leave applications and status.',
    roles: ['*'],
    queryParams: ['status', 'year'],
  },
  {
    id: 'leaves_list',
    method: 'GET',
    path: 'leaves',
    description: 'Leave requests in scope. Use search=emp_no for a specific employee. Filter by status, fromDate, toDate.',
    roles: ['manager', 'hod', 'hr', 'sub_admin', 'super_admin'],
    queryParams: ['status', 'fromDate', 'toDate', 'search', 'department', 'page', 'limit'],
  },
  {
    id: 'employee_applications',
    method: 'GET',
    path: 'employee-applications',
    description: 'Employee onboarding/joining applications. Status: pending, verified, approved, rejected.',
    roles: ['manager', 'hod', 'hr', 'sub_admin', 'super_admin'],
    queryParams: ['status', 'search', 'division_id', 'department_id'],
  },
  {
    id: 'leaves_stats',
    method: 'GET',
    path: 'leaves/stats',
    description: 'Leave statistics aggregates for dashboards.',
    roles: ['*'],
    queryParams: ['year', 'department'],
  },
  {
    id: 'leaves_pending',
    method: 'GET',
    path: 'leaves/pending-approvals',
    description: 'Leave requests waiting for the user approval.',
    roles: ['manager', 'hod', 'hr', 'sub_admin', 'super_admin'],
    queryParams: [],
  },
  {
    id: 'leave_balance',
    method: 'GET',
    path: 'leaves/earned/balance/{employeeId}',
    description: 'Earned leave (EL) balance for an employee.',
    roles: ['*'],
    pathParams: ['employeeId'],
    queryParams: [],
  },
  {
    id: 'leave_register',
    method: 'GET',
    path: 'leaves/register/employee/{employeeId}',
    description: 'Leave register detail for an employee in the financial year.',
    roles: ['*'],
    pathParams: ['employeeId'],
    queryParams: ['year'],
  },
  {
    id: 'holidays_my',
    method: 'GET',
    path: 'holidays/my',
    description: 'Upcoming and past holidays applicable to the user.',
    roles: ['*'],
    queryParams: ['year'],
  },
  {
    id: 'loans_my',
    method: 'GET',
    path: 'loans/my',
    description: 'Current user loan applications and repayment status.',
    roles: ['*'],
    queryParams: [],
  },
  {
    id: 'loans_list',
    method: 'GET',
    path: 'loans',
    description: 'All loans in HR scope. For managers/HR only.',
    roles: ['hr', 'sub_admin', 'super_admin', 'hod', 'manager'],
    queryParams: ['status', 'empNo', 'page', 'limit'],
  },
  {
    id: 'loans_pending',
    method: 'GET',
    path: 'loans/pending-approvals',
    description: 'Loan requests pending approval for the user.',
    roles: ['manager', 'hod', 'hr', 'sub_admin', 'super_admin'],
    queryParams: [],
  },
  {
    id: 'payroll_payslip',
    method: 'GET',
    path: 'payroll/payslip/{employeeId}/{month}',
    description: 'Payslip for employee and month (month format YYYY-MM).',
    roles: ['*'],
    pathParams: ['employeeId', 'month'],
    queryParams: [],
  },
  {
    id: 'payroll_list',
    method: 'GET',
    path: 'payroll',
    description: 'Payroll records list for a month in user scope.',
    roles: ['hr', 'sub_admin', 'super_admin', 'hod', 'manager'],
    queryParams: ['month', 'department', 'division', 'page', 'limit'],
  },
  {
    id: 'ot_list',
    method: 'GET',
    path: 'ot',
    description: 'Overtime requests in scope.',
    roles: ['*'],
    queryParams: ['status', 'startDate', 'endDate', 'empNo', 'page', 'limit'],
  },
  {
    id: 'ot_pending',
    method: 'GET',
    path: 'ot/pending-approvals',
    description: 'OT requests pending user approval.',
    roles: ['manager', 'hod', 'hr', 'sub_admin', 'super_admin'],
    queryParams: [],
  },
  {
    id: 'permissions_list',
    method: 'GET',
    path: 'permissions',
    description: 'Gate pass / permission requests in scope.',
    roles: ['*'],
    queryParams: ['status', 'startDate', 'endDate', 'empNo', 'page', 'limit'],
  },
  {
    id: 'permissions_pending',
    method: 'GET',
    path: 'permissions/pending-approvals',
    description: 'Permission requests pending approval.',
    roles: ['manager', 'hod', 'hr', 'sub_admin', 'super_admin'],
    queryParams: [],
  },
  {
    id: 'notifications',
    method: 'GET',
    path: 'notifications',
    description: 'In-app notifications for the current user.',
    roles: ['*'],
    queryParams: ['page', 'limit', 'unreadOnly'],
  },
  {
    id: 'notifications_unread',
    method: 'GET',
    path: 'notifications/unread-count',
    description: 'Unread notification count.',
    roles: ['*'],
    queryParams: [],
  },
  {
    id: 'settings_leave_policy',
    method: 'GET',
    path: 'settings/leave-policy',
    description: 'Organisation leave policy (EL/CL rules) — read-only reference.',
    roles: ['*'],
    queryParams: [],
  },
  {
    id: 'departments',
    method: 'GET',
    path: 'departments',
    description: 'List of departments visible to the user.',
    roles: ['*'],
    queryParams: [],
  },
];

function getCatalogForRole(role) {
  const r = (role || 'employee').toLowerCase();
  return ENDPOINT_CATALOG.filter((ep) => {
    if (!ep.roles || ep.roles.includes('*')) return true;
    return ep.roles.includes(r);
  });
}

function findCatalogEntry(endpointId) {
  return ENDPOINT_CATALOG.find((e) => e.id === endpointId);
}

module.exports = {
  ENDPOINT_CATALOG,
  getCatalogForRole,
  findCatalogEntry,
};
